import {describe,expect,it} from 'vitest';
import {readFileSync,writeFileSync,mkdtempSync,existsSync,mkdirSync} from 'node:fs';
import {join,resolve,relative} from 'node:path';const tmpdir=()=>{const p=resolve('.superpowers');mkdirSync(p,{recursive:true});return p};
import {spawnSync} from 'node:child_process';
import {compareRegions,validateVisualEnvironment} from '../../apps/mobile/src/ui/visual-runner.js';

describe('Task 7 final acceptance',()=>{
 it('routes the application to BattleScreen and keeps preview explicitly development-only',()=>{const text=readFileSync('apps/mobile/app/index.tsx','utf8');expect(text).toContain('<BattleScreen');expect(text).toContain('__DEV__')});
 it('uses changed-pixel ratio without a global maximum veto',()=>{const golden={width:2,height:1,data:new Uint8Array(8)};const actual={...golden,data:new Uint8Array([255,0,0,0,0,0,0,0])};expect(compareRegions(actual,golden,[{id:'x',x:0,y:0,width:2,height:1,maxChangedRatio:.5,maxChannelDelta:10}],[])[0]?.pass).toBe(true)});
 it('fails closed when any visual environment pin differs',()=>{const pins={node:'24.18.0',pnpm:'11.13.0',platform:'android' as const,adapter:'maestro-android@1',viewport:[390,844] as const,locale:'ko-KR',runner:'ubuntu-24.04-x64',gpu:'SwiftShader',font:'Inter@1',fontScale:1};for(const key of Object.keys(pins) as Array<keyof typeof pins>)expect(()=>validateVisualEnvironment(pins,{...pins,[key]:key==='fontScale'?2:'wrong'})).toThrow(new RegExp(key))});
 it('stores a structured unique acceptance matrix',()=>{const rows=JSON.parse(readFileSync('config/ui-acceptance-matrix.v1.json','utf8')) as Array<Record<string,unknown>>;expect(rows.length).toBeGreaterThan(0);expect(new Set(rows.map(x=>x.requirementId)).size).toBe(rows.length);for(const row of rows)for(const key of ['requirementId','platform','viewport','method','expectedStates','evidence','status'])expect(row).toHaveProperty(key)});
 it('wires real Maestro commands and has no orphan assertion registry entries',()=>{const adapters=JSON.parse(readFileSync('config/ui-visual-adapters.v1.json','utf8'));for(const platform of ['ios','android']){const a=adapters.adapters[platform];expect(a.command.slice(0,2)).toEqual(['node','tools/capture-ui-maestro.mjs']);expect(a.command).toContain(`.maestro/capture-${platform}.yaml`);expect(existsSync(`.maestro/capture-${platform}.yaml`)).toBe(true)}const registry=JSON.parse(readFileSync('config/ui-assertion-registry.v1.json','utf8'));expect(registry.assertions.map((x:any)=>x.assertionId)).toEqual(['strict-wire-render'])});
 it('commits a strict visual manifest schema and rejects traversal paths',()=>{const schema=JSON.parse(readFileSync('schemas/ui-visual-manifest.schema.json','utf8'));expect(schema.$id).toBe('UiVisualManifestV1');expect(JSON.stringify(schema)).toContain('date-time');expect(schema.$defs.path.pattern).toContain('\\.\\.')});
 it('rejects the required unapproved beta fixture',()=>{const result=spawnSync(process.execPath,['tools/check-ui-assets.mjs','--target','beta'],{env:{...process.env,UI_ASSET_MANIFEST:'tests/fixtures/ui/invalid-beta-unapproved.json'},encoding:'utf8'});expect(result.status).toBe(1);expect(result.stderr).toContain('beta requires APPROVED')});
 it('keeps the executable visual gate honestly blocked by the exact repository runtime first',()=>{const result=spawnSync(process.execPath,['tools/run-ui-visual.mjs'],{env:{...process.env,UI_PLATFORM:'android'},encoding:'utf8'});expect(result.status).toBe(2);expect(result.stderr).toContain('runtime pin mismatch')});
 it('keeps Expo and Maestro on the exact approved mobile identity',()=>{const identity=JSON.parse(readFileSync('config/mobile-identity.v1.json','utf8')),app=JSON.parse(readFileSync('apps/mobile/app.json','utf8'));expect(app.expo.ios.bundleIdentifier).toBe(identity.appId);expect(app.expo.android.package).toBe(identity.appId);for(const platform of ['ios','android'])expect(readFileSync(`.maestro/capture-${platform}.yaml`,'utf8')).toContain(`appId: ${identity.appId}`)});
 it('invokes a configured capture adapter and compares actual PNG fixtures',()=>{const dir=mkdtempSync(join(tmpdir(),'ui-visual-')),golden=join(dir,'golden.png'),current=join(dir,'current.png'),mask=join(dir,'mask.png'),adapters=join(dir,'adapters.json'),goldens=join(dir,'goldens.json'),evidence=join(dir,'evidence.json');const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGP4z8DwHwAFAAH/iZk9HQAAAABJRU5ErkJggg==','base64');const maskPng=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAC0lEQVR4nGNgAAIAAAUAAXpeqz8AAAAASUVORK5CYII=','base64');writeFileSync(golden,png);writeFileSync(mask,maskPng);writeFileSync(adapters,JSON.stringify({schemaVersion:'1.0.0',adapters:{android:{id:'mock@1',os:'test-os',device:'test-device',runner:'test-runner',gpu:'test-gpu',command:[process.execPath,resolve('tests/fixtures/ui/mock-capture-adapter.mjs')]}}}));writeFileSync(goldens,JSON.stringify({schemaVersion:'1.0.0',status:'APPROVED',baselineAutoUpdate:false,masks:[{id:'mask',platform:'android',viewport:'390x844',x:0,y:0,width:1,height:1,maskFile:mask}],goldens:[{platform:'android',viewport:'390x844',source:'DEVICE_CAPTURE',approvedBy:'human',approvedAt:'2026-07-19T00:00:00Z',goldenFile:golden,currentFile:current,regions:[{id:'screen',x:0,y:0,width:1,height:1,maxChangedRatio:0,maxChannelDelta:0}]}]}));writeFileSync(evidence,JSON.stringify({status:'BLOCKED_MANUAL_DEVICE_EVIDENCE',pins:{node:process.versions.node,pnpm:'11.13.0',runner:'test-runner',ios:'MANUAL_REQUIRED',android:'MANUAL_REQUIRED',emulator:'test-device',gpu:'test-gpu',font:'test-font',fontScale:1,locale:'ko-KR',seed:7182026,time:'2026-07-18T00:00:00.000Z'},conceptImagesAreGolden:false,baselineAutoUpdate:false,candidateThresholds:{ssim:.97,rgbAbsoluteDifference:.04,maxDifferentPixelRatio:.05,calibrated:false},masks:['USER_DATA'],requiredViewports:[[390,844]]}));const result=spawnSync(process.execPath,['tools/run-ui-visual.mjs'],{env:{...process.env,UI_PLATFORM:'android',UI_NODE:process.versions.node,UI_PNPM:'11.13.0',UI_ADAPTER:'mock@1',UI_OS:'test-os',UI_DEVICE:'test-device',UI_RUNNER:'test-runner',UI_GPU:'test-gpu',UI_FONT:'test-font',UI_FONT_SCALE:'1',UI_LOCALE:'ko-KR',UI_SEED:'7182026',UI_TIME:'2026-07-18T00:00:00.000Z',UI_EVIDENCE_MANIFEST:evidence,UI_ADAPTER_MANIFEST:adapters,UI_GOLDEN_MANIFEST:goldens,UI_MOCK_SOURCE:golden},encoding:'utf8'});expect(result.status,result.stderr).toBe(0);expect(JSON.parse(result.stdout).regions[0].pass).toBe(true)});
});
