import {describe,expect,it} from 'vitest';
import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {compareRegions,validateVisualEnvironment} from '../../apps/mobile/src/ui/visual-runner.js';

describe('Task 7 final acceptance',()=>{
 it('routes the application to BattleScreen and keeps preview explicitly development-only',()=>{const text=readFileSync('apps/mobile/app/index.tsx','utf8');expect(text).toContain('<BattleScreen');expect(text).toContain('__DEV__')});
 it('uses changed-pixel ratio without a global maximum veto',()=>{const golden={width:2,height:1,data:new Uint8Array(8)};const actual={...golden,data:new Uint8Array([255,0,0,0,0,0,0,0])};expect(compareRegions(actual,golden,[{id:'x',x:0,y:0,width:2,height:1,maxChangedRatio:.5,maxChannelDelta:10}],[])[0]?.pass).toBe(true)});
 it('fails closed when any visual environment pin differs',()=>{const pins={node:'24.18.0',pnpm:'11.13.0',platform:'android' as const,adapter:'maestro-android@1',viewport:[390,844] as const,locale:'ko-KR',runner:'ubuntu-24.04-x64',gpu:'SwiftShader',font:'Inter@1',fontScale:1};for(const key of Object.keys(pins) as Array<keyof typeof pins>)expect(()=>validateVisualEnvironment(pins,{...pins,[key]:key==='fontScale'?2:'wrong'})).toThrow(new RegExp(key))});
 it('stores a structured unique acceptance matrix',()=>{const rows=JSON.parse(readFileSync('config/ui-acceptance-matrix.v1.json','utf8')) as Array<Record<string,unknown>>;expect(rows.length).toBeGreaterThan(0);expect(new Set(rows.map(x=>x.requirementId)).size).toBe(rows.length);for(const row of rows)for(const key of ['requirementId','platform','viewport','method','expectedStates','evidence','status'])expect(row).toHaveProperty(key)});
 it('rejects the required unapproved beta fixture',()=>{const result=spawnSync(process.execPath,['tools/check-ui-assets.mjs','--target','beta'],{env:{...process.env,UI_ASSET_MANIFEST:'tests/fixtures/ui/invalid-beta-unapproved.json'},encoding:'utf8'});expect(result.status).toBe(1);expect(result.stderr).toContain('beta requires APPROVED')});
 it('keeps the executable visual gate honestly blocked by the exact repository runtime first',()=>{const result=spawnSync(process.execPath,['tools/run-ui-visual.mjs'],{env:{...process.env,UI_PLATFORM:'android'},encoding:'utf8'});expect(result.status).toBe(2);expect(result.stderr).toContain('runtime pin mismatch')});
 it('invokes a configured capture adapter and compares real RGBA fixtures',()=>{const dir=mkdtempSync(join(tmpdir(),'ui-visual-')),golden=join(dir,'golden.json'),current=join(dir,'current.json'),adapters=join(dir,'adapters.json'),goldens=join(dir,'goldens.json'),evidence=join(dir,'evidence.json');writeFileSync(golden,JSON.stringify({width:1,height:1,data:[0,0,0,255]}));writeFileSync(adapters,JSON.stringify({adapters:{android:{id:'mock@1',os:'test-os',device:'test-device',runner:'test-runner',gpu:'test-gpu',command:[process.execPath,resolve('tests/fixtures/ui/mock-capture-adapter.mjs')]}}}));writeFileSync(goldens,JSON.stringify({status:'APPROVED',masks:[],goldens:[{platform:'android',viewport:'390x844',source:'DEVICE_CAPTURE',approvedBy:'human',approvedAt:'2026-07-19T00:00:00Z',goldenFile:golden,currentFile:current,regions:[{id:'screen',x:0,y:0,width:1,height:1,maxChangedRatio:0,maxChannelDelta:0}]}]}));writeFileSync(evidence,JSON.stringify({pins:{node:process.versions.node,pnpm:'11.13.0',gpu:'test-gpu',font:'test-font',fontScale:1,locale:'ko-KR',seed:7182026,time:'2026-07-18T00:00:00.000Z'}}));const result=spawnSync(process.execPath,['tools/run-ui-visual.mjs'],{env:{...process.env,UI_PLATFORM:'android',UI_NODE:process.versions.node,UI_PNPM:'11.13.0',UI_ADAPTER:'mock@1',UI_OS:'test-os',UI_DEVICE:'test-device',UI_RUNNER:'test-runner',UI_GPU:'test-gpu',UI_FONT:'test-font',UI_FONT_SCALE:'1',UI_LOCALE:'ko-KR',UI_SEED:'7182026',UI_TIME:'2026-07-18T00:00:00.000Z',UI_EVIDENCE_MANIFEST:evidence,UI_ADAPTER_MANIFEST:adapters,UI_GOLDEN_MANIFEST:goldens,UI_MOCK_SOURCE:golden},encoding:'utf8'});expect(result.status,result.stderr).toBe(0);expect(JSON.parse(result.stdout).regions[0]).toMatchObject({pass:true,changedPixelRatio:0,observedMaxChannelDelta:0})});
});
