import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';

type Circle = { cx: number; cy: number; r: number };
type Bundle = {
  publicContent: {
    theme: string;
    imageA: { width: number; height: number };
    imageB: { width: number; height: number };
  };
  privateSolution: {
    differences: Array<{
      objectiveId: string;
      tier: 'NORMAL' | 'HARD';
      hitboxes: { imageA: Circle; imageB: Circle };
    }>;
    finalChallenge: {
      meaning: {
        options: Array<{ id: string }>;
        correctOptionId: string;
      };
    };
  };
};

type Manifest = {
  entries: Array<{ key: string; category: 'ENGLISH' | 'PROVERB' | 'IDIOM' }>;
};

const outputPath = 'apps/mobile/src/learning-demo/registry.ts';

function assertCircle(key: string, circle: Circle): void {
  const finite = [circle.cx, circle.cy, circle.r].every(Number.isFinite);
  if (
    !finite ||
    circle.r <= 0 ||
    circle.r > 1 ||
    circle.cx < 0 ||
    circle.cx > 1 ||
    circle.cy < 0 ||
    circle.cy > 1
  ) {
    throw new Error(`INVALID_HITBOX:${key}`);
  }
}

export function validatePlayableBundle(key: string, bundle: Bundle): void {
  if (bundle.publicContent.theme !== key) throw new Error(`THEME_MISMATCH:${key}`);
  const differences = bundle.privateSolution.differences;
  if (differences.length !== 10) throw new Error(`INVALID_DIFFERENCE_COUNT:${key}`);
  const ids = differences.map((difference) => difference.objectiveId);
  if (new Set(ids).size !== ids.length) throw new Error(`DUPLICATE_OBJECTIVE:${key}`);
  const normal = differences.filter((difference) => difference.tier === 'NORMAL').length;
  const hard = differences.filter((difference) => difference.tier === 'HARD').length;
  if (normal !== 7 || hard !== 3) throw new Error(`INVALID_TIER_COUNTS:${key}`);
  for (const difference of differences) {
    assertCircle(key, difference.hitboxes.imageA);
    assertCircle(key, difference.hitboxes.imageB);
  }
  const meaning = bundle.privateSolution.finalChallenge.meaning;
  if (!meaning.options.some((option) => option.id === meaning.correctOptionId)) {
    throw new Error(`INVALID_CORRECT_OPTION:${key}`);
  }
}

export async function readPngSize(path: string): Promise<{ width: number; height: number }> {
  const bytes = await readFile(path);
  const signature = bytes.subarray(0, 8).toString('hex');
  if (signature !== '89504e470d0a1a0a' || bytes.subarray(12, 16).toString('ascii') !== 'IHDR') {
    throw new Error(`INVALID_PNG:${path}`);
  }
  return { width: bytes.readUInt32BE(16), height: bytes.readUInt32BE(20) };
}

export async function buildPlayableRegistry(root: string): Promise<{
  source: string;
  entries: Array<{ key: string; differenceCount: number; normalCount: number; hardCount: number }>;
}> {
  const allowlist = JSON.parse(
    await readFile(resolve(root, 'content/learning/device-demo.v1.json'), 'utf8'),
  ) as { keys: string[] };
  const manifest = JSON.parse(
    await readFile(resolve(root, 'content/learning/manifest.v1.json'), 'utf8'),
  ) as Manifest;
  if (new Set(allowlist.keys).size !== allowlist.keys.length) throw new Error('DUPLICATE_ALLOWLIST_KEY');

  const manifestByKey = new Map(manifest.entries.map((entry) => [entry.key, entry]));
  const projected = [];
  for (const key of allowlist.keys) {
    const manifestEntry = manifestByKey.get(key);
    if (!manifestEntry) throw new Error(`UNKNOWN_ALLOWLIST_KEY:${key}`);
    const bundle = JSON.parse(
      await readFile(resolve(root, `content/learning/drafts/${key}.json`), 'utf8'),
    ) as Bundle;
    validatePlayableBundle(key, bundle);
    const imageA = await readPngSize(resolve(root, `content/learning/source/${key}-a.png`));
    const imageB = await readPngSize(resolve(root, `content/learning/source/${key}-b.png`));
    for (const [side, actual, declared] of [
      ['A', imageA, bundle.publicContent.imageA],
      ['B', imageB, bundle.publicContent.imageB],
    ] as const) {
      if (actual.width !== declared.width || actual.height !== declared.height) {
        throw new Error(`IMAGE_DIMENSION_MISMATCH:${key}:${side}`);
      }
    }
    if (imageA.width !== imageB.width || imageA.height !== imageB.height) {
      throw new Error(`PAIR_DIMENSION_MISMATCH:${key}`);
    }
    projected.push({
      key,
      category: manifestEntry.category,
      width: imageA.width,
      height: imageA.height,
      differenceCount: bundle.privateSolution.differences.length,
      normalCount: bundle.privateSolution.differences.filter((item) => item.tier === 'NORMAL').length,
      hardCount: bundle.privateSolution.differences.filter((item) => item.tier === 'HARD').length,
    });
  }

  const names = projected.map((entry, index) => ({ ...entry, variable: `bundle${index + 1}` }));
  const source = [
    '// Generated by tools/content/generate-playable-registry.ts. Do not edit.',
    "import { buildDemoEntry, type Bundle } from './data';",
    '',
    'declare const require: (path: string) => number;',
    '',
    ...names.map(
      (entry) =>
        `const ${entry.variable} = require('../../../../content/learning/drafts/${entry.key}.json') as unknown as Bundle;`,
    ),
    '',
    '// Device-demo registry: bundles and assets are packaged locally; no private solution crosses a network boundary.',
    'export const learningDemoEntries = [',
    ...names.map(
      (entry) =>
        `  buildDemoEntry('${entry.category}', ${entry.variable}, { imageA: require('../../../../content/learning/source/${entry.key}-a.png'), imageB: require('../../../../content/learning/source/${entry.key}-b.png') }, { width: ${entry.width}, height: ${entry.height} }),`,
    ),
    '] as const;',
    '',
  ].join('\n');
  return { source, entries: projected };
}

export async function generatePlayableRegistry(root: string, check = false): Promise<void> {
  const { source } = await buildPlayableRegistry(root);
  const target = resolve(root, outputPath);
  if (check) {
    const current = await readFile(target, 'utf8');
    if (current !== source) throw new Error(`GENERATED_REGISTRY_DRIFT:${outputPath}`);
    return;
  }
  await writeFile(target, source, 'utf8');
}

const invokedPath = process.argv[1] ? resolve(process.argv[1]) : '';
if (invokedPath === fileURLToPath(import.meta.url)) {
  await generatePlayableRegistry(process.cwd(), process.argv.includes('--check'));
}
