/**
 * Patch script: append all missing catalog entries using ESM syntax
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const catalogPath = path.join(__dirname, '../../content/learning/catalog.v1.json');
const catalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8'));

const existingKeys = new Set(catalog.entries.map(e => e.key));

const newEntries = [
  {
    "key": "en-phonics-apple",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "BEGINNER",
    "status": "DRAFT",
    "canonicalAnswer": "apple",
    "aliases": ["fruit", "red fruit"],
    "meaning": { "prompt": "What is this fruit called in English?", "options": [{"id":"option_1","label":"Apple"},{"id":"option_2","label":"Orange"},{"id":"option_3","label":"Grape"}], "correctOptionId": "option_1" },
    "sceneBrief": "Phonics apple fruit learning scene",
    "changes": ["Color changes on apple","Leaf shape","Basket color change","Background fruit removed","Bowl color","Shadow removed","Stem length","Worm added","Tag removed","Shine spot"],
    "wordHunts": [{"kind":"NORMAL","prompt":"사과를 찾으세요","object":"apple"},{"kind":"NORMAL","prompt":"과일 바구니를 찾으세요","object":"fruit basket"},{"kind":"SPECIAL","prompt":"나뭇잎을 찾으세요","object":"leaf"}],
    "suddenDeath": {"prompt":"빨간 사과를 찾으세요","object":"red apple"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "gk-space-rover",
    "category": "GENERAL_KNOWLEDGE",
    "language": "en",
    "difficulty": "INTERMEDIATE",
    "status": "DRAFT",
    "canonicalAnswer": "space rover",
    "aliases": ["mars rover", "space vehicle"],
    "meaning": { "prompt": "What is this vehicle called?", "options": [{"id":"option_1","label":"Space Rover"},{"id":"option_2","label":"Submarine"},{"id":"option_3","label":"Airplane"}], "correctOptionId": "option_1" },
    "sceneBrief": "Space rover on Mars surface exploring scene",
    "changes": ["Rover color","Antenna shape","Flag removed","Solar panel color","Wheel count","Camera lens","Crater removed","Rock added","Signal light color","Astronaut removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"화성 탐사선을 찾으세요","object":"space rover"},{"kind":"NORMAL","prompt":"태양광 패널을 찾으세요","object":"solar panel"},{"kind":"SPECIAL","prompt":"분화구를 찾으세요","object":"crater"}],
    "suddenDeath": {"prompt":"탐사선을 찾으세요","object":"space rover"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "ko-proverb-cow-barn",
    "category": "KOREAN",
    "language": "ko",
    "difficulty": "INTERMEDIATE",
    "status": "DRAFT",
    "canonicalAnswer": "소 잃고 외양간 고친다",
    "aliases": ["소 잃고", "외양간"],
    "meaning": { "prompt": "이 속담의 의미는?", "options": [{"id":"option_1","label":"일이 일어난 후에 대비함"},{"id":"option_2","label":"미리 잘 준비함"},{"id":"option_3","label":"남의 일에 참견함"}], "correctOptionId": "option_1" },
    "sceneBrief": "소가 도망간 후 외양간을 고치는 농부 씬",
    "changes": ["농부 옷 색상","외양간 문 색상","닭 제거","지붕 색상","소 색상","도구 추가","울타리 제거","나무 추가","등불 색상","구름 제거"],
    "wordHunts": [{"kind":"NORMAL","prompt":"농부를 찾으세요","object":"farmer"},{"kind":"NORMAL","prompt":"외양간을 찾으세요","object":"cattle barn"},{"kind":"SPECIAL","prompt":"도망간 소를 찾으세요","object":"cow running away"}],
    "suddenDeath": {"prompt":"외양간을 고치는 농부를 찾으세요","object":"farmer fixing barn"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "ko-idiom-birds-one-stone",
    "category": "KOREAN",
    "language": "ko",
    "difficulty": "INTERMEDIATE",
    "status": "DRAFT",
    "canonicalAnswer": "일석이조",
    "aliases": ["一石二鳥", "일거양득"],
    "meaning": { "prompt": "일석이조의 의미는?", "options": [{"id":"option_1","label":"한 가지로 두 가지를 얻음"},{"id":"option_2","label":"두 번 실패함"},{"id":"option_3","label":"새를 잡음"}], "correctOptionId": "option_1" },
    "sceneBrief": "돌 하나로 새 두 마리를 잡는 일석이조 씬",
    "changes": ["돌 색상","새 위치","나뭇잎 색상","구름 제거","나무 색상","새 제거","풀 색상","구름 추가","돌 크기","나무 추가"],
    "wordHunts": [{"kind":"NORMAL","prompt":"돌을 찾으세요","object":"stone"},{"kind":"NORMAL","prompt":"새를 찾으세요","object":"birds"},{"kind":"SPECIAL","prompt":"돌을 던지는 손을 찾으세요","object":"hand throwing stone"}],
    "suddenDeath": {"prompt":"날아가는 새 두 마리를 찾으세요","object":"two birds"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-school-classroom",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "BEGINNER",
    "status": "DRAFT",
    "canonicalAnswer": "classroom",
    "aliases": ["school", "class"],
    "meaning": { "prompt": "What is this place called in English?", "options": [{"id":"option_1","label":"Classroom"},{"id":"option_2","label":"Library"},{"id":"option_3","label":"Kitchen"}], "correctOptionId": "option_1" },
    "sceneBrief": "Busy elementary school classroom learning scene",
    "changes": ["Blackboard color","Chair color","Teacher outfit","Plant removed","Clock hands","Poster removed","Student hat","Pencil color","Bag added","Window blinds"],
    "wordHunts": [{"kind":"NORMAL","prompt":"선생님을 찾으세요","object":"teacher"},{"kind":"NORMAL","prompt":"칠판을 찾으세요","object":"blackboard"},{"kind":"SPECIAL","prompt":"시계를 찾으세요","object":"clock"}],
    "suddenDeath": {"prompt":"교실 칠판을 찾으세요","object":"blackboard"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-happy-family",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "BEGINNER",
    "status": "DRAFT",
    "canonicalAnswer": "family",
    "aliases": ["parents", "home"],
    "meaning": { "prompt": "What is this group of people called?", "options": [{"id":"option_1","label":"Family"},{"id":"option_2","label":"Team"},{"id":"option_3","label":"Crowd"}], "correctOptionId": "option_1" },
    "sceneBrief": "Happy family picnic in a sunny park scene",
    "changes": ["Dad's shirt color","Mom's dress color","Kid's balloon color","Dog removed","Picnic blanket","Food basket color","Hat removed","Kite color","Tree fruit","Bench added"],
    "wordHunts": [{"kind":"NORMAL","prompt":"가족을 찾으세요","object":"family"},{"kind":"NORMAL","prompt":"풍선을 찾으세요","object":"balloon"},{"kind":"SPECIAL","prompt":"개를 찾으세요","object":"dog"}],
    "suddenDeath": {"prompt":"행복한 가족을 찾으세요","object":"happy family"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-curiosity-lab",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "INTERMEDIATE",
    "status": "DRAFT",
    "canonicalAnswer": "curiosity",
    "aliases": ["curious", "wonder"],
    "meaning": { "prompt": "What is the English word for '호기심'?", "options": [{"id":"option_1","label":"Curiosity"},{"id":"option_2","label":"Boredom"},{"id":"option_3","label":"Anxiety"}], "correctOptionId": "option_1" },
    "sceneBrief": "Curiosity science lab with excited young researchers scene",
    "changes": ["Lab coat color","Flask liquid color","Microscope color","Chart removed","Beaker added","Goggles color","Plant color","Robot toy","Book color","Window sticker removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"과학자를 찾으세요","object":"scientist"},{"kind":"NORMAL","prompt":"현미경을 찾으세요","object":"microscope"},{"kind":"SPECIAL","prompt":"시험관을 찾으세요","object":"test tube"}],
    "suddenDeath": {"prompt":"연구실 플라스크를 찾으세요","object":"flask"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-ambiguity-gallery",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "INTERMEDIATE",
    "status": "DRAFT",
    "canonicalAnswer": "ambiguity",
    "aliases": ["ambiguous", "unclear"],
    "meaning": { "prompt": "What is the English word for '모호함'?", "options": [{"id":"option_1","label":"Ambiguity"},{"id":"option_2","label":"Clarity"},{"id":"option_3","label":"Certainty"}], "correctOptionId": "option_1" },
    "sceneBrief": "Art gallery with optical illusion artworks showing ambiguity scene",
    "changes": ["Frame color","Painting content","Visitor outfit","Sculpture removed","Lighting color","Bench color","Exit sign removed","Painting added","Vase color","Curtain color"],
    "wordHunts": [{"kind":"NORMAL","prompt":"관람객을 찾으세요","object":"art visitor"},{"kind":"NORMAL","prompt":"그림 액자를 찾으세요","object":"painting frame"},{"kind":"SPECIAL","prompt":"착시 그림을 찾으세요","object":"optical illusion painting"}],
    "suddenDeath": {"prompt":"갤러리 조각품을 찾으세요","object":"sculpture"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-toy-hospital",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "BEGINNER",
    "status": "DRAFT",
    "canonicalAnswer": "hospital",
    "aliases": ["doctor", "clinic"],
    "meaning": { "prompt": "What is this place called?", "options": [{"id":"option_1","label":"Hospital"},{"id":"option_2","label":"School"},{"id":"option_3","label":"Market"}], "correctOptionId": "option_1" },
    "sceneBrief": "Cute toy hospital with teddy bear patients scene",
    "changes": ["Doctor coat color","Patient bear color","Stethoscope color","Medicine bottle","Bandage color","Thermometer removed","Nurse hat","Bed color","Chart added","Plant removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"의사를 찾으세요","object":"doctor"},{"kind":"NORMAL","prompt":"곰인형 환자를 찾으세요","object":"teddy bear patient"},{"kind":"SPECIAL","prompt":"청진기를 찾으세요","object":"stethoscope"}],
    "suddenDeath": {"prompt":"병원 침대를 찾으세요","object":"hospital bed"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-city-park",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "BEGINNER",
    "status": "DRAFT",
    "canonicalAnswer": "park",
    "aliases": ["garden", "playground"],
    "meaning": { "prompt": "What is this outdoor area called?", "options": [{"id":"option_1","label":"Park"},{"id":"option_2","label":"Forest"},{"id":"option_3","label":"Desert"}], "correctOptionId": "option_1" },
    "sceneBrief": "Colorful city park with children playing scene",
    "changes": ["Slide color","Swing color","Duck removed","Bench color","Kite color","Tree flowers","Dog color","Fountain removed","Balloon added","Lamp color"],
    "wordHunts": [{"kind":"NORMAL","prompt":"미끄럼틀을 찾으세요","object":"slide"},{"kind":"NORMAL","prompt":"그네를 찾으세요","object":"swing"},{"kind":"SPECIAL","prompt":"오리를 찾으세요","object":"duck"}],
    "suddenDeath": {"prompt":"공원 벤치를 찾으세요","object":"park bench"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-yellow-bus",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "BEGINNER",
    "status": "DRAFT",
    "canonicalAnswer": "bus",
    "aliases": ["school bus", "yellow bus"],
    "meaning": { "prompt": "What is this vehicle called?", "options": [{"id":"option_1","label":"Bus"},{"id":"option_2","label":"Train"},{"id":"option_3","label":"Car"}], "correctOptionId": "option_1" },
    "sceneBrief": "Yellow school bus at school gate with children scene",
    "changes": ["Bus window color","Driver hat","Student uniform","Stop sign color","Wheel color","Backpack color","Bird removed","Fence color","Cloud added","Flower removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"노란 스쿨버스를 찾으세요","object":"yellow school bus"},{"kind":"NORMAL","prompt":"버스 기사를 찾으세요","object":"bus driver"},{"kind":"SPECIAL","prompt":"정류장 표지판을 찾으세요","object":"stop sign"}],
    "suddenDeath": {"prompt":"노란 버스를 찾으세요","object":"yellow bus"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-funny-zoo",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "BEGINNER",
    "status": "DRAFT",
    "canonicalAnswer": "zoo",
    "aliases": ["animals", "wildlife park"],
    "meaning": { "prompt": "What is this place called?", "options": [{"id":"option_1","label":"Zoo"},{"id":"option_2","label":"Farm"},{"id":"option_3","label":"Museum"}], "correctOptionId": "option_1" },
    "sceneBrief": "Fun cartoon zoo with funny animal characters scene",
    "changes": ["Giraffe spot color","Elephant hat","Monkey tail","Lion mane color","Zoo gate color","Bird color","Cage color","Sign removed","Ice cream color","Staff uniform"],
    "wordHunts": [{"kind":"NORMAL","prompt":"기린을 찾으세요","object":"giraffe"},{"kind":"NORMAL","prompt":"코끼리를 찾으세요","object":"elephant"},{"kind":"SPECIAL","prompt":"사자를 찾으세요","object":"lion"}],
    "suddenDeath": {"prompt":"동물원 입구를 찾으세요","object":"zoo entrance"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-sweet-bakery",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "BEGINNER",
    "status": "DRAFT",
    "canonicalAnswer": "bakery",
    "aliases": ["bread", "cake shop"],
    "meaning": { "prompt": "What is this shop called?", "options": [{"id":"option_1","label":"Bakery"},{"id":"option_2","label":"Library"},{"id":"option_3","label":"Pharmacy"}], "correctOptionId": "option_1" },
    "sceneBrief": "Sweet colorful bakery shop with pastries and cakes scene",
    "changes": ["Cake frosting color","Bread loaf","Cookie removed","Baker hat color","Display case color","Cupcake topping","Sign color","Flower added","Window color","Tray shape"],
    "wordHunts": [{"kind":"NORMAL","prompt":"제빵사를 찾으세요","object":"baker"},{"kind":"NORMAL","prompt":"케이크를 찾으세요","object":"cake"},{"kind":"SPECIAL","prompt":"진열대를 찾으세요","object":"display case"}],
    "suddenDeath": {"prompt":"달콤한 케이크를 찾으세요","object":"cake"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-summer-beach",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "BEGINNER",
    "status": "DRAFT",
    "canonicalAnswer": "beach",
    "aliases": ["ocean", "seaside"],
    "meaning": { "prompt": "What is this place called?", "options": [{"id":"option_1","label":"Beach"},{"id":"option_2","label":"Mountain"},{"id":"option_3","label":"Desert"}], "correctOptionId": "option_1" },
    "sceneBrief": "Sunny summer beach with swimmers and sand castles scene",
    "changes": ["Umbrella color","Ball color","Surfboard","Seashell removed","Lifeguard tower color","Swimsuit color","Crab added","Bucket color","Wave color","Bird removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"비치 파라솔을 찾으세요","object":"beach umbrella"},{"kind":"NORMAL","prompt":"모래성을 찾으세요","object":"sand castle"},{"kind":"SPECIAL","prompt":"파도를 찾으세요","object":"wave"}],
    "suddenDeath": {"prompt":"해변 파라솔을 찾으세요","object":"beach umbrella"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-space-rocket",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "BEGINNER",
    "status": "DRAFT",
    "canonicalAnswer": "rocket",
    "aliases": ["spacecraft", "spaceship"],
    "meaning": { "prompt": "What is this vehicle called?", "options": [{"id":"option_1","label":"Rocket"},{"id":"option_2","label":"Airplane"},{"id":"option_3","label":"Helicopter"}], "correctOptionId": "option_1" },
    "sceneBrief": "Space rocket launch at night with stars scene",
    "changes": ["Rocket body color","Flame color","Star pattern","Moon shape","Astronaut suit","Launch pad color","Satellite removed","Flag color","Booster removed","Window added"],
    "wordHunts": [{"kind":"NORMAL","prompt":"로켓을 찾으세요","object":"rocket"},{"kind":"NORMAL","prompt":"발사대를 찾으세요","object":"launch pad"},{"kind":"SPECIAL","prompt":"달을 찾으세요","object":"moon"}],
    "suddenDeath": {"prompt":"우주 로켓을 찾으세요","object":"space rocket"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-sustainability-greenhouse",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "INTERMEDIATE",
    "status": "DRAFT",
    "canonicalAnswer": "sustainability",
    "aliases": ["eco", "green"],
    "meaning": { "prompt": "What is the English word for '지속가능성'?", "options": [{"id":"option_1","label":"Sustainability"},{"id":"option_2","label":"Destruction"},{"id":"option_3","label":"Waste"}], "correctOptionId": "option_1" },
    "sceneBrief": "Eco-friendly greenhouse with solar panels and organic plants scene",
    "changes": ["Solar panel color","Plant color","Watering can color","Recycling bin removed","Worker outfit","Butterfly added","Compost bin color","Roof color","Sprinkler removed","Sunlight ray"],
    "wordHunts": [{"kind":"NORMAL","prompt":"온실을 찾으세요","object":"greenhouse"},{"kind":"NORMAL","prompt":"태양광 패널을 찾으세요","object":"solar panel"},{"kind":"SPECIAL","prompt":"재활용 쓰레기통을 찾으세요","object":"recycling bin"}],
    "suddenDeath": {"prompt":"친환경 온실을 찾으세요","object":"eco greenhouse"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-architecture-studio",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "INTERMEDIATE",
    "status": "DRAFT",
    "canonicalAnswer": "architecture",
    "aliases": ["architect", "design"],
    "meaning": { "prompt": "What is the English word for '건축'?", "options": [{"id":"option_1","label":"Architecture"},{"id":"option_2","label":"Agriculture"},{"id":"option_3","label":"Chemistry"}], "correctOptionId": "option_1" },
    "sceneBrief": "Architect studio with building blueprints and models scene",
    "changes": ["Blueprint color","Building model color","Desk lamp","Scale ruler removed","Pencil color","Chair color","Computer screen","Plant added","Hard hat color","Window removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"건축가를 찾으세요","object":"architect"},{"kind":"NORMAL","prompt":"건물 모형을 찾으세요","object":"building model"},{"kind":"SPECIAL","prompt":"청사진을 찾으세요","object":"blueprint"}],
    "suddenDeath": {"prompt":"건축 설계 스튜디오를 찾으세요","object":"architecture studio"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-ecosystem-coral",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "INTERMEDIATE",
    "status": "DRAFT",
    "canonicalAnswer": "ecosystem",
    "aliases": ["coral reef", "marine"],
    "meaning": { "prompt": "What is the English word for '생태계'?", "options": [{"id":"option_1","label":"Ecosystem"},{"id":"option_2","label":"Economy"},{"id":"option_3","label":"Electricity"}], "correctOptionId": "option_1" },
    "sceneBrief": "Colorful coral reef ecosystem with tropical fish scene",
    "changes": ["Coral color","Fish species","Sea turtle removed","Jellyfish color","Anemone added","Diver suit color","Seaweed color","Shell removed","Bubble pattern","Starfish color"],
    "wordHunts": [{"kind":"NORMAL","prompt":"산호초를 찾으세요","object":"coral reef"},{"kind":"NORMAL","prompt":"열대어를 찾으세요","object":"tropical fish"},{"kind":"SPECIAL","prompt":"바다거북을 찾으세요","object":"sea turtle"}],
    "suddenDeath": {"prompt":"바닷속 산호초를 찾으세요","object":"coral reef"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-astronomy-observatory",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "INTERMEDIATE",
    "status": "DRAFT",
    "canonicalAnswer": "observatory",
    "aliases": ["telescope", "stargazing"],
    "meaning": { "prompt": "What is the English word for '천문대'?", "options": [{"id":"option_1","label":"Observatory"},{"id":"option_2","label":"Laboratory"},{"id":"option_3","label":"Dormitory"}], "correctOptionId": "option_1" },
    "sceneBrief": "Night sky astronomy observatory with telescope scene",
    "changes": ["Telescope color","Dome color","Star pattern","Astronomer coat","Planet poster","Eyepiece color","Chart removed","Chair color","Lantern added","Moon position"],
    "wordHunts": [{"kind":"NORMAL","prompt":"천문대를 찾으세요","object":"observatory"},{"kind":"NORMAL","prompt":"망원경을 찾으세요","object":"telescope"},{"kind":"SPECIAL","prompt":"돔 지붕을 찾으세요","object":"dome roof"}],
    "suddenDeath": {"prompt":"천문 관측소를 찾으세요","object":"astronomy observatory"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-archaeology-dig",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "INTERMEDIATE",
    "status": "DRAFT",
    "canonicalAnswer": "archaeology",
    "aliases": ["excavation", "fossil"],
    "meaning": { "prompt": "What is the English word for '고고학'?", "options": [{"id":"option_1","label":"Archaeology"},{"id":"option_2","label":"Architecture"},{"id":"option_3","label":"Accountancy"}], "correctOptionId": "option_1" },
    "sceneBrief": "Archaeological dig site with fossil discovery scene",
    "changes": ["Archaeologist hat","Brush color","Fossil shape","Tent color","Tool removed","Artifact added","Grid rope color","Sign color","Shovel color","Sun hat removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"고고학자를 찾으세요","object":"archaeologist"},{"kind":"NORMAL","prompt":"발굴 현장을 찾으세요","object":"dig site"},{"kind":"SPECIAL","prompt":"화석을 찾으세요","object":"fossil"}],
    "suddenDeath": {"prompt":"고고학 발굴 현장을 찾으세요","object":"archaeology dig"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-symphony-orchestra",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "INTERMEDIATE",
    "status": "DRAFT",
    "canonicalAnswer": "symphony",
    "aliases": ["orchestra", "classical music"],
    "meaning": { "prompt": "What is the English word for '교향곡'?", "options": [{"id":"option_1","label":"Symphony"},{"id":"option_2","label":"Symphony"},{"id":"option_3","label":"Synonym"}], "correctOptionId": "option_1" },
    "sceneBrief": "Grand symphony orchestra performance on concert stage scene",
    "changes": ["Conductor baton color","Violin color","Cello bow","Music stand color","Stage curtain","Horn color","Dress color","Sheet music","Spotlight color","Piano added"],
    "wordHunts": [{"kind":"NORMAL","prompt":"지휘자를 찾으세요","object":"conductor"},{"kind":"NORMAL","prompt":"바이올린을 찾으세요","object":"violin"},{"kind":"SPECIAL","prompt":"첼로를 찾으세요","object":"cello"}],
    "suddenDeath": {"prompt":"교향악단 무대를 찾으세요","object":"orchestra stage"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-hypothesis-lab",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "INTERMEDIATE",
    "status": "DRAFT",
    "canonicalAnswer": "hypothesis",
    "aliases": ["theory", "experiment"],
    "meaning": { "prompt": "What is the English word for '가설'?", "options": [{"id":"option_1","label":"Hypothesis"},{"id":"option_2","label":"Hypnosis"},{"id":"option_3","label":"Hyena"}], "correctOptionId": "option_1" },
    "sceneBrief": "Science lab with hypothesis testing and experiments scene",
    "changes": ["Lab coat color","Chemical color","Whiteboard text","Beaker removed","Safety goggle color","Plant experiment","Notebook added","Timer color","Microscope lens","Chart color"],
    "wordHunts": [{"kind":"NORMAL","prompt":"과학 실험실을 찾으세요","object":"science lab"},{"kind":"NORMAL","prompt":"비커를 찾으세요","object":"beaker"},{"kind":"SPECIAL","prompt":"가설 칠판을 찾으세요","object":"hypothesis whiteboard"}],
    "suddenDeath": {"prompt":"실험실 안전고글을 찾으세요","object":"safety goggles"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-journalism-press",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "INTERMEDIATE",
    "status": "DRAFT",
    "canonicalAnswer": "journalism",
    "aliases": ["reporter", "news"],
    "meaning": { "prompt": "What is the English word for '저널리즘'?", "options": [{"id":"option_1","label":"Journalism"},{"id":"option_2","label":"Geography"},{"id":"option_3","label":"Geometry"}], "correctOptionId": "option_1" },
    "sceneBrief": "Journalism press newsroom with reporters and cameras scene",
    "changes": ["Reporter jacket","Camera color","Microphone color","Desk color","Monitor removed","Notepad added","Map background","Light color","Press badge color","Clock removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"기자를 찾으세요","object":"reporter"},{"kind":"NORMAL","prompt":"방송 카메라를 찾으세요","object":"broadcast camera"},{"kind":"SPECIAL","prompt":"마이크를 찾으세요","object":"microphone"}],
    "suddenDeath": {"prompt":"뉴스룸을 찾으세요","object":"newsroom"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-metaphor-library",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "INTERMEDIATE",
    "status": "DRAFT",
    "canonicalAnswer": "metaphor",
    "aliases": ["simile", "figure of speech"],
    "meaning": { "prompt": "What is the English word for '은유'?", "options": [{"id":"option_1","label":"Metaphor"},{"id":"option_2","label":"Metaphysics"},{"id":"option_3","label":"Metronome"}], "correctOptionId": "option_1" },
    "sceneBrief": "Surreal fantasy library with floating books and metaphors scene",
    "changes": ["Book color","Floating book","Librarian outfit","Shelf color","Reading lamp","Globe removed","Magnifier color","Chair color","Plant added","Staircase color"],
    "wordHunts": [{"kind":"NORMAL","prompt":"도서관을 찾으세요","object":"library"},{"kind":"NORMAL","prompt":"사서를 찾으세요","object":"librarian"},{"kind":"SPECIAL","prompt":"공중에 떠있는 책을 찾으세요","object":"floating book"}],
    "suddenDeath": {"prompt":"책이 떠있는 도서관을 찾으세요","object":"metaphor library"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-paradox-labyrinth",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "paradox",
    "aliases": ["contradiction", "impossible"],
    "meaning": { "prompt": "What is the English word for '역설'?", "options": [{"id":"option_1","label":"Paradox"},{"id":"option_2","label":"Paragraph"},{"id":"option_3","label":"Parallel"}], "correctOptionId": "option_1" },
    "sceneBrief": "Escher-like impossible geometric labyrinth maze scene",
    "changes": ["Staircase direction","Arch color","Figure position","Window removed","Bridge added","Pillar color","Door color","Light source","Shadow direction","Ground pattern"],
    "wordHunts": [{"kind":"NORMAL","prompt":"미로를 찾으세요","object":"labyrinth"},{"kind":"NORMAL","prompt":"계단을 찾으세요","object":"staircase"},{"kind":"SPECIAL","prompt":"역설적인 구조물을 찾으세요","object":"impossible structure"}],
    "suddenDeath": {"prompt":"불가능한 기하학 미로를 찾으세요","object":"impossible labyrinth"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-serendipity-garden",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "serendipity",
    "aliases": ["luck", "chance discovery"],
    "meaning": { "prompt": "What is the English word for '뜻밖의 행운'?", "options": [{"id":"option_1","label":"Serendipity"},{"id":"option_2","label":"Serenity"},{"id":"option_3","label":"Sincerity"}], "correctOptionId": "option_1" },
    "sceneBrief": "Magical four-leaf clover utopia botanical garden scene",
    "changes": ["Clover color","Butterfly color","Fountain color","Flower removed","Bench color","Fairy added","Gate color","Rainbow color","Bird removed","Mushroom added"],
    "wordHunts": [{"kind":"NORMAL","prompt":"네잎클로버를 찾으세요","object":"four-leaf clover"},{"kind":"NORMAL","prompt":"마법의 정원을 찾으세요","object":"magical garden"},{"kind":"SPECIAL","prompt":"나비를 찾으세요","object":"butterfly"}],
    "suddenDeath": {"prompt":"행운의 네잎클로버 정원을 찾으세요","object":"serendipity garden"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-synergy-cradle",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "synergy",
    "aliases": ["collaboration", "teamwork"],
    "meaning": { "prompt": "What is the English word for '시너지'?", "options": [{"id":"option_1","label":"Synergy"},{"id":"option_2","label":"Syntax"},{"id":"option_3","label":"Synonym"}], "correctOptionId": "option_1" },
    "sceneBrief": "High-tech design studio showcasing collaborative synergy scene",
    "changes": ["Screen color","Desk layout","Team member outfit","Robot arm color","Hologram removed","Coffee cup added","Chair color","Window view","Plant removed","Logo color"],
    "wordHunts": [{"kind":"NORMAL","prompt":"시너지 디자인 스튜디오를 찾으세요","object":"design studio"},{"kind":"NORMAL","prompt":"협업하는 팀원들을 찾으세요","object":"team members"},{"kind":"SPECIAL","prompt":"홀로그램 화면을 찾으세요","object":"hologram screen"}],
    "suddenDeath": {"prompt":"첨단 스튜디오를 찾으세요","object":"high-tech studio"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-resilience-garden",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "resilience",
    "aliases": ["recovery", "bouncing back"],
    "meaning": { "prompt": "What is the English word for '회복탄력성'?", "options": [{"id":"option_1","label":"Resilience"},{"id":"option_2","label":"Resistance"},{"id":"option_3","label":"Resolution"}], "correctOptionId": "option_1" },
    "sceneBrief": "Rainbow recovery garden with new growth after rain scene",
    "changes": ["Rainbow color","Flower color","Sprout removed","Rain puddle","Bird added","Butterfly color","Fence color","Cloud shape","Sun position","Gardener outfit"],
    "wordHunts": [{"kind":"NORMAL","prompt":"무지개를 찾으세요","object":"rainbow"},{"kind":"NORMAL","prompt":"새싹을 찾으세요","object":"sprout"},{"kind":"SPECIAL","prompt":"비 온 뒤 정원사를 찾으세요","object":"gardener after rain"}],
    "suddenDeath": {"prompt":"회복의 무지개 정원을 찾으세요","object":"resilience garden"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-nostalgia-attic",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "nostalgia",
    "aliases": ["memory", "longing"],
    "meaning": { "prompt": "What is the English word for '향수(그리움)'?", "options": [{"id":"option_1","label":"Nostalgia"},{"id":"option_2","label":"Navigation"},{"id":"option_3","label":"Narration"}], "correctOptionId": "option_1" },
    "sceneBrief": "Cozy attic filled with vintage memories and old toys scene",
    "changes": ["Toy color","Photo frame","Trunk color","Music box","Lamp color","Stuffed animal removed","Letter box color","Window curtain","Clock style","Poster added"],
    "wordHunts": [{"kind":"NORMAL","prompt":"다락방을 찾으세요","object":"attic"},{"kind":"NORMAL","prompt":"오래된 장난감을 찾으세요","object":"old toys"},{"kind":"SPECIAL","prompt":"사진 액자를 찾으세요","object":"photo frame"}],
    "suddenDeath": {"prompt":"추억이 담긴 다락방을 찾으세요","object":"nostalgia attic"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-epiphany-lighthouse",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "epiphany",
    "aliases": ["revelation", "sudden insight"],
    "meaning": { "prompt": "What is the English word for '갑작스러운 깨달음'?", "options": [{"id":"option_1","label":"Epiphany"},{"id":"option_2","label":"Epidemic"},{"id":"option_3","label":"Epilogue"}], "correctOptionId": "option_1" },
    "sceneBrief": "Coastal lighthouse with flash of brilliant insight at night scene",
    "changes": ["Lighthouse beam color","Keeper outfit","Lantern color","Boat removed","Rock color","Wave height","Star pattern","Window color","Bell removed","Door color"],
    "wordHunts": [{"kind":"NORMAL","prompt":"등대를 찾으세요","object":"lighthouse"},{"kind":"NORMAL","prompt":"등대지기를 찾으세요","object":"lighthouse keeper"},{"kind":"SPECIAL","prompt":"등대 불빛을 찾으세요","object":"lighthouse beam"}],
    "suddenDeath": {"prompt":"해안 등대를 찾으세요","object":"coastal lighthouse"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-equilibrium-cliff",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "equilibrium",
    "aliases": ["balance", "harmony"],
    "meaning": { "prompt": "What is the English word for '평형'?", "options": [{"id":"option_1","label":"Equilibrium"},{"id":"option_2","label":"Equipment"},{"id":"option_3","label":"Equivalent"}], "correctOptionId": "option_1" },
    "sceneBrief": "Perfectly balanced zen cliff with harmony and equilibrium scene",
    "changes": ["Stone color","Balance scale","Cloud position","Tree shape","Monk outfit","Waterfall color","Bird removed","Rock stack","Flower color","Rope bridge"],
    "wordHunts": [{"kind":"NORMAL","prompt":"균형잡힌 절벽을 찾으세요","object":"balanced cliff"},{"kind":"NORMAL","prompt":"저울을 찾으세요","object":"balance scale"},{"kind":"SPECIAL","prompt":"명상하는 인물을 찾으세요","object":"meditating figure"}],
    "suddenDeath": {"prompt":"균형의 절벽을 찾으세요","object":"equilibrium cliff"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-transmutation-alchemist",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "transmutation",
    "aliases": ["alchemy", "transformation"],
    "meaning": { "prompt": "What is the English word for '연금술적 변형'?", "options": [{"id":"option_1","label":"Transmutation"},{"id":"option_2","label":"Transportation"},{"id":"option_3","label":"Transaction"}], "correctOptionId": "option_1" },
    "sceneBrief": "Mystical alchemist laboratory transforming elements scene",
    "changes": ["Flask color","Potion glow","Element symbol","Alchemist robe","Book color","Cauldron removed","Gem added","Smoke color","Rune pattern","Table color"],
    "wordHunts": [{"kind":"NORMAL","prompt":"연금술사를 찾으세요","object":"alchemist"},{"kind":"NORMAL","prompt":"마법의 플라스크를 찾으세요","object":"alchemical flask"},{"kind":"SPECIAL","prompt":"원소 변환 부호를 찾으세요","object":"element symbol"}],
    "suddenDeath": {"prompt":"연금술 실험실을 찾으세요","object":"alchemy lab"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-transcendence-galaxy",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "transcendence",
    "aliases": ["surpassing", "beyond limits"],
    "meaning": { "prompt": "What is the English word for '초월'?", "options": [{"id":"option_1","label":"Transcendence"},{"id":"option_2","label":"Transparency"},{"id":"option_3","label":"Translation"}], "correctOptionId": "option_1" },
    "sceneBrief": "Cosmic galaxy transcendence beyond space and time scene",
    "changes": ["Galaxy color","Star cluster","Planet removed","Astronaut suit","Nebula color","Black hole position","Comet added","Light ray color","Space station removed","Constellation pattern"],
    "wordHunts": [{"kind":"NORMAL","prompt":"은하를 찾으세요","object":"galaxy"},{"kind":"NORMAL","prompt":"우주 비행사를 찾으세요","object":"astronaut"},{"kind":"SPECIAL","prompt":"블랙홀을 찾으세요","object":"black hole"}],
    "suddenDeath": {"prompt":"초월적 우주를 찾으세요","object":"transcendence galaxy"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-phenomenon-lab",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "phenomenon",
    "aliases": ["natural phenomenon", "wonder"],
    "meaning": { "prompt": "What is the English word for '현상'?", "options": [{"id":"option_1","label":"Phenomenon"},{"id":"option_2","label":"Philosophy"},{"id":"option_3","label":"Photography"}], "correctOptionId": "option_1" },
    "sceneBrief": "Natural phenomenon science observation lab with lightning and aurora scene",
    "changes": ["Aurora color","Lightning bolt","Lab coat color","Monitor display","Crystal color","Sensor removed","Cloud pattern","Researcher hat","Antenna color","Data chart"],
    "wordHunts": [{"kind":"NORMAL","prompt":"자연 현상 연구자를 찾으세요","object":"phenomenon researcher"},{"kind":"NORMAL","prompt":"오로라를 찾으세요","object":"aurora"},{"kind":"SPECIAL","prompt":"번개를 찾으세요","object":"lightning"}],
    "suddenDeath": {"prompt":"자연 현상 관측소를 찾으세요","object":"phenomenon lab"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-juxtaposition-market",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "juxtaposition",
    "aliases": ["contrast", "side by side"],
    "meaning": { "prompt": "What is the English word for '병치'?", "options": [{"id":"option_1","label":"Juxtaposition"},{"id":"option_2","label":"Justification"},{"id":"option_3","label":"Jurisdiction"}], "correctOptionId": "option_1" },
    "sceneBrief": "Steampunk vs Cyberpunk contrasting market stalls juxtaposition scene",
    "changes": ["Stall color","Technology item","Vendor outfit","Sign color","Gear removed","Neon light added","Market item","Clock style","Robot vendor","Fountain removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"스팀펑크 가판대를 찾으세요","object":"steampunk stall"},{"kind":"NORMAL","prompt":"사이버펑크 가판대를 찾으세요","object":"cyberpunk stall"},{"kind":"SPECIAL","prompt":"대조적 마켓 입구를 찾으세요","object":"juxtaposition market"}],
    "suddenDeath": {"prompt":"대조적인 마켓 씬을 찾으세요","object":"juxtaposition market"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-kaleidoscope-chamber",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "kaleidoscope",
    "aliases": ["prism", "colorful pattern"],
    "meaning": { "prompt": "What is the English word for '만화경'?", "options": [{"id":"option_1","label":"Kaleidoscope"},{"id":"option_2","label":"Kangaroo"},{"id":"option_3","label":"Karate"}], "correctOptionId": "option_1" },
    "sceneBrief": "Stained glass prism kaleidoscope chamber with rainbow reflections scene",
    "changes": ["Glass panel color","Prism shape","Light ray color","Mirror removed","Crystal added","Chamber door color","Reflection pattern","Artist outfit","Beam color","Glass removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"만화경 방을 찾으세요","object":"kaleidoscope chamber"},{"kind":"NORMAL","prompt":"스테인드 글라스를 찾으세요","object":"stained glass"},{"kind":"SPECIAL","prompt":"무지개 반사빛을 찾으세요","object":"rainbow reflection"}],
    "suddenDeath": {"prompt":"오색찬란 만화경 방을 찾으세요","object":"kaleidoscope chamber"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-metamorphosis-cocoon",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "metamorphosis",
    "aliases": ["transformation", "butterfly"],
    "meaning": { "prompt": "What is the English word for '변태(탈바꿈)'?", "options": [{"id":"option_1","label":"Metamorphosis"},{"id":"option_2","label":"Metabolism"},{"id":"option_3","label":"Meteorology"}], "correctOptionId": "option_1" },
    "sceneBrief": "Butterfly chrysalis conservatory with metamorphosis cocoons scene",
    "changes": ["Cocoon color","Butterfly color","Biologist outfit","Plant color","Light color","Chrysalis removed","Leaf pattern","Magnifier color","Jar added","Window frame"],
    "wordHunts": [{"kind":"NORMAL","prompt":"나비 변태 온실을 찾으세요","object":"metamorphosis conservatory"},{"kind":"NORMAL","prompt":"번데기 고치를 찾으세요","object":"chrysalis cocoon"},{"kind":"SPECIAL","prompt":"나비를 찾으세요","object":"butterfly"}],
    "suddenDeath": {"prompt":"변태 과정의 나비를 찾으세요","object":"metamorphosis butterfly"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-panoramic-observatory",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "panoramic",
    "aliases": ["panorama", "wide view"],
    "meaning": { "prompt": "What is the English word for '파노라마의'?", "options": [{"id":"option_1","label":"Panoramic"},{"id":"option_2","label":"Pandemic"},{"id":"option_3","label":"Paranoid"}], "correctOptionId": "option_1" },
    "sceneBrief": "Mountain summit 360 degree panoramic observatory at sunset scene",
    "changes": ["Jacket color","Telescope color","Binoculars removed","Railing color","Hat color","Map color","Eagle removed","Compass added","Anemometer removed","Backpack color"],
    "wordHunts": [{"kind":"NORMAL","prompt":"파노라마 관측대를 찾으세요","object":"panoramic observatory"},{"kind":"NORMAL","prompt":"지리학자를 찾으세요","object":"geographer"},{"kind":"SPECIAL","prompt":"설산 전경을 찾으세요","object":"mountain panorama"}],
    "suddenDeath": {"prompt":"설산 정상 파노라마 관측대를 찾으세요","object":"panoramic observatory"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-cataclysm-volcano",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "cataclysm",
    "aliases": ["disaster", "eruption"],
    "meaning": { "prompt": "What is the English word for '대재앙'?", "options": [{"id":"option_1","label":"Cataclysm"},{"id":"option_2","label":"Catalyst"},{"id":"option_3","label":"Category"}], "correctOptionId": "option_1" },
    "sceneBrief": "Volcanic eruption cataclysm geothermal research station scene",
    "changes": ["Helmet visor color","Seismic monitor color","Drill probe color","Obsidian crystal removed","Railing color","Shoulder badge color","Sensor removed","Camera color","Lava container added","Siren removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"화산학자를 찾으세요","object":"volcanologist"},{"kind":"NORMAL","prompt":"관측 데크를 찾으세요","object":"observation deck"},{"kind":"SPECIAL","prompt":"지진 모니터를 찾으세요","object":"seismic monitor"}],
    "suddenDeath": {"prompt":"화산 관측소의 화산학자를 찾으세요","object":"volcanologist on deck"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-quintessence-alchemy",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "quintessence",
    "aliases": ["pure essence", "fifth element"],
    "meaning": { "prompt": "What is the English word for '정수(제5원소)'?", "options": [{"id":"option_1","label":"Quintessence"},{"id":"option_2","label":"Quarantined"},{"id":"option_3","label":"Questionnaire"}], "correctOptionId": "option_1" },
    "sceneBrief": "Celestial alchemy lab with Fifth Element crystal orb quintessence scene",
    "changes": ["Robe trim color","Crystal orb glow","Astrolabe color","Ether crystal removed","Globe stand color","Flask liquid color","Star marker removed","Hat band color","Ether vial added","Sun pendant removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"연금술사를 찾으세요","object":"alchemist"},{"kind":"NORMAL","prompt":"제5원소 구체를 찾으세요","object":"Fifth Element orb"},{"kind":"SPECIAL","prompt":"황동 아스트롤라베를 찾으세요","object":"brass astrolabe"}],
    "suddenDeath": {"prompt":"빛나는 제5원소 구체를 찾으세요","object":"glowing Fifth Element orb"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-chrysanthemum-greenhouse",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "chrysanthemum",
    "aliases": ["golden flower", "greenhouse"],
    "meaning": { "prompt": "What is the English word for '국화'?", "options": [{"id":"option_1","label":"Chrysanthemum"},{"id":"option_2","label":"Carnation"},{"id":"option_3","label":"Camellia"}], "correctOptionId": "option_1" },
    "sceneBrief": "Royal Victorian greenhouse with golden chrysanthemum blooms scene",
    "changes": ["Apron color","Chrysanthemum color","Watering can color","Hanging basket removed","Porcelain pot color","Fountain petal color","Pruning shears removed","Hair ribbon color","Clay flowerpot added","Thermometer removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"플로리스트를 찾으세요","object":"master florist"},{"kind":"NORMAL","prompt":"황금 국화 화병을 찾으세요","object":"golden chrysanthemum vase"},{"kind":"SPECIAL","prompt":"대리석 분수대를 찾으세요","object":"marble fountain"}],
    "suddenDeath": {"prompt":"황금 국화 꽃을 찾으세요","object":"golden chrysanthemum flowers"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-archipelago-island",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "archipelago",
    "aliases": ["island chain", "lagoon"],
    "meaning": { "prompt": "What is the English word for '다도해'?", "options": [{"id":"option_1","label":"Archipelago"},{"id":"option_2","label":"Architecture"},{"id":"option_3","label":"Archaeology"}], "correctOptionId": "option_1" },
    "sceneBrief": "Tropical volcanic island chain archipelago from watchtower scene",
    "changes": ["Geographer shirt color","Telescope color","Canoe sail color","Sea hawk removed","Railing color","Sun hat color","Barrel removed","Map container color","Compass added","Lantern removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"해양 지리학자를 찾으세요","object":"marine geographer"},{"kind":"NORMAL","prompt":"나무 망루를 찾으세요","object":"wooden watchtower"},{"kind":"SPECIAL","prompt":"열대 군도를 찾으세요","object":"tropical island chain"}],
    "suddenDeath": {"prompt":"망원경을 찾으세요","object":"spyglass telescope on tripod"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-constellation-astronomy",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "constellation",
    "aliases": ["star chart", "zodiac"],
    "meaning": { "prompt": "What is the English word for '별자리'?", "options": [{"id":"option_1","label":"Constellation"},{"id":"option_2","label":"Conservation"},{"id":"option_3","label":"Constitution"}], "correctOptionId": "option_1" },
    "sceneBrief": "Night sky constellation observatory dome with telescope scene",
    "changes": ["Sweater color","Telescope barrel color","Globe stand color","Oil lamp removed","Star map case color","Hair clip color","Astrolabe removed","Frame trim color","Star globe added","Thermometer removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"천문학자를 찾으세요","object":"astronomer"},{"kind":"NORMAL","prompt":"거대 망원경을 찾으세요","object":"refractor telescope"},{"kind":"SPECIAL","prompt":"별자리 선을 찾으세요","object":"glowing constellation lines"}],
    "suddenDeath": {"prompt":"천문대 돔의 망원경을 찾으세요","object":"refractor telescope"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-synchronicity-clock",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "synchronicity",
    "aliases": ["clockwork", "pendulum"],
    "meaning": { "prompt": "What is the English word for '동시성'?", "options": [{"id":"option_1","label":"Synchronicity"},{"id":"option_2","label":"Symmetry"},{"id":"option_3","label":"Syndicate"}], "correctOptionId": "option_1" },
    "sceneBrief": "Clock tower pendulum chamber with twin pendulums in synchronicity scene",
    "changes": ["Vest color","Pendulum disc color","Clock numerals color","Oil lamp removed","Pocket watch chain color","Valve handle color","Gear sprocket removed","Loupe band color","Oil bottle added","Pressure gauge removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"시계공을 찾으세요","object":"horologist"},{"kind":"NORMAL","prompt":"거대 진자를 찾으세요","object":"giant pendulum"},{"kind":"SPECIAL","prompt":"거대 기어 구조를 찾으세요","object":"interlocking gears"}],
    "suddenDeath": {"prompt":"동시에 움직이는 진자를 찾으세요","object":"twin swinging pendulums"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-camaraderie-campfire",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "camaraderie",
    "aliases": ["friendship", "fellowship"],
    "meaning": { "prompt": "What is the English word for '동료애'?", "options": [{"id":"option_1","label":"Camaraderie"},{"id":"option_2","label":"Chivalry"},{"id":"option_3","label":"Choreography"}], "correctOptionId": "option_1" },
    "sceneBrief": "Forest campfire gathering with guitar and friends camaraderie scene",
    "changes": ["Sweater color","Tent color","Cocoa mug color","Lantern removed","Neckerchief color","Marshmallow bag color","Roasting stick removed","Guitar color","Enamel mug added","Flashlight removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"통기타 연주자를 찾으세요","object":"guitar player"},{"kind":"NORMAL","prompt":"모닥불을 찾으세요","object":"campfire"},{"kind":"SPECIAL","prompt":"숲속 텐트를 찾으세요","object":"camping tent"}],
    "suddenDeath": {"prompt":"모닥불 가의 통기타를 찾으세요","object":"acoustic guitar"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-solitude-sanctuary",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "solitude",
    "aliases": ["peace", "sanctuary"],
    "meaning": { "prompt": "What is the English word for '고독'?", "options": [{"id":"option_1","label":"Solitude"},{"id":"option_2","label":"Solidarity"},{"id":"option_3","label":"Solicitation"}], "correctOptionId": "option_1" },
    "sceneBrief": "Alpine mountain sanctuary with meditating monk in solitude scene",
    "changes": ["Monk robe color","Bronze gong color","Cushion mat color","Wind chime removed","Stone lantern roof color","Lotus flower color","Singing bowl removed","Gong mallet color","Tea cup added","Wall scroll removed"],
    "wordHunts": [{"kind":"NORMAL","prompt":"명상하는 수도승을 찾으세요","object":"meditating monk"},{"kind":"NORMAL","prompt":"청동 징을 찾으세요","object":"bronze gong"},{"kind":"SPECIAL","prompt":"연꽃을 찾으세요","object":"floating lotus flower"}],
    "suddenDeath": {"prompt":"설산 정자의 수도승을 찾으세요","object":"meditating monk"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  },
  {
    "key": "en-serenity-lake",
    "category": "ENGLISH",
    "language": "en",
    "difficulty": "ADVANCED",
    "status": "DRAFT",
    "canonicalAnswer": "serenity",
    "aliases": ["peace", "lake", "canoe"],
    "meaning": { "prompt": "What is the English word for '평정' or '고요한 평화'?", "options": [{"id":"option_1","label":"Serenity"},{"id":"option_2","label":"Severity"},{"id":"option_3","label":"Security"}], "correctOptionId": "option_1" },
    "sceneBrief": "고급 영단어 Serenity 학습을 위한 잔잔하고 평화로운 안개 낀 호수에서 카누를 타고 지도를 탐색하는 씬",
    "changes": ["지리학자의 자켓 색상을 주황색에서 에메랄드 그린으로 변경","블루 왜가리의 다리와 부리 색상을 오렌지에서 실버로 변경","나무 데크 선착장 위에 놓여있던 황동 랜턴 케이스 색상을 황동 골드에서 크림슨 레드로 변경","카누 보트 왼쪽 물 위에 떠있던 수련 꽃 1개 제거","지리학자가 쥔 노의 패들 깃 색상을 갈색에서 터콰이즈 블루로 변경","지리학자의 챙 모자 색상을 베이지에서 밝은 노란색으로 변경","카누 보트 시트 위에 놓여있던 작은 쌍안경 망원경 1개 제거","데크 위 가죽 지도 보관함 케이스 색상을 브라운 레더에서 로얄 블루로 변경","데크 선착장 랜턴 옆에 작게 놓인 금속 머그잔 1개 추가","데크 기둥 벽면 포스트에 걸려있던 가죽 꼬리표 장식 1개 제거"],
    "wordHunts": [{"kind":"NORMAL","prompt":"고요한 호수 위에서 카누를 타며 지도를 보는 지리학자를 찾으세요","object":"geographer in wooden canoe"},{"kind":"NORMAL","prompt":"물속 바위 위에 외롭게 서있는 왜가리를 찾으세요","object":"blue heron standing on rock"},{"kind":"SPECIAL","prompt":"호수 물 위에 둥둥 떠있는 수련 꽃들을 찾으세요","object":"water lilies floating on lake"}],
    "suddenDeath": {"prompt":"호수 위에 떠있는 나무 카누를 찾으세요","object":"wooden canoe"},
    "promptProvenance": {"provider":"OPENAI","model":"IMAGEGEN","basePromptSha256":null,"editPromptSha256":null,"generatedAt":null}
  }
];

let added = 0;
for (const entry of newEntries) {
  if (!existingKeys.has(entry.key)) {
    catalog.entries.push(entry);
    existingKeys.add(entry.key);
    added++;
    console.log('Added:', entry.key);
  } else {
    console.log('Already exists:', entry.key);
  }
}

fs.writeFileSync(catalogPath, JSON.stringify(catalog, null, 2));
console.log(`\nTotal added: ${added}. Catalog now has ${catalog.entries.length} entries.`);
