import{mkdtemp,rm,writeFile}from'node:fs/promises';import{tmpdir}from'node:os';import{resolve}from'node:path';import sharp from'sharp';import{afterEach,describe,expect,it}from'vitest';import{evaluateVisualDelta,type DeltaRegion}from'./visual-delta.js';
const dirs:string[]=[];afterEach(async()=>Promise.all(dirs.splice(0).map(x=>rm(x,{recursive:true,force:true}))));
const regions:Array<DeltaRegion>=Array.from({length:10},(_,i)=>({id:`difference_${i+1}`,cx:.1+(i%5)*.2,cy:.2+Math.floor(i/5)*.5,r:.055}));
async function pair(options:{wrongSize?:boolean;leak?:boolean}={}){const dir=await mkdtemp(resolve(tmpdir(),'learning-delta-'));dirs.push(dir);const width=100,height=100,ap=resolve(dir,'a.png'),bp=resolve(dir,'b.png');await writeFile(ap,await sharp({create:{width,height,channels:4,background:'#ffffff'}}).png().toBuffer());if(options.wrongSize){await writeFile(bp,await sharp({create:{width:101,height,channels:4,background:'#ffffff'}}).png().toBuffer());return{ap,bp};}const declared=regions.map(r=>`<rect x="${Math.round(r.cx*width)-2}" y="${Math.round(r.cy*height)-2}" width="5" height="5" fill="#1450b4"/>`).join(''),leak=options.leak?'<rect x="42" y="42" width="16" height="16" fill="#000000"/>':'',svg=Buffer.from(`<svg width="100" height="100" xmlns="http://www.w3.org/2000/svg"><rect width="100" height="100" fill="#ffffff"/>${declared}${leak}</svg>`);await writeFile(bp,await sharp(svg).png().toBuffer());return{ap,bp};}
describe('learning visual delta',()=>{
 it('requires material change in all ten declared regions',async()=>{const{ap,bp}=await pair();await expect(evaluateVisualDelta(ap,bp,regions,{pixelThreshold:24,minChangedPixelsPerRegion:16,maxOutsideChangedRatio:.005})).resolves.toMatchObject({dimensionsMatch:true,changedRegions:10,missingRegions:[],outsidePolicy:'PASS'});});
 it('rejects dimension drift',async()=>{const{ap,bp}=await pair({wrongSize:true});await expect(evaluateVisualDelta(ap,bp,regions,{pixelThreshold:24,minChangedPixelsPerRegion:16,maxOutsideChangedRatio:.005})).rejects.toThrow('PAIR_DIMENSION_MISMATCH');});
 it('rejects undeclared visual changes',async()=>{const{ap,bp}=await pair({leak:true});await expect(evaluateVisualDelta(ap,bp,regions,{pixelThreshold:24,minChangedPixelsPerRegion:16,maxOutsideChangedRatio:.005})).rejects.toThrow('UNDECLARED_VISUAL_DELTA');});
});
