begin;
select plan(24);
select has_table('private','admin_publish_receipts','durable admin publish receipts exist');
select has_table('private','admin_sessions','verified server sessions exist');
select has_table('private','admin_publish_audit','safe admin audit exists');
select has_function('private','claim_admin_publish_v1',array['text','text','text','text','integer'],'durable claim boundary exists');
select function_privs_are('private','claim_admin_publish_v1',array['text','text','text','text','integer'],'admin_publish_role',array['EXECUTE'],'only admin publish role claims publish');
select has_function('private','complete_admin_publish_v1',array['text','text','text','bigint','jsonb','jsonb','jsonb','text','text','text','text','text','text'],'fenced completion boundary exists');
select function_privs_are('private','complete_admin_publish_v1',array['text','text','text','bigint','jsonb','jsonb','jsonb','text','text','text','text','text','text'],'admin_publish_role',array['EXECUTE'],'only admin publish role completes publish');
select has_function('private','resolve_admin_publish_v1',array['text','text'],'ambiguous outcome resolver exists');
select function_privs_are('private','resolve_admin_publish_v1',array['text','text'],'admin_publish_role',array['EXECUTE'],'only admin publish role resolves publish');
select col_is_unique('private','admin_publish_receipts','attestation_hash','attestations are single-use across keys');
select col_not_null('private','admin_publish_receipts','fence','receipt fencing is mandatory');
select policies_are('private','admin_publish_receipts',array[]::text[],'receipt authority is never exposed through RLS');
select has_function('private','lookup_admin_session_v1',array['text'],'session lookup wrapper exists');
select has_function('private','create_admin_session_v1',array['text','text','uuid'],'session bootstrap wrapper exists');
select has_function('private','write_admin_publish_audit_v1',array['text','text','text','text','text','text'],'safe audit wrapper exists');
select function_privs_are('private','write_admin_publish_audit_v1',array['text','text','text','text','text','text'],'admin_publish_role',array['EXECUTE'],'admin publish role can only invoke validated audit wrapper');
select ok(not has_table_privilege('deployment_role','private.admin_publish_audit','INSERT'),'deployment role cannot insert audit rows directly');
select ok((select proowner=(select oid from pg_roles where rolname='game_security_owner') and proconfig=array['search_path=pg_catalog'] from pg_proc where oid='private.write_admin_publish_audit_v1(text,text,text,text,text,text)'::regprocedure),'audit wrapper has NOLOGIN owner and pg_catalog-only path');
select ok((select not rolcanlogin and not rolinherit from pg_roles where rolname='game_security_owner'),'admin definer owner is NOLOGIN NOINHERIT');
select ok((select proowner=(select oid from pg_roles where rolname='game_security_owner') and proconfig=array['search_path=pg_catalog'] from pg_proc where oid='private.lookup_admin_session_v1(text)'::regprocedure),'lookup is owned and pins pg_catalog only');
select ok((select proowner=(select oid from pg_roles where rolname='game_security_owner') and proconfig=array['search_path=pg_catalog'] from pg_proc where oid='private.create_admin_session_v1(text,text,uuid)'::regprocedure),'bootstrap is owned and pins pg_catalog only');
select ok((select proowner=(select oid from pg_roles where rolname='game_security_owner') and proconfig=array['search_path=pg_catalog'] from pg_proc where oid='private.claim_admin_publish_v1(text,text,text,text,integer)'::regprocedure),'claim is owned and pins pg_catalog only');
select ok((select proowner=(select oid from pg_roles where rolname='game_security_owner') and proconfig=array['search_path=pg_catalog'] from pg_proc where oid='private.complete_admin_publish_v1(text,text,text,bigint,jsonb,jsonb,jsonb,text,text,text,text,text,text)'::regprocedure),'complete is owned and pins pg_catalog only');
select ok((select proowner=(select oid from pg_roles where rolname='game_security_owner') and proconfig=array['search_path=pg_catalog'] from pg_proc where oid='private.resolve_admin_publish_v1(text,text)'::regprocedure),'resolve is owned and pins pg_catalog only');
select * from finish();
rollback;
