begin;
create extension if not exists pgtap with schema extensions;
select plan(20);
select has_table('private','economy_policy_revisions','economy policy revisions are private');
select has_table('private','pet_catalog_revisions','catalog revisions are private');
select has_table('private','pet_catalog_revision_entries','catalog entries are private');
select has_table('private','economy_subjects','random subject mapping exists');
select has_table('private','idempotency_requests','subject-scoped receipts exist');
select has_table('private','reward_ledger','reward ledger exists');
select has_table('private','gacha_history','draw history exists');
select has_table('private','fusion_history','fusion history exists');
select has_table('private','gacha_pity_state','pity state exists');
select has_table('private','outbox_events','transactional outbox exists');
select has_function('private','publish_economy_bundle_v1','approved bundle publish function exists');
select has_function('private','award_match_reward_v1','reward command exists');
select has_function('private','draw_pet_v1','draw command exists');
select has_function('private','fuse_pets_v1','fusion command exists');
select has_function('private','select_pet_v1','select command exists');
select has_function('private','set_pet_lock_v1','lock command exists');
select ok(has_function_privilege('deployment_role','private.publish_economy_bundle_v1(jsonb,jsonb)','EXECUTE') and not has_function_privilege('app_server','private.publish_economy_bundle_v1(jsonb,jsonb)','EXECUTE'),'only deployment role publishes');
select ok(has_function_privilege('app_server','private.draw_pet_v1(uuid,uuid,text,text,text,text,text)','EXECUTE') and not has_function_privilege('authenticated','private.draw_pet_v1(uuid,uuid,text,text,text,text,text)','EXECUTE'),'only app server draws');
select isnt(has_schema_privilege('authenticated','private','USAGE'),true,'authenticated cannot use private schema');
select isnt(has_table_privilege('app_server','private.economy_subjects','INSERT'),true,'app_server cannot mutate economy tables directly');
select * from finish();
rollback;
