import { canonicalJsonSha256 } from '../../contracts/src/canonical-json.js';
import type { CreateMatchInitialStateInput, MatchInitialStateV1 } from '../../contracts/src/match.js';
import type { RulesetV1 } from '../../contracts/src/rules.js';

export function createMatchInitialState(input:CreateMatchInitialStateInput,rules:RulesetV1) {
 if(input.rulesetHash!==canonicalJsonSha256(rules))throw Error('rulesetHash mismatch');
 if(input.playerIds[0]===input.playerIds[1])throw Error('players must differ');
 if(input.privateSolution.contentRevisionId!==input.contentManifest.contentRevisionId||input.privateSolution.privateSolutionHash!==input.contentManifest.privateSolutionHash)throw Error('content mismatch');
 const schedule=input.randomSchedule.wordHunts;
 if(new Set(schedule.map(x=>x.missionId)).size!==3||schedule.some((x,i)=>x.kind!==rules.wordHuntSchedule[i].kind||x.endsAfterMs-x.startsAfterMs!==rules.time.wordHuntMs))throw Error('invalid schedule');
 if(new Set(input.randomSchedule.hintRevealOrder).size!==input.privateSolution.finalChallenge.hintUnits.length||input.randomSchedule.hintRevealOrder.some(x=>x<0||x>=input.privateSolution.finalChallenge.hintUnits.length))throw Error('invalid hint order');
 const player=(playerId:string)=>({playerId,assetLoadStatus:'PENDING' as const,assetFailure:null,assetAttestation:null,score:0,wrongFinalAttempts:0,hintCredits:0,revealedHintIndexes:[],publicPattern:null,finalAnswerStatus:'NOT_SUBMITTED' as const,meaningCorrect:null,answerUntilMs:null,tapRateWindow:{windowIndex:null,acceptedCount:0}});
 const state:MatchInitialStateV1={matchId:input.matchId,engineVersion:input.engineVersion,rulesetVersion:'1.0.0',rulesetHash:input.rulesetHash,contentRevisionId:input.contentManifest.contentRevisionId,contentHash:input.contentManifest.publicContentHash,assetPolicyVersion:'1.0.0',createdAtMs:input.createdAtMs,assetLoadDeadlineMs:input.createdAtMs+rules.time.assetLoadMs,expectedAssets:input.contentManifest.expectedAssets,phase:'WAITING_FOR_ASSETS',phaseEndsAtMs:null,startedAtMs:null,gameplayClosesAtMs:null,settlementCapAtMs:null,stateRevision:0,nextEventSeq:1,players:[player(input.playerIds[0]),player(input.playerIds[1])],connections:[{playerId:input.playerIds[0],status:'CONNECTED',disconnectEpoch:0,disconnectedAtMs:null,forfeitAtMs:null},{playerId:input.playerIds[1],status:'CONNECTED',disconnectEpoch:0,disconnectedAtMs:null,forfeitAtMs:null}],objectives:[...input.privateSolution.differences.map(x=>({objectiveId:x.objectiveId,kind:'DIFFERENCE' as const,ownerPlayerId:null})),...input.privateSolution.wordHunts.map(x=>({objectiveId:x.missionId,kind:'WORD_HUNT' as const,ownerPlayerId:null}))],activeMission:null,finalChallenge:{unlockedAtMs:null,unlockSource:null},meaningQuizzes:[],suddenDeath:null,randomSchedule:input.randomSchedule,privateSolution:input.privateSolution,winnerPlayerId:null,endReason:null};
 return {state,timerIntents:[{kind:'SCHEDULE' as const,timerId:`${input.matchId}:timer:ASSET_LOAD_TIMEOUT:asset`,dueAtMs:state.assetLoadDeadlineMs,payload:{type:'ASSET_LOAD_TIMEOUT' as const}}] as const};
}
