import { canonicalJsonSha256 } from '../../contracts/src/canonical-json.js';
import { normalizeFinalAnswer } from '../../contracts/src/answer-normalization.js';
import type { CreateMatchInitialStateInput, MatchCommand, MatchEvent, MatchInitialStateV1, MatchStateV1, ReduceResult, TimerIntent } from '../../contracts/src/match.js';
import type { RulesetV1 } from '../../contracts/src/rules.js';

export function createMatchInitialState(input:CreateMatchInitialStateInput,rules:RulesetV1) {
 if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(input.matchId)||input.playerIds.some(x=>!/^[\x21-\x7e]{1,128}$/.test(x)))throw Error('invalid match or player id');
 if(input.rulesetHash!==canonicalJsonSha256(rules))throw Error('rulesetHash mismatch');
 if(input.playerIds[0]===input.playerIds[1])throw Error('players must differ');
 if(input.privateSolution.contentRevisionId!==input.contentManifest.contentRevisionId||input.privateSolution.privateSolutionHash!==input.contentManifest.privateSolutionHash)throw Error('content mismatch');
 if(input.contentManifest.expectedAssets[0].side!=='A'||input.contentManifest.expectedAssets[1].side!=='B'||input.contentManifest.expectedAssets.some(a=>!/^https:\/\/[^\s]+$/.test(a.url)||!/^[a-f0-9]{64}$/.test(a.sha256)||!Number.isSafeInteger(a.encodedBytes)||a.encodedBytes<1||!Number.isSafeInteger(a.width)||a.width<1||!Number.isSafeInteger(a.height)||a.height<1))throw Error('invalid asset manifest');
 const schedule=input.randomSchedule.wordHunts;
 const missionIds=new Set(input.privateSolution.wordHunts.map(x=>x.missionId));
 if(new Set(schedule.map(x=>x.missionId)).size!==3||schedule.some((x,i)=>{const slot=rules.wordHuntSchedule[i]!;const within='spawnWindowMs' in slot?x.startsAfterMs>=slot.spawnWindowMs[0]&&x.startsAfterMs<slot.spawnWindowMs[1]:x.startsAfterMs===slot.spawnAtMs;return !missionIds.has(x.missionId)||x.kind!==slot.kind||!within||x.endsAfterMs-x.startsAfterMs!==rules.time.wordHuntMs;}))throw Error('invalid schedule');
 if(input.randomSchedule.suddenDeathObjectiveId!==input.privateSolution.suddenDeath.objectiveId)throw Error('invalid sudden death objective');
 if(new Set(input.randomSchedule.hintRevealOrder).size!==input.privateSolution.finalChallenge.hintUnits.length||input.randomSchedule.hintRevealOrder.some(x=>x<0||x>=input.privateSolution.finalChallenge.hintUnits.length))throw Error('invalid hint order');
 const player=(playerId:string)=>({playerId,assetLoadStatus:'PENDING' as const,assetFailure:null,assetAttestation:null,score:0,wrongFinalAttempts:0,hintCredits:0,revealedHintIndexes:[],publicPattern:null,finalAnswerStatus:'NOT_SUBMITTED' as const,meaningCorrect:null,answerUntilMs:null,tapRateWindow:{windowIndex:null,acceptedCount:0}});
 const state:MatchInitialStateV1={matchId:input.matchId,engineVersion:input.engineVersion,rulesetVersion:'1.0.0',rulesetHash:input.rulesetHash,contentRevisionId:input.contentManifest.contentRevisionId,contentHash:input.contentManifest.publicContentHash,assetPolicyVersion:'1.0.0',createdAtMs:input.createdAtMs,assetLoadDeadlineMs:input.createdAtMs+rules.time.assetLoadMs,expectedAssets:input.contentManifest.expectedAssets,phase:'WAITING_FOR_ASSETS',phaseEndsAtMs:null,startedAtMs:null,gameplayClosesAtMs:null,settlementCapAtMs:null,stateRevision:0,nextEventSeq:1,players:[player(input.playerIds[0]),player(input.playerIds[1])],connections:[{playerId:input.playerIds[0],status:'CONNECTED',disconnectEpoch:0,disconnectedAtMs:null,forfeitAtMs:null},{playerId:input.playerIds[1],status:'CONNECTED',disconnectEpoch:0,disconnectedAtMs:null,forfeitAtMs:null}],objectives:[...input.privateSolution.differences.map(x=>({objectiveId:x.objectiveId,kind:'DIFFERENCE' as const,ownerPlayerId:null})),...input.privateSolution.wordHunts.map(x=>({objectiveId:x.missionId,kind:'WORD_HUNT' as const,ownerPlayerId:null}))],activeMission:null,finalChallenge:{unlockedAtMs:null,unlockSource:null},meaningQuizzes:[],suddenDeath:null,randomSchedule:input.randomSchedule,privateSolution:input.privateSolution,winnerPlayerId:null,endReason:null};
 return {state,timerIntents:[{kind:'SCHEDULE' as const,timerId:`${input.matchId}:timer:ASSET_LOAD_TIMEOUT:asset`,dueAtMs:state.assetLoadDeadlineMs,payload:{type:'ASSET_LOAD_TIMEOUT' as const}}] as const};
}

export function reduceMatch(state:MatchStateV1,command:MatchCommand,rules:RulesetV1):ReduceResult {
 if(command.matchId!==state.matchId)throw Error('match mismatch');
 if(state.phase==='FINISHED'||state.phase==='CANCELLED')return rejected(state,'MATCH_INPUT_CLOSED');
 if(command.source!=='PLAYER'||command.payload.type!=='READY')return reduceOther(state,command,rules);
 if(command.expectedRevision>state.stateRevision)return rejected(state,'REVISION_AHEAD');
 const index=state.players.findIndex(p=>p.playerId===command.playerId);if(index<0)return rejected(state,'NOT_A_PARTICIPANT');
 const current=state.players[index]!;if(current.assetLoadStatus!=='PENDING')return rejected(state,'ALREADY_READY');
 const payload=command.payload;const expected=new Map(state.expectedAssets.map(a=>[a.sha256,a]));
 const valid=payload.contentRevisionId===state.contentRevisionId&&payload.contentHash===state.contentHash&&payload.assetHashes.length===expected.size&&new Set(payload.assetHashes).size===expected.size&&payload.assetHashes.every(h=>expected.has(h))&&payload.decodedDimensions.length===expected.size&&payload.decodedDimensions.every(d=>{const a=expected.get(d.assetHash);return a?.width===d.width&&a.height===d.height});
 const next=structuredClone(state) as MatchStateV1;const player=next.players[index]!;const intents:TimerIntent[]=[];let type='ASSET_READY_CHANGED';let eventPayload:Record<string,unknown>;
 if(!valid){player.assetLoadStatus='FAILED';player.assetFailure={reason:'ATTESTATION_MISMATCH'};next.phase='CANCELLED';next.endReason='NO_CONTEST_ASSET_LOAD';intents.push({kind:'CANCEL',timerId:`${state.matchId}:timer:ASSET_LOAD_TIMEOUT:asset`});eventPayload={winnerPlayerId:null,endReason:next.endReason};type='MATCH_FINISHED';}
 else {player.assetLoadStatus='READY';player.assetAttestation={contentHash:payload.contentHash,assetHashes:payload.assetHashes,decodedDimensions:payload.decodedDimensions};const readyCount=next.players.filter(p=>p.assetLoadStatus==='READY').length as 1|2;if(readyCount===2){next.phase='COUNTDOWN';next.phaseEndsAtMs=command.receivedAtMs+rules.time.countdownMs;intents.push({kind:'CANCEL',timerId:`${state.matchId}:timer:ASSET_LOAD_TIMEOUT:asset`},{kind:'SCHEDULE',timerId:`${state.matchId}:timer:START_MATCH:countdown`,dueAtMs:next.phaseEndsAtMs,payload:{type:'START_MATCH'}});}eventPayload={playerId:player.playerId,readyCount,countdownEndsAtMs:next.phaseEndsAtMs};}
 next.stateRevision=state.stateRevision+1;const event:MatchEvent={eventId:`${state.matchId}:${state.nextEventSeq}`,matchId:state.matchId,eventSeq:state.nextEventSeq,causedByCommandSeq:command.commandSeq,stateRevision:next.stateRevision,occurredAtMs:command.receivedAtMs,phase:next.phase,type,payload:eventPayload};next.nextEventSeq++;
 return {state:next,events:[event],timerIntents:intents,decision:{status:'APPLIED'}};
}
function rejected(state:MatchStateV1,reason:any):ReduceResult{return {state,events:[],timerIntents:[],decision:{status:'REJECTED',reason}};}

function reduceOther(state:MatchStateV1,command:MatchCommand,rules:RulesetV1):ReduceResult {
 if(command.source==='PLAYER'&&command.expectedRevision>state.stateRevision)return rejected(state,'REVISION_AHEAD');
 const next=structuredClone(state) as MatchStateV1;const at=command.source==='TIMER'?command.dueAtMs:command.receivedAtMs;const raw:Array<{type:string;payload:Record<string,unknown>}>=[];const intents:TimerIntent[]=[];
 const emit=(type:string,payload:Record<string,unknown>)=>raw.push({type,payload});const schedule=(type:string,scope:string,dueAtMs:number,payload:any)=>intents.push({kind:'SCHEDULE',timerId:`${state.matchId}:timer:${type}:${scope}`,dueAtMs,payload});
 const finish=(winner:string|null,reason:any)=>{next.winnerPlayerId=winner;next.endReason=reason;next.phase=reason==='NO_CONTEST'||reason==='NO_CONTEST_ASSET_LOAD'?'CANCELLED':'FINISHED';emit('MATCH_FINISHED',{winnerPlayerId:winner,endReason:reason});};
 if(command.source==='PLAYER'){
  const p=next.players.find(x=>x.playerId===command.playerId);if(!p)return rejected(state,'NOT_A_PARTICIPANT');const q=command.payload;
  if(q.type==='REPORT_ASSET_LOAD_FAILURE'){if(next.phase!=='WAITING_FOR_ASSETS'||p.assetLoadStatus!=='PENDING'||!next.expectedAssets.some(a=>a.sha256===q.assetHash))return rejected(state,'INPUT_LOCKED');p.assetLoadStatus='FAILED';p.assetFailure={reason:'FETCH_FAILED',assetHash:q.assetHash,attempts:2};intents.push({kind:'CANCEL',timerId:`${state.matchId}:timer:ASSET_LOAD_TIMEOUT:asset`});finish(null,'NO_CONTEST_ASSET_LOAD');}
  else if(q.type==='TAP_IMAGE'){
   if(next.startedAtMs===null||!['PLAYING','FINAL_RUSH','SUDDEN_DEATH'].includes(next.phase))return rejected(state,'INPUT_LOCKED');const wi=Math.floor((at-next.startedAtMs)/1000);if(p.tapRateWindow.windowIndex!==wi)p.tapRateWindow={windowIndex:wi,acceptedCount:0};if(p.tapRateWindow.acceptedCount>=rules.limits.maxBoardTapsPerSecond)return rejected(state,'RATE_LIMITED');p.tapRateWindow.acceptedCount++;
   const side=q.imageSide==='A'?'imageA':'imageB';let target:any=null;if(next.phase==='SUDDEN_DEATH')target=next.privateSolution.suddenDeath;else if(next.activeMission&&at>=next.activeMission.startedAtMs+rules.time.wordHuntRevealMs&&at<next.activeMission.endsAtMs)target=next.privateSolution.wordHunts.find(w=>w.missionId===next.activeMission!.missionId);else target=next.privateSolution.differences.find(d=>!next.objectives.find(o=>o.objectiveId===d.objectiveId)?.ownerPlayerId&&inside(q.x,q.y,d.hitboxes[side]));const hit=!!target&&inside(q.x,q.y,target.hitboxes[side]);emit('TAP_RESOLVED',{playerId:p.playerId,requestId:command.requestId,hit,objectiveId:hit?(target.objectiveId??target.missionId):null});
   if(hit&&next.phase==='SUDDEN_DEATH')finish(p.playerId,'SUDDEN_DEATH');else if(hit){const id=target.objectiveId??target.missionId;const obj=next.objectives.find(o=>o.objectiveId===id)!;if(obj.ownerPlayerId)return rejected(state,'ALREADY_CLAIMED');obj.ownerPlayerId=p.playerId;const word=!target.tier;const delta=word?(target.kind==='SPECIAL'?rules.score.specialWordHunt:rules.score.normalWordHunt):(target.tier==='HARD'?rules.score.hardDifference:rules.score.normalDifference)*(next.phase==='FINAL_RUSH'?rules.score.finalRushDifferenceMultiplier:1);p.score+=delta;emit(word?'WORD_HUNT_WON':'OBJECTIVE_CLAIMED',word?{missionId:id,playerId:p.playerId}:{objectiveId:id,ownerPlayerId:p.playerId,kind:'DIFFERENCE'});emit('SCORE_CHANGED',{playerId:p.playerId,delta,absoluteScore:p.score});if(word){p.hintCredits++;next.activeMission=null;emit('HINT_CREDIT_CHANGED',{playerId:p.playerId,delta:1,absoluteCredits:p.hintCredits});}unlock(next,at,word?'WORD_HUNT':'DIFFERENCE',emit);if(p.score>=rules.targetScore)finish(p.playerId,'SCORE_TARGET');}
  } else if(q.type==='USE_HINT'){if(p.hintCredits<1)return rejected(state,'NO_HINT_CREDIT');if(next.finalChallenge.unlockedAtMs===null||!['PLAYING','FINAL_RUSH'].includes(next.phase))return rejected(state,'INPUT_LOCKED');const idx=next.randomSchedule.hintRevealOrder[p.revealedHintIndexes.length];if(idx===undefined)return rejected(state,'INPUT_LOCKED');p.hintCredits--;p.revealedHintIndexes=[...p.revealedHintIndexes,idx];p.publicPattern=next.privateSolution.finalChallenge.hintUnits.map((u,i)=>p.revealedHintIndexes.includes(i)?u:'_').join('');emit('HINT_REVEALED',{playerId:p.playerId,hintIndex:idx,publicPattern:p.publicPattern});emit('HINT_CREDIT_CHANGED',{playerId:p.playerId,delta:-1,absoluteCredits:p.hintCredits});
  } else if(q.type==='SUBMIT_FINAL_ANSWER'){if(next.finalChallenge.unlockedAtMs===null||p.finalAnswerStatus!=='NOT_SUBMITTED'||(p.answerUntilMs!==null&&at<p.answerUntilMs)||!['PLAYING','FINAL_RUSH'].includes(next.phase))return rejected(state,'INPUT_LOCKED');const normalized=normalizeFinalAnswer(q.answer);const correct=[next.privateSolution.finalChallenge.canonicalAnswer,...next.privateSolution.finalChallenge.aliases].some(a=>normalizeFinalAnswer(a)===normalized);if(correct){p.finalAnswerStatus='MEANING_PENDING';const ordinal=next.meaningQuizzes.filter(x=>x.playerId===p.playerId).length+1;const endsAtMs=Math.min(at+rules.time.meaningQuizMs,next.settlementCapAtMs??Number.MAX_SAFE_INTEGER);next.meaningQuizzes=[...next.meaningQuizzes,{playerId:p.playerId,quizOrdinal:ordinal,startedAtMs:at,endsAtMs,submitted:false}];schedule('MEANING_TIMEOUT',`${p.playerId}:${ordinal}`,endsAtMs,{type:'MEANING_TIMEOUT',playerId:p.playerId,quizOrdinal:ordinal});emit('MEANING_QUIZ_STARTED',{playerId:p.playerId,quizOrdinal:ordinal,endsAtMs});}else{p.wrongFinalAttempts++;const delta=next.phase==='FINAL_RUSH'?rules.score.finalRushWrongAnswer:rules.score.wrongAnswer;p.score=Math.max(rules.scoreFloor,p.score+delta);emit('SCORE_CHANGED',{playerId:p.playerId,delta,absoluteScore:p.score});if(p.wrongFinalAttempts>=rules.finalChallenge.maxWrongAttempts)p.finalAnswerStatus='FAILED';else{const lock=next.phase==='FINAL_RUSH'?rules.lockMs.finalRushWrongAnswer:rules.lockMs.wrongAnswer;p.answerUntilMs=at+lock;schedule('ANSWER_LOCK_EXPIRED',`${p.playerId}:${p.wrongFinalAttempts}`,p.answerUntilMs,{type:'ANSWER_LOCK_EXPIRED',playerId:p.playerId,wrongAttemptOrdinal:p.wrongFinalAttempts});emit('ANSWER_LOCK_CHANGED',{playerId:p.playerId,answerUntilMs:p.answerUntilMs,reason:next.phase==='FINAL_RUSH'?'FINAL_RUSH_WRONG_ANSWER':'WRONG_ANSWER'});}}
  } else if(q.type==='SUBMIT_MEANING'){const quiz=[...next.meaningQuizzes].reverse().find(x=>x.playerId===p.playerId&&!x.submitted);if(!quiz||at>=quiz.endsAtMs)return rejected(state,'INPUT_LOCKED');quiz.submitted=true;p.meaningCorrect=q.optionId===next.privateSolution.finalChallenge.meaning.correctOptionId;p.finalAnswerStatus='SETTLED';const delta=rules.score.finalWord+(p.meaningCorrect?rules.score.meaning:0);p.score+=delta;emit('SCORE_CHANGED',{playerId:p.playerId,delta,absoluteScore:p.score});if(p.score>=rules.targetScore)finish(p.playerId,'SCORE_TARGET');else settleIfReady(next,rules,at,emit,intents);}
  else return rejected(state,'INPUT_LOCKED');
 } else if(command.source==='TIMER'){
  const q=command.payload;
  if(q.type==='ASSET_LOAD_TIMEOUT'){if(next.phase!=='WAITING_FOR_ASSETS'||at!==next.assetLoadDeadlineMs)return rejected(state,'OBSOLETE_TIMER');for(const p of next.players)if(p.assetLoadStatus==='PENDING'){p.assetLoadStatus='FAILED';p.assetFailure={reason:'TIMEOUT'}}finish(null,'NO_CONTEST_ASSET_LOAD');}
  else if(q.type==='START_MATCH'){if(next.phase!=='COUNTDOWN'||next.phaseEndsAtMs!==at)return rejected(state,'OBSOLETE_TIMER');next.phase='PLAYING';next.startedAtMs=at;next.gameplayClosesAtMs=at+rules.time.playingMs;next.settlementCapAtMs=at+rules.time.meaningSettlementCapMs;next.phaseEndsAtMs=next.gameplayClosesAtMs;emit('MATCH_STARTED',{startedAtMs:at});for(const w of next.randomSchedule.wordHunts){schedule('START_WORD_HUNT',w.missionId,at+w.startsAfterMs,{type:'START_WORD_HUNT',missionId:w.missionId});schedule('END_WORD_HUNT',w.missionId,at+w.endsAfterMs,{type:'END_WORD_HUNT',missionId:w.missionId});}schedule('UNLOCK_FINAL_CHALLENGE','final',at+rules.finalChallenge.unlock.atMs,{type:'UNLOCK_FINAL_CHALLENGE'});schedule('START_FINAL_RUSH','final-rush',at+rules.time.finalRushStartsAtMs,{type:'START_FINAL_RUSH'});schedule('CLOSE_INPUT','close',next.gameplayClosesAtMs,{type:'CLOSE_INPUT'});}
  else if(q.type==='START_WORD_HUNT'){if(!['PLAYING','FINAL_RUSH'].includes(next.phase)||next.activeMission)return rejected(state,'OBSOLETE_TIMER');const mission=next.privateSolution.wordHunts.find(w=>w.missionId===q.missionId);const slot=next.randomSchedule.wordHunts.find(w=>w.missionId===q.missionId);if(!mission||!slot||next.startedAtMs!+slot.startsAfterMs!==at)return rejected(state,'OBSOLETE_TIMER');next.activeMission={missionId:mission.missionId,kind:mission.kind,publicPrompt:mission.publicPrompt,startedAtMs:at,endsAtMs:next.startedAtMs!+slot.endsAfterMs};emit('WORD_HUNT_STARTED',{...next.activeMission});}
  else if(q.type==='END_WORD_HUNT'){if(next.activeMission?.missionId!==q.missionId||next.activeMission.endsAtMs!==at)return rejected(state,'OBSOLETE_TIMER');next.activeMission=null;emit('WORD_HUNT_ENDED',{missionId:q.missionId,reason:'TIMEOUT'});}
  else if(q.type==='UNLOCK_FINAL_CHALLENGE'){if(next.finalChallenge.unlockedAtMs!==null)return rejected(state,'OBSOLETE_TIMER');unlock(next,at,'TIME',emit);}
  else if(q.type==='START_FINAL_RUSH'){if(next.phase!=='PLAYING'||next.startedAtMs!+rules.time.finalRushStartsAtMs!==at)return rejected(state,'OBSOLETE_TIMER');next.phase='FINAL_RUSH';emit('FINAL_RUSH_STARTED',{startedAtMs:at});}
  else if(q.type==='CLOSE_INPUT'){if(!['PLAYING','FINAL_RUSH'].includes(next.phase)||next.gameplayClosesAtMs!==at)return rejected(state,'OBSOLETE_TIMER');next.phase='SETTLING';emit('INPUT_CLOSED',{closedAtMs:at,settlementCapAtMs:next.settlementCapAtMs!});settleIfReady(next,rules,at,emit,intents);}
  else if(q.type==='ANSWER_LOCK_EXPIRED'){const p=next.players.find(x=>x.playerId===q.playerId);if(!p||p.wrongFinalAttempts!==q.wrongAttemptOrdinal||p.answerUntilMs!==at)return rejected(state,'OBSOLETE_TIMER');p.answerUntilMs=null;emit('ANSWER_LOCK_CHANGED',{playerId:p.playerId,answerUntilMs:null,reason:'EXPIRED'});}
  else if(q.type==='MEANING_TIMEOUT'){const quiz=next.meaningQuizzes.find(x=>x.playerId===q.playerId&&x.quizOrdinal===q.quizOrdinal);if(!quiz||quiz.submitted||quiz.endsAtMs!==at)return rejected(state,'OBSOLETE_TIMER');quiz.submitted=true;const p=next.players.find(x=>x.playerId===q.playerId)!;p.meaningCorrect=false;p.finalAnswerStatus='SETTLED';p.score+=rules.score.finalWord;emit('SCORE_CHANGED',{playerId:p.playerId,delta:rules.score.finalWord,absoluteScore:p.score});if(p.score>=rules.targetScore)finish(p.playerId,'SCORE_TARGET');else settleIfReady(next,rules,at,emit,intents);}
  else if(q.type==='DISCONNECT_FORFEIT_TIMEOUT'){const c=next.connections.find(x=>x.playerId===q.playerId);if(!c||c.status!=='DISCONNECTED'||c.disconnectEpoch!==q.disconnectEpoch||c.forfeitAtMs!==at)return rejected(state,'OBSOLETE_TIMER');finish(next.players.find(x=>x.playerId!==q.playerId)!.playerId,'FORFEIT');}
  else if(q.type==='SUDDEN_DEATH_TIMEOUT'){if(next.phase!=='SUDDEN_DEATH'||next.suddenDeath?.endsAtMs!==at)return rejected(state,'OBSOLETE_TIMER');finish(null,'DRAW');}
 } else {const q=command.payload;if(q.type==='CANCEL_NO_CONTEST')finish(null,'NO_CONTEST');else{const c=next.connections.find(x=>x.playerId===q.playerId);if(!c)return rejected(state,'OBSOLETE_SYSTEM_COMMAND');if(q.status==='DISCONNECTED'){if(c.status!=='CONNECTED'||q.disconnectEpoch!==c.disconnectEpoch+1)return rejected(state,'OBSOLETE_SYSTEM_COMMAND');c.status='DISCONNECTED';c.disconnectEpoch=q.disconnectEpoch;c.disconnectedAtMs=at;c.forfeitAtMs=at+rules.time.reconnectForfeitMs;schedule('DISCONNECT_FORFEIT_TIMEOUT',`${c.playerId}:${c.disconnectEpoch}`,c.forfeitAtMs,{type:'DISCONNECT_FORFEIT_TIMEOUT',playerId:c.playerId,disconnectEpoch:c.disconnectEpoch});}else{if(c.status!=='DISCONNECTED'||q.disconnectEpoch!==c.disconnectEpoch)return rejected(state,'OBSOLETE_SYSTEM_COMMAND');intents.push({kind:'CANCEL',timerId:`${state.matchId}:timer:DISCONNECT_FORFEIT_TIMEOUT:${c.playerId}:${c.disconnectEpoch}`});c.status='CONNECTED';c.disconnectedAtMs=null;c.forfeitAtMs=null;}emit('PLAYER_CONNECTION_CHANGED',{playerId:c.playerId,status:c.status,disconnectEpoch:c.disconnectEpoch,forfeitAtMs:c.forfeitAtMs});}}
 if(raw.length===0)return rejected(state,'OBSOLETE_TIMER');next.stateRevision=state.stateRevision+1;let seq=state.nextEventSeq;const events:MatchEvent[]=raw.map(e=>({eventId:`${state.matchId}:${seq}`,matchId:state.matchId,eventSeq:seq++,causedByCommandSeq:command.commandSeq,stateRevision:next.stateRevision,occurredAtMs:at,phase:next.phase,type:e.type,payload:e.payload}));next.nextEventSeq=seq;return {state:next,events,timerIntents:intents,decision:{status:'APPLIED'}};
}
function inside(x:number,y:number,c:{cx:number;cy:number;r:number}){const dx=x-c.cx,dy=y-c.cy;return dx*dx+dy*dy<=c.r*c.r;}
function unlock(s:MatchStateV1,at:number,source:'TIME'|'DIFFERENCE'|'WORD_HUNT',emit:(t:string,p:Record<string,unknown>)=>void){if(s.finalChallenge.unlockedAtMs!==null)return;s.finalChallenge={unlockedAtMs:at,unlockSource:source};for(const p of s.players)p.publicPattern='_'.repeat(s.privateSolution.finalChallenge.hintUnits.length);emit('FINAL_CHALLENGE_UNLOCKED',{unlockedAtMs:at,source,publicPattern:s.players[0].publicPattern!});}
function settleIfReady(s:MatchStateV1,r:RulesetV1,at:number,emit:(t:string,p:Record<string,unknown>)=>void,intents:TimerIntent[]){if(s.phase!=='SETTLING'||s.meaningQuizzes.some(q=>!q.submitted))return;s.phase='TIEBREAK_EVAL';const [a,b]=s.players;const hard=(id:string)=>s.objectives.filter(o=>o.ownerPlayerId===id&&s.privateSolution.differences.some(d=>d.objectiveId===o.objectiveId&&d.tier==='HARD')).length;const values:ReadonlyArray<readonly [number,number]>=[[a.score,b.score],[a.meaningCorrect?1:0,b.meaningCorrect?1:0],[hard(a.playerId),hard(b.playerId)],[-a.wrongFinalAttempts,-b.wrongFinalAttempts]];for(const pair of values){const x=pair[0],y=pair[1];if(x!==y){s.winnerPlayerId=x>y?a.playerId:b.playerId;s.endReason='TIMEOUT_TIEBREAK';s.phase='FINISHED';emit('MATCH_FINISHED',{winnerPlayerId:s.winnerPlayerId,endReason:s.endReason});return;}}s.phase='SUDDEN_DEATH';s.suddenDeath={objectiveId:s.randomSchedule.suddenDeathObjectiveId,endsAtMs:at+r.time.suddenDeathMs};emit('SUDDEN_DEATH_STARTED',{...s.suddenDeath});intents.push({kind:'SCHEDULE',timerId:`${s.matchId}:timer:SUDDEN_DEATH_TIMEOUT:${s.suddenDeath.objectiveId}`,dueAtMs:s.suddenDeath.endsAtMs,payload:{type:'SUDDEN_DEATH_TIMEOUT'}});}
