import { randomUUID } from 'node:crypto';
import { Pool, type PoolClient } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { loadLocalDatabaseUrl } from '../support/local-supabase-status.js';

function localDbUrl(): URL {
  return loadLocalDatabaseUrl();
}
const rootUrl = localDbUrl(); const admin = new Pool({ connectionString: rootUrl.toString() }); const userId = randomUUID(); let subjectKey = ''; let api: Pool;
async function transaction(client: PoolClient, sql: string, values: readonly unknown[]) { await client.query('begin'); await client.query('set local role app_server'); try { const result = await client.query(sql, values); await client.query('commit'); return result; } catch (error) { await client.query('rollback'); throw error; } }

beforeAll(async () => { await admin.query("insert into auth.users(id,aud,role,email) values($1,'authenticated','authenticated',$2)",[userId,`${userId}@example.test`]); const url=new URL(rootUrl);url.username='touchcatch_api_test';url.password='touchcatch_local_test_only';api=new Pool({connectionString:url.toString(),max:4}); const client=await api.connect();try{const account=await transaction(client,'select private.ensure_account_v1($1) value',[userId]);subjectKey=(account.rows[0]?.value as {apiSubjectKey:string}).apiSubjectKey;}finally{client.release();} });
afterAll(async()=>{const failures:string[]=[];try{await api?.end();}catch{failures.push('api');}try{await admin.query('grant account_security_owner to postgres');}catch{failures.push('owner-grant');}if(subjectKey)try{await admin.query('delete from private.account_deletion_jobs where subject_key=$1',[subjectKey]);}catch{failures.push('job');}try{await admin.query('delete from auth.users where id=$1',[userId]);}catch{failures.push('auth-user');}try{await admin.query('revoke account_security_owner from postgres');}catch{failures.push('owner-revoke');}try{await admin.end();}catch{failures.push('database');}if(failures.length>0)throw new Error('LOCAL_DB_CLEANUP_FAILED');});

describe('account lifecycle serialization',()=>{
  it('replays the same nickname key under concurrency',async()=>{const key=randomUUID();const clients=await Promise.all([api.connect(),api.connect()]);try{const results=await Promise.all(clients.map(client=>transaction(client,'select private.update_profile_v1($1,$2,$3) value',[userId,key,'Concurrent Name'])));expect(new Set(results.map(result=>JSON.stringify(result.rows[0]?.value))).size).toBe(1);expect((await admin.query('select count(*)::int n from private.profile_update_decisions where idempotency_key=$1',[key])).rows[0]?.n).toBe(1);}finally{clients.forEach(client=>client.release());}});
  it('allows only one distinct nickname key inside the rate window',async()=>{await admin.query('grant account_security_owner to postgres');await admin.query("update private.profile_update_decisions set decided_at=clock_timestamp()-interval '2 minutes' where subject_key=(select subject_key from private.api_subjects where user_id=$1)",[userId]);const clients=await Promise.all([api.connect(),api.connect()]);try{const settled=await Promise.allSettled(clients.map((client,index)=>transaction(client,'select private.update_profile_v1($1,$2,$3)',[userId,randomUUID(),`Name ${index}`])));expect(settled.filter(result=>result.status==='fulfilled')).toHaveLength(1);expect(settled.filter(result=>result.status==='rejected'&&/RATE_LIMITED/u.test(String(result.reason)))).toHaveLength(1);}finally{clients.forEach(client=>client.release());}});
  it('leases one automatically ready HARD deletion job to exactly one worker',async()=>{const requester=await api.connect();let jobId:string;try{const result=await transaction(requester,'select private.request_account_deletion_v1($1,$2) value',[userId,randomUUID()]);jobId=(result.rows[0]?.value as {jobId:string}).jobId;}finally{requester.release();}const workers=await Promise.all(Array.from({length:10},()=>admin.connect()));try{const claims=await Promise.all(workers.map(async(client)=>{await client.query('begin');await client.query('set local role account_worker');const value=(await client.query('select private.claim_account_deletion_job_v1($1,$2) value',[randomUUID(),30000])).rows[0]?.value as {jobId?:string;deletionMode?:string}|null;await client.query('commit');return value;}));expect(claims.filter(claim=>claim?.jobId===jobId)).toHaveLength(1);expect(claims.find(claim=>claim?.jobId===jobId)?.deletionMode).toBe('HARD');}finally{workers.forEach(client=>client.release());}});
});
