import { execFileSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { resolve } from 'node:path';
import { Pool, type PoolClient } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { loadTestEconomyFixture } from '../helpers/load-test-economy-fixture.js';

function databaseUrl():string { const explicit=process.env.TEST_DATABASE_URL; const output=explicit??execFileSync(process.execPath,[resolve('D:/touchcatch/node_modules/supabase/dist/supabase.js'),'status','-o','env'],{encoding:'utf8'}); const raw=explicit??/^DB_URL=(?:"([^"]+)"|([^\r\n]+))$/mu.exec(output)?.slice(1).find(Boolean); if(!raw)throw new Error('local DB required');const url=new URL(raw);if(!['127.0.0.1','localhost','::1'].includes(url.hostname))throw new Error('loopback required');return url.toString(); }
const pool=new Pool({connectionString:databaseUrl(),max:25});
let fixture:Awaited<ReturnType<typeof loadTestEconomyFixture>>;
let economy:Record<string,unknown>;let catalog:Awaited<ReturnType<typeof loadTestEconomyFixture>>['catalog'];
async function role(c:PoolClient,name:'deployment_role'|'app_server'){await c.query(`set role ${name}`);expect((await c.query('select current_user')).rows[0]?.current_user).toBe(name);}
async function clients20(){const clients=await Promise.all(Array.from({length:20},()=>pool.connect()));await Promise.all(clients.map(c=>role(c,'app_server')));return clients;}
async function release(clients:PoolClient[]){await Promise.all(clients.map(async c=>{await c.query('reset role').catch(()=>undefined);c.release();}));}

beforeAll(async()=>{fixture=await loadTestEconomyFixture();catalog=fixture.publishInput.catalog;economy={...fixture.publishInput.economy,economyHash:fixture.economyHash};const c=await pool.connect();try{await role(c,'deployment_role');await c.query('select private.publish_economy_bundle_v1($1,$2)',[economy,catalog]);}finally{await c.query('reset role');c.release();}});
afterAll(async()=>pool.end());

describe('economy production-role concurrency',()=>{
  it('collapses 20 identical reward requests and conflicts when any policy reference changes',async()=>{const subject=randomUUID(),match=randomUUID();await pool.query('insert into private.economy_subjects(subject_key) values($1)',[subject]);const args=[match,subject,'MATCH_GACHA_POINTS',1,fixture.economyHash,fixture.catalogRevision,fixture.catalogHash];const cs=await clients20();try{const responses=await Promise.all(cs.map(c=>c.query('select private.award_match_reward_v1($1,$2,$3,$4,$5,$6,$7) r',args)));expect(new Set(responses.map(r=>JSON.stringify(r.rows[0]?.r)))).toHaveLength(1);expect((await pool.query('select count(*)::int n from private.reward_ledger where subject_key=$1',[subject])).rows[0].n).toBe(1);await expect(cs[0]!.query('select private.award_match_reward_v1($1,$2,$3,$4,$5,$6,$7)',[...args.slice(0,4),'f'.repeat(64),...args.slice(5)])).rejects.toThrow(/IDEMPOTENCY_CONFLICT/);}finally{await release(cs);}});
  it('collapses 20 same-key draws before entropy',async()=>{const subject=randomUUID(),key=randomUUID();await pool.query('insert into private.economy_subjects(subject_key,gacha_points) values($1,100)',[subject]);const args=[subject,key,'a'.repeat(64),fixture.economyVersion,fixture.economyHash,fixture.catalogRevision,fixture.catalogHash];const cs=await clients20();try{const rs=await Promise.all(cs.map(c=>c.query('select private.draw_pet_v1($1,$2,$3,$4,$5,$6,$7) r',args)));expect(new Set(rs.map(r=>JSON.stringify(r.rows[0]?.r)))).toHaveLength(1);expect((await pool.query('select count(*)::int n from private.gacha_history where subject_key=$1',[subject])).rows[0].n).toBe(1);}finally{await release(cs);}});
  it('keeps the same UUID independent across two subjects',async()=>{const a=randomUUID(),b=randomUUID(),key=randomUUID();await pool.query('insert into private.economy_subjects(subject_key,gacha_points) values($1,100),($2,100)',[a,b]);const c=await pool.connect();try{await role(c,'app_server');for(const subject of[a,b])await c.query('select private.draw_pet_v1($1,$2,$3,$4,$5,$6,$7)',[subject,key,'b'.repeat(64),fixture.economyVersion,fixture.economyHash,fixture.catalogRevision,fixture.catalogHash]);expect((await pool.query('select count(*)::int n from private.gacha_history where subject_key=any($1)',[[a,b]])).rows[0].n).toBe(2);}finally{await c.query('reset role');c.release();}});
  it('rejects DRAFT and forged/extra publisher artifacts without rows',async()=>{const before=(await pool.query('select count(*)::int n from private.economy_policy_revisions')).rows[0].n;const c=await pool.connect();try{await role(c,'deployment_role');for(const bad of[{...economy,status:'DRAFT'},{...economy,extra:true},{...economy,approvalDecisionId:'FORGED'}])await expect(c.query('select private.publish_economy_bundle_v1($1,$2)',[bad,catalog])).rejects.toThrow();expect((await pool.query('select count(*)::int n from private.economy_policy_revisions')).rows[0].n).toBe(before);}finally{await c.query('reset role');c.release();}});
  it('serializes 20 distinct-key draws without lost balance or history',async()=>{const subject=randomUUID();await pool.query('insert into private.economy_subjects(subject_key,gacha_points) values($1,2000)',[subject]);const cs=await clients20();try{await Promise.all(cs.map((c,i)=>c.query('select private.draw_pet_v1($1,$2,$3,$4,$5,$6,$7)',[subject,`00000000-0000-4000-8000-${String(100+i).padStart(12,'0')}`,String(i).padStart(64,'a'),fixture.economyVersion,fixture.economyHash,fixture.catalogRevision,fixture.catalogHash])));expect((await pool.query('select gacha_points from private.economy_subjects where subject_key=$1',[subject])).rows[0].gacha_points).toBe('0');expect((await pool.query('select count(*)::int n from private.gacha_history where subject_key=$1',[subject])).rows[0].n).toBe(20);expect((await pool.query('select count(*)::int n from private.gacha_pity_state where subject_key=$1',[subject])).rows[0].n).toBe(1);}finally{await release(cs);}});
  it('fails incompatible pity publication closed and allows an exact-semantics version rollover',async()=>{const c=await pool.connect();try{await role(c,'deployment_role');const before=(await pool.query('select count(*)::int n from private.economy_policy_revisions')).rows[0].n;const incompatible={...economy,economyVersion:'2.0.0',economyHash:'b'.repeat(64),pitySemanticsHash:'d'.repeat(64)};expect((await c.query('select private.publish_economy_bundle_v1($1,$2) r',[incompatible,catalog])).rows[0].r).toEqual({code:'UNSUPPORTED_SERIES_MIGRATION'});expect((await pool.query('select count(*)::int n from private.economy_policy_revisions')).rows[0].n).toBe(before);const compatible={...economy,economyVersion:'1.1.0',economyHash:'1'.repeat(64)};await c.query('select private.publish_economy_bundle_v1($1,$2)',[compatible,catalog]);expect((await pool.query("select count(*)::int n from private.economy_policy_revisions where economy_version='1.1.0'")).rows[0].n).toBe(1);}finally{await c.query('reset role');c.release();}});
  it('rejects protected and duplicate fusion materials, then consumes exact five',async()=>{const subject=randomUUID(),material=randomUUID();await pool.query('insert into private.economy_subjects(subject_key) values($1)',[subject]);await pool.query("insert into private.pet_inventory(user_pet_id,subject_key,pet_id,rarity,copies,locked,acquired_catalog_revision,acquired_catalog_hash) values($1,$2,$3,'COMMON',5,true,$4,$5)",[material,subject,catalog.entries[0]!.petId,fixture.catalogRevision,fixture.catalogHash]);const c=await pool.connect();try{await role(c,'app_server');const call=(m:unknown,key=randomUUID())=>c.query('select private.fuse_pets_v1($1,$2,$3,$4,$5,$6,$7,$8)',[subject,key,'2'.repeat(64),JSON.stringify(m),fixture.economyVersion,fixture.economyHash,fixture.catalogRevision,fixture.catalogHash]);await expect(call([{userPetId:material,count:5}])).rejects.toThrow(/INVALID_MATERIALS/);await pool.query('update private.pet_inventory set locked=false where user_pet_id=$1',[material]);await expect(call([{userPetId:material,count:2},{userPetId:material,count:3}])).rejects.toThrow(/INVALID_MATERIALS/);const response=(await call([{userPetId:material,count:5}])).rows[0];expect(response).toBeDefined();expect((await pool.query('select count(*)::int n from private.fusion_history where subject_key=$1',[subject])).rows[0].n).toBe(1);}finally{await c.query('reset role');c.release();}});
});
