import { execFileSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { resolve } from 'node:path';
import { Pool, type PoolClient } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

function databaseUrl(): string {
  const explicit=process.env.TEST_DATABASE_URL;
  const output=explicit ?? execFileSync(process.execPath,[resolve('D:/touchcatch/node_modules/supabase/dist/supabase.js'),'status','-o','env'],{encoding:'utf8',windowsHide:true});
  const raw=explicit ?? /^DB_URL=(?:"([^"]+)"|([^\r\n]+))$/mu.exec(output)?.slice(1).find(Boolean);
  if(!raw) throw new Error('local Supabase DB_URL required'); const url=new URL(raw);
  if(!['127.0.0.1','localhost','::1'].includes(url.hostname)||url.pathname!=='/postgres') throw new Error('loopback postgres required'); return url.toString();
}
const pool=new Pool({connectionString:databaseUrl(),max:25});
const subject=randomUUID(); const matchId=randomUUID(); const key=randomUUID();
const catalog={catalogRevision:'catalog-test',catalogHash:'c'.repeat(64),entries:Array.from({length:50},(_,i)=>({petId:`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`,rarity:i<30?'COMMON':i<45?'RARE':'LEGENDARY',displayKey:`pet.${i+1}`}))};
const economy={economyVersion:'1.0.0-test',economyHash:'e'.repeat(64),pitySeriesId:'pity-50-150-v1',pitySemanticsHash:'a'.repeat(64),pitySemantics:{thresholds:{rareOrBetter:50,legendary:150}},drawCost:100,rewardPolicies:{MATCH_GACHA_POINTS:1}};
async function role(client:PoolClient,name:'deployment_role'|'app_server'){await client.query(`set role ${name}`); const r=await client.query('select current_user'); expect(r.rows[0]?.current_user).toBe(name);}

beforeAll(async()=>{
  await pool.query(`insert into private.economy_subjects(subject_key,gacha_points) values($1,0)`,[subject]);
  const c=await pool.connect(); try { await role(c,'deployment_role'); await c.query('select private.publish_economy_bundle_v1($1,$2)',[economy,catalog]); } finally {await c.query('reset role').catch(()=>undefined); c.release();}
});
afterAll(async()=>{await pool.end();});

describe('economy production-role concurrency',()=>{
  it('collapses 20 same-key rewards to one effect and one outbox response',async()=>{
    const clients=await Promise.all(Array.from({length:20},()=>pool.connect())); try {await Promise.all(clients.map(c=>role(c,'app_server'))); let go!:()=>void; const barrier=new Promise<void>(r=>{go=r}); const calls=clients.map(async c=>{await barrier; return (await c.query('select private.award_match_reward_v1($1,$2,$3,$4,$5,$6,$7) response',[matchId,subject,'MATCH_GACHA_POINTS',1,'e'.repeat(64),'catalog-test','c'.repeat(64)])).rows[0]?.response;}); go(); const responses=await Promise.all(calls); expect(new Set(responses.map((value)=>JSON.stringify(value)))).toHaveLength(1); expect((await pool.query('select count(*)::int n from private.reward_ledger where subject_key=$1',[subject])).rows[0]?.n).toBe(1); expect(Number((await pool.query('select gacha_points from private.economy_subjects where subject_key=$1',[subject])).rows[0]?.gacha_points)).toBe(1); expect((await pool.query("select count(*)::int n from private.outbox_events where operation_scope='REWARD_V1' and aggregate_key=$1",[subject])).rows[0]?.n).toBe(1);} finally {await Promise.all(clients.map(async c=>{await c.query('reset role').catch(()=>undefined);c.release();}));}
  });
  it('same client UUID is independent across subjects and same subject conflicts on changed hash',async()=>{
    const other=randomUUID(); await pool.query('insert into private.economy_subjects(subject_key,gacha_points) values($1,500)',[other]); await pool.query('update private.economy_subjects set gacha_points=500 where subject_key=$1',[subject]);
    const c=await pool.connect(); try {await role(c,'app_server'); const refs=[key,'b'.repeat(64),'1.0.0-test','e'.repeat(64),'catalog-test','c'.repeat(64)]; await c.query('select private.draw_pet_v1($1,$2,$3,$4,$5,$6,$7)',[subject,...refs]); await c.query('select private.draw_pet_v1($1,$2,$3,$4,$5,$6,$7)',[other,...refs]); await expect(c.query('select private.draw_pet_v1($1,$2,$3,$4,$5,$6,$7)',[subject,key,'d'.repeat(64),...refs.slice(2)])).rejects.toThrow(/IDEMPOTENCY_CONFLICT/); } finally {await c.query('reset role').catch(()=>undefined);c.release();}
  });
  it('collapses 20 same-key draws before entropy and creates one acquisition/outbox',async()=>{
    const drawSubject=randomUUID(); const drawKey=randomUUID(); await pool.query('insert into private.economy_subjects(subject_key,gacha_points) values($1,100)',[drawSubject]);
    const clients=await Promise.all(Array.from({length:20},()=>pool.connect())); try {await Promise.all(clients.map(c=>role(c,'app_server')));let go!:()=>void;const barrier=new Promise<void>(r=>{go=r});const calls=clients.map(async c=>{await barrier;return (await c.query('select private.draw_pet_v1($1,$2,$3,$4,$5,$6,$7) response',[drawSubject,drawKey,'f'.repeat(64),economy.economyVersion,economy.economyHash,catalog.catalogRevision,catalog.catalogHash])).rows[0]?.response});go();const responses=await Promise.all(calls);expect(new Set(responses.map(v=>JSON.stringify(v)))).toHaveLength(1);expect((await pool.query('select count(*)::int n from private.gacha_history where subject_key=$1',[drawSubject])).rows[0]?.n).toBe(1);expect((await pool.query('select count(*)::int n from private.pet_inventory where subject_key=$1',[drawSubject])).rows[0]?.n).toBe(1);expect(Number((await pool.query('select gacha_points from private.economy_subjects where subject_key=$1',[drawSubject])).rows[0]?.gacha_points)).toBe(0);}finally{await Promise.all(clients.map(async c=>{await c.query('reset role').catch(()=>undefined);c.release()}));}
  });
  it('serializes 20 distinct-key draws without lost balance or pity updates',async()=>{
    const drawSubject=randomUUID();await pool.query('insert into private.economy_subjects(subject_key,gacha_points) values($1,2000)',[drawSubject]);const clients=await Promise.all(Array.from({length:20},()=>pool.connect()));try{await Promise.all(clients.map(c=>role(c,'app_server')));let go!:()=>void;const barrier=new Promise<void>(r=>{go=r});const calls=clients.map(async(c,i)=>{await barrier;return c.query('select private.draw_pet_v1($1,$2,$3,$4,$5,$6,$7)',[drawSubject,`00000000-0000-4000-8000-${String(100+i).padStart(12,'0')}`,String(i).padStart(64,'a'),economy.economyVersion,economy.economyHash,catalog.catalogRevision,catalog.catalogHash])});go();await Promise.all(calls);expect(Number((await pool.query('select gacha_points from private.economy_subjects where subject_key=$1',[drawSubject])).rows[0]?.gacha_points)).toBe(0);expect((await pool.query('select count(*)::int n from private.gacha_history where subject_key=$1',[drawSubject])).rows[0]?.n).toBe(20);const pity=await pool.query('select rare_counter,legendary_counter from private.gacha_pity_state where subject_key=$1',[drawSubject]);expect(pity.rows).toHaveLength(1);expect(pity.rows[0]!.legendary_counter).toBeGreaterThanOrEqual(0);}finally{await Promise.all(clients.map(async c=>{await c.query('reset role').catch(()=>undefined);c.release()}));}
  });
  it('fails incompatible pity publication closed and permits same-semantics policy rollover',async()=>{
    const before=await pool.query('select count(*)::int n from private.economy_policy_revisions');const c=await pool.connect();try{await role(c,'deployment_role');const incompatible={...economy,economyVersion:'2.0.0-test',economyHash:'b'.repeat(64),pitySemanticsHash:'d'.repeat(64),pitySemantics:{thresholds:{rareOrBetter:10,legendary:150}}};const rejected=await c.query('select private.publish_economy_bundle_v1($1,$2) response',[incompatible,catalog]);expect(rejected.rows[0]?.response).toEqual({code:'UNSUPPORTED_SERIES_MIGRATION'});expect((await pool.query('select count(*)::int n from private.economy_policy_revisions')).rows[0]?.n).toBe(before.rows[0]?.n);const compatible={...economy,economyVersion:'1.1.0-test',economyHash:'1'.repeat(64),drawCost:120};await c.query('select private.publish_economy_bundle_v1($1,$2)',[compatible,catalog]);expect((await pool.query("select count(*)::int n from private.economy_policy_revisions where economy_version='1.1.0-test'")).rows[0]?.n).toBe(1);}finally{await c.query('reset role').catch(()=>undefined);c.release();}
  });
  it('rejects protected fusion material then consumes exactly five eligible copies',async()=>{
    const fusionSubject=randomUUID();const materialId=randomUUID();await pool.query('insert into private.economy_subjects(subject_key) values($1)',[fusionSubject]);await pool.query("insert into private.pet_inventory(user_pet_id,subject_key,pet_id,rarity,copies,locked,acquired_catalog_revision,acquired_catalog_hash) values($1,$2,$3,'COMMON',5,true,$4,$5)",[materialId,fusionSubject,catalog.entries[0]!.petId,catalog.catalogRevision,catalog.catalogHash]);const c=await pool.connect();try{await role(c,'app_server');const materials=[{userPetId:materialId,count:5}];await expect(c.query('select private.fuse_pets_v1($1,$2,$3,$4,$5,$6,$7,$8)',[fusionSubject,randomUUID(),'2'.repeat(64),JSON.stringify(materials),economy.economyVersion,economy.economyHash,catalog.catalogRevision,catalog.catalogHash])).rejects.toThrow(/INVALID_MATERIALS/);expect((await pool.query('select count(*)::int n from private.fusion_history where subject_key=$1',[fusionSubject])).rows[0]?.n).toBe(0);await pool.query('update private.pet_inventory set locked=false where user_pet_id=$1',[materialId]);const response=(await c.query('select private.fuse_pets_v1($1,$2,$3,$4,$5,$6,$7,$8) response',[fusionSubject,randomUUID(),'3'.repeat(64),JSON.stringify(materials),economy.economyVersion,economy.economyHash,catalog.catalogRevision,catalog.catalogHash])).rows[0]?.response;expect(response.output.rarity).toBe('RARE');expect((await pool.query('select count(*)::int n from private.fusion_history where subject_key=$1',[fusionSubject])).rows[0]?.n).toBe(1);expect((await pool.query('select count(*)::int n from private.pet_inventory where subject_key=$1',[fusionSubject])).rows[0]?.n).toBe(1);}finally{await c.query('reset role').catch(()=>undefined);c.release();}
  });
});
