import{randomUUID}from'node:crypto';import{Pool,type PoolClient}from'pg';import{afterAll,describe,expect,it}from'vitest';import{loadLocalDatabaseUrl}from'../support/local-supabase-status.js';
function databaseUrl(){return loadLocalDatabaseUrl().toString();}
const pool=new Pool({connectionString:databaseUrl(),max:22});async function app(c:PoolClient){await c.query('set role app_server');}afterAll(()=>pool.end());
const lease=async(c:PoolClient,match:string,owner:string,expectedOwner:string|null=null,expectedFence:number|null=null,leaseMs=15000)=>Number((await c.query('select private.acquire_match_lease_g3($1,$2,$3,$4,$5) fence',[match,owner,expectedOwner,expectedFence,leaseMs])).rows[0].fence);const release=async(c:PoolClient)=>{await c.query('reset role').catch(()=>{});c.release();};
const call=(c:PoolClient,match:string,request:string,owner:string,fence:number,fault:string|null=null)=>c.query('select private.apply_match_command_g3($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) r',[match,request,'a'.repeat(64),owner,fence,{type:'APPLIED'},{phase:'PLAYING'},`timer-${request}`,10,`effect-${request}`,fault]);
describe('G3 durable transaction adapter',()=>{
 it('collapses 20 duplicate requests',async()=>{const match=randomUUID(),owner=randomUUID(),request=randomUUID(),cs=await Promise.all(Array.from({length:20},()=>pool.connect()));try{await Promise.all(cs.map(app));const fence=await lease(cs[0]!,match,owner);const results=await Promise.all(cs.map(c=>call(c,match,request,owner,fence)));expect(new Set(results.map(x=>JSON.stringify(x.rows[0].r)))).toHaveLength(1);expect((await pool.query('select count(*)::int n from private.g3_journal where request_id=$1',[request])).rows[0].n).toBe(1);}finally{await Promise.all(cs.map(release));}});
 it('restarts after every injected boundary',async()=>{for(const fault of ['AFTER_CLAIM','AFTER_JOURNAL','AFTER_EFFECT']){const match=randomUUID(),owner=randomUUID(),request=randomUUID(),c=await pool.connect();try{await app(c);const fence=await lease(c,match,owner);await expect(call(c,match,request,owner,fence,fault)).rejects.toThrow(new RegExp(fault));expect((await pool.query('select count(*)::int n from private.g3_command_receipts where request_id=$1',[request])).rows[0].n).toBe(0);const result=(await call(c,match,request,owner,fence)).rows[0].r;expect((await call(c,match,request,owner,fence)).rows[0].r).toEqual(result);}finally{await release(c);}}});
 it('serializes 20 distinct requests with exact sequence continuity',async()=>{const match=randomUUID(),owner=randomUUID(),cs=await Promise.all(Array.from({length:20},()=>pool.connect()));try{await Promise.all(cs.map(app));const fence=await lease(cs[0]!,match,owner),requests=Array.from({length:20},()=>randomUUID());const results=await Promise.all(cs.map((c,i)=>call(c,match,requests[i]!,owner,fence)));expect(results.map(x=>x.rows[0].r.eventSeq).sort((a,b)=>a-b)).toEqual(Array.from({length:20},(_,i)=>i+1));}finally{await Promise.all(cs.map(release));}});
 it('requires CAS before expiry and rejects stale completion/replay',async()=>{const match=randomUUID(),oldOwner=randomUUID(),newOwner=randomUUID(),request=randomUUID(),c=await pool.connect();try{await app(c);const oldFence=await lease(c,match,oldOwner);await expect(lease(c,match,newOwner)).rejects.toThrow(/LEASE_HELD/);const completed=(await call(c,match,request,oldOwner,oldFence)).rows[0].r;const newFence=await lease(c,match,newOwner,oldOwner,oldFence);expect(newFence).toBe(oldFence+1);await expect(call(c,match,randomUUID(),oldOwner,oldFence)).rejects.toThrow(/STALE_LEASE/);await expect(call(c,match,request,oldOwner,oldFence)).rejects.toThrow(/STALE_LEASE/);expect(completed.eventSeq).toBe(1);}finally{await release(c);}});
 it('rejects apply from an expired owner before takeover',async()=>{const match=randomUUID(),owner=randomUUID(),c=await pool.connect();try{await app(c);const fence=await lease(c,match,owner,null,null,100);await new Promise(resolve=>setTimeout(resolve,150));await expect(call(c,match,randomUUID(),owner,fence)).rejects.toThrow(/STALE_LEASE/);expect((await pool.query('select count(*)::int n from private.g3_journal where match_id=$1',[match])).rows[0].n).toBe(0);}finally{await release(c);}});
 it('reclaims only an expired lease with current fence continuity',async()=>{const match=randomUUID(),oldOwner=randomUUID(),newOwner=randomUUID(),c=await pool.connect();try{await app(c);const oldFence=await lease(c,match,oldOwner,null,null,100);await new Promise(resolve=>setTimeout(resolve,150));await expect(lease(c,match,newOwner,null,oldFence-1)).rejects.toThrow(/LEASE_CAS_MISMATCH/);const newFence=await lease(c,match,newOwner,null,oldFence);expect(newFence).toBe(oldFence+1);}finally{await release(c);}});
});
