import {createHash} from 'node:crypto';
export type MatchStage='queue'|'handshake'|'preload'|'command'|'finish'|'reward';
export const OPERATIONAL_METRICS_V1=['tap_result_p95','unexpected_command_failure_rate','accepted_duplicate_effect_total','match_finish_loss_total','release_requirement_gate_status'] as const;
type RiskData={cellBucket:string;countBucket:string;windowDurationBucket:string}|{durationBucket:string};
export type AnalyticsEventV1={eventVersion:1;eventSeq:number;stateRevision:number;occurredAt:string;matchId:string;anonymousUserId:string;traceId:string;engineVersion:string;rulesetVersion:string;contentRevisionId:string;experimentVariant:'CONTROL'|'TREATMENT';serverVersion:string;protocolVersion:1;name:'same_coordinate_burst_signal'|'answer_reaction_time_signal'|'match_stage';data:RiskData|{stage:MatchStage}};

const envelopeKeys=['eventVersion','eventSeq','stateRevision','occurredAt','matchId','anonymousUserId','traceId','engineVersion','rulesetVersion','contentRevisionId','experimentVariant','serverVersion','protocolVersion','name','data'];
const forbidden=/(jwt|token|service.?key|secret|auth.?uuid|user.?id|email|phone|name|canonical.?answer|alias|correct.?option.?id|hitbox|raw.?upload|source.?data|coordinate|timestamp|objective.?id|option.?id|correctness|answer|^x$|^y$)/i;
const record=(x:unknown):x is Record<string,unknown>=>typeof x==='object'&&x!==null&&!Array.isArray(x);
const forbiddenValue=[/^[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}$/,/^sb_(?:secret|publishable)_/i,/^[^\s@]+@[^\s@]+\.[^\s@]+$/i,/^Bearer\s+\S+$/i,/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,/^[a-z][a-z0-9+.-]*:\/\/[^\s/:]+:[^\s/@]+@/i,/^(?:sk|pk|rk)_(?:live|test)_[A-Za-z0-9_-]{16,}$/i,/-----BEGIN [A-Z ]+PRIVATE KEY-----/];
function privacyScan(value:unknown,path='$'):void {
  if(typeof value==='string'&&forbiddenValue.some(pattern=>pattern.test(value)))throw new TypeError(`forbidden analytics value ${path}`);
  if(Array.isArray(value)){value.forEach((v,i)=>privacyScan(v,`${path}[${i}]`));return;}
  if(!record(value))return;
  for(const [key,nested] of Object.entries(value)){if(!(path==='$'&&envelopeKeys.includes(key))&&forbidden.test(key))throw new TypeError(`forbidden analytics field ${path}.${key}`);privacyScan(nested,`${path}.${key}`);}
}
function exact(value:Record<string,unknown>,keys:string[]){return Object.keys(value).length===keys.length&&Object.keys(value).every(k=>keys.includes(k));}
export function parseAnalyticsEventV1(input:unknown):AnalyticsEventV1{
  privacyScan(input);
  if(!record(input)||!exact(input,envelopeKeys)||input.eventVersion!==1||input.protocolVersion!==1||!Number.isSafeInteger(input.eventSeq)||Number(input.eventSeq)<0||!Number.isSafeInteger(input.stateRevision)||Number(input.stateRevision)<0)throw new TypeError('invalid analytics envelope');
  for(const key of ['matchId','anonymousUserId','traceId','engineVersion','rulesetVersion','contentRevisionId','serverVersion'])if(typeof input[key]!=='string'||input[key]===''||String(input[key]).length>128)throw new TypeError(`invalid ${key}`);
  if(!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(String(input.occurredAt))||!['CONTROL','TREATMENT'].includes(String(input.experimentVariant))||!record(input.data))throw new TypeError('invalid analytics values');
  const data=input.data;
  if(input.name==='match_stage'){if(!exact(data,['stage'])||!['queue','handshake','preload','command','finish','reward'].includes(String(data.stage)))throw new TypeError('invalid stage');}
  else if(input.name==='same_coordinate_burst_signal'){if(!exact(data,['cellBucket','countBucket','windowDurationBucket'])||!/^\d{2}:\d{2}$/.test(String(data.cellBucket))||!['1','2-3','4-7','8-15','16+'].includes(String(data.countBucket))||!['<1s','1-2s','2-5s','5s+'].includes(String(data.windowDurationBucket)))throw new TypeError('invalid bucket');}
  else if(input.name==='answer_reaction_time_signal'){if(!exact(data,['durationBucket'])||!['<250ms','250-499ms','500-999ms','1-2s','2s+'].includes(String(data.durationBucket)))throw new TypeError('invalid bucket');}
  else throw new TypeError('invalid analytics name');
  return input as AnalyticsEventV1;
}

const expected=new Set(['ALREADY_CLAIMED','ALREADY_READY','INPUT_LOCKED','RATE_LIMITED','REVISION_AHEAD']);
const unexpected=new Set(['INTERNAL_ERROR','DURABLE_RECEIPT_FAILURE','TRANSACTION_FAILURE','ACK_TIMEOUT']);
type RequestObservation={requestId:string;outcome:'SUCCESS'|'EXPECTED_REJECTION'|'UNEXPECTED_FAILURE';reason?:string|undefined;occurredAtMs?:number|undefined;schemaValid?:boolean|undefined};
export class AnalyticsCollector{
  private readonly terminal=new Map<string,RequestObservation>();
  recordRequest(r:RequestObservation){if(!r.requestId||r.schemaValid===false)return;if(r.outcome==='EXPECTED_REJECTION'&&(!r.reason||!expected.has(r.reason)))throw new TypeError('unexpected rejection reason');if(r.outcome==='UNEXPECTED_FAILURE'&&(!r.reason||!unexpected.has(r.reason)))throw new TypeError('unexpected failure reason');const previous=this.terminal.get(r.requestId);if(previous&&Number(r.occurredAtMs??0)<Number(previous.occurredAtMs??0))throw new TypeError('retry order must be monotonic');this.terminal.set(r.requestId,r);}
  snapshot(){let expectedCount=0,unexpected=0;for(const r of this.terminal.values()){if(r.outcome==='EXPECTED_REJECTION')expectedCount++;else if(r.outcome==='UNEXPECTED_FAILURE')unexpected++;}return{uniqueSchemaValidRequests:this.terminal.size,expectedDomainRejections:expectedCount,unexpectedFailures:unexpected};}
}
export function reconstructTrace(events:readonly AnalyticsEventV1[],traceId:string):MatchStage[]{const selected=events.filter(e=>e.traceId===traceId&&e.name==='match_stage').sort((a,b)=>a.eventSeq-b.eventSeq),stages=selected.map(e=>(e.data as {stage:MatchStage}).stage),required:MatchStage[]=['queue','handshake','preload','command','finish','reward'];if(selected.length!==6||new Set(selected.map(e=>e.eventSeq)).size!==6||new Set(selected.map(e=>e.matchId)).size!==1||stages.some((x,i)=>x!==required[i]))throw TypeError('complete unique ordered lifecycle with one match required');return stages;}

export type ExperimentContractV1={schemaVersion:1;experimentId:string;assignmentUnit:'anonymousUserId';assignmentSaltVersion:string;variants:['CONTROL','TREATMENT'];allocationBasisPoints:[number,number];primaryMetric:'final_attempt_rate';mde:number;alpha:number;power:number;minSamplePerVariant:number;guardrails:['tap_result_p95','unexpected_failure_rate','srm'];stoppingRule:'FIXED_HORIZON';cellBucket:string};
function parseExperimentContractStructureV1(x:unknown):ExperimentContractV1{if(!record(x)||!exact(x,['schemaVersion','experimentId','assignmentUnit','assignmentSaltVersion','variants','allocationBasisPoints','primaryMetric','mde','alpha','power','minSamplePerVariant','guardrails','stoppingRule','cellBucket']))throw TypeError('invalid experiment contract');const y=x as unknown as ExperimentContractV1;if(y.schemaVersion!==1||y.assignmentUnit!=='anonymousUserId'||JSON.stringify(y.variants)!=='["CONTROL","TREATMENT"]'||!Array.isArray(y.allocationBasisPoints)||y.allocationBasisPoints.length!==2||y.allocationBasisPoints.some(n=>!Number.isInteger(n)||n<=0)||y.allocationBasisPoints[0]+y.allocationBasisPoints[1]!==10000)throw TypeError('invalid assignment allocation');if(y.primaryMetric!=='final_attempt_rate'||!(y.mde>0&&y.mde<1)||!(y.alpha>0&&y.alpha<1)||!(y.power>0&&y.power<1)||!Number.isSafeInteger(y.minSamplePerVariant)||y.minSamplePerVariant<1||JSON.stringify(y.guardrails)!=='["tap_result_p95","unexpected_failure_rate","srm"]'||y.stoppingRule!=='FIXED_HORIZON'||!/^\d{2}:\d{2}$/.test(y.cellBucket))throw TypeError('invalid experiment statistics');for(const value of [y.experimentId,y.assignmentSaltVersion])if(!/^[a-z][a-z0-9_-]{2,63}$/i.test(value))throw TypeError('invalid experiment identifier');return y;}
export function parseExperimentContractCompositeV1(x:unknown){return parseExperimentContractStructureV1(x);}
export type RequirementGateResult='PASS'|'FAIL'|'BLOCKED';
export function emitRequirementGateStatus(requirementId:string,result:RequirementGateResult){if(!/^(?:(?:RULE|STATE|SEC|API|DATA|ECON|CONTENT|UX|QA|OBS|ENV|DOC)-\d{3}|RISK-\d{2})$/.test(requirementId))throw TypeError('invalid opaque requirement ID');return{metric:'release_requirement_gate_status' as const,requirementId,result,value:result==='PASS'?1 as const:0 as const};}
export function assignExperimentVariant(subject:string,c:ExperimentContractV1){if(!subject)throw TypeError('subject');const bucket=Number.parseInt(createHash('sha256').update(`${c.experimentId}\0${c.assignmentSaltVersion}\0${subject}`).digest('hex').slice(0,12),16)%10000;return bucket<c.allocationBasisPoints[0]?'CONTROL' as const:'TREATMENT' as const;}
export function evaluateSampleRatioMismatch(counts:{CONTROL:number;TREATMENT:number},c:ExperimentContractV1){const total=counts.CONTROL+counts.TREATMENT;if(!Number.isSafeInteger(total)||total<=0||counts.CONTROL<0||counts.TREATMENT<0)throw TypeError('counts');const a=total*c.allocationBasisPoints[0]/10000,b=total-a,chiSquare=(counts.CONTROL-a)**2/a+(counts.TREATMENT-b)**2/b;return{chiSquare,threshold:3.841458820694124,verdict:chiSquare<=3.841458820694124?'PASS' as const:'FAIL' as const};}

type LifecycleRow={stage:MatchStage;eventSeq:number;traceId:string;matchId:string;requestId:string;effectId:string|null};
export function validateLifecycleTrace(rows:readonly LifecycleRow[]){privacyScan(rows);const stages:MatchStage[]=['queue','handshake','preload','command','finish','reward'];if(rows.length!==stages.length||rows.some((r,i)=>r.stage!==stages[i]||r.eventSeq!==i+1)||new Set(rows.map(r=>r.eventSeq)).size!==rows.length)throw TypeError('trace must be unique and ordered');const first=rows[0]!;if(!/^trace_opaque_[a-z0-9]+$/i.test(first.traceId)||!/^match_opaque_[a-z0-9]+$/i.test(first.matchId)||rows.some(r=>r.traceId!==first.traceId||r.matchId!==first.matchId||!/^request_opaque_[a-z0-9]+$/i.test(r.requestId))||!/^effect_opaque_[a-z0-9]+$/i.test(rows[5]!.effectId??''))throw TypeError('invalid opaque correlation');return{traceId:first.traceId,matchId:first.matchId,stages};}
