import type { MatchCommand, MatchInitialStateV1, MatchStateV1, ReplayBundleV1 } from './match.js';
const requestUuid=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const matchUuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const safe=(n:unknown)=>Number.isSafeInteger(n)&&Number(n)>=0;
const exact=(x:Record<string,unknown>,allowed:string[])=>Object.keys(x).every(k=>allowed.includes(k));
export function parseMatchCommandV1(value:unknown):MatchCommand {
 if(!value||typeof value!=='object')throw Error('command must be an object');const x=value as Record<string,unknown>;
 const common=['source','commandId','matchId','commandSeq','receivedAtMs','payload'];
 if(typeof x.commandId!=='string'||!/^[\x21-\x7e]{1,512}$/.test(x.commandId)||typeof x.matchId!=='string'||!matchUuid.test(x.matchId)||!safe(x.commandSeq)||!safe(x.receivedAtMs)||!x.payload||typeof x.payload!=='object')throw Error('invalid command fields');
 if(x.source==='PLAYER') {if(!exact(x,[...common,'requestId','playerId','expectedRevision'])||typeof x.requestId!=='string'||!requestUuid.test(x.requestId)||typeof x.playerId!=='string'||!/^[\x21-\x7e]{1,128}$/.test(x.playerId)||!safe(x.expectedRevision))throw Error('invalid player command');}
 else if(x.source==='TIMER'){if(!exact(x,[...common,'timerId','dueAtMs'])||x.timerId!==x.commandId||!safe(x.dueAtMs)||Number(x.receivedAtMs)<Number(x.dueAtMs))throw Error('invalid timer command');}
 else if(x.source==='SYSTEM'){if(!exact(x,[...common,'systemCommandId'])||x.systemCommandId!==x.commandId)throw Error('invalid system command');}
 else throw Error('invalid source'); validatePayload(x.source,x.payload as Record<string,unknown>);return value as MatchCommand;
}
const stateKeys=['matchId','engineVersion','rulesetVersion','rulesetHash','contentRevisionId','contentHash','assetPolicyVersion','createdAtMs','assetLoadDeadlineMs','expectedAssets','phase','phaseEndsAtMs','startedAtMs','gameplayClosesAtMs','settlementCapAtMs','stateRevision','nextEventSeq','players','connections','objectives','activeMission','finalChallenge','meaningQuizzes','suddenDeath','randomSchedule','privateSolution','winnerPlayerId','endReason'];
export function parseMatchStateV1(value:unknown):MatchStateV1 {if(!value||typeof value!=='object'||!exact(value as Record<string,unknown>,stateKeys))throw Error('invalid match state');const s=value as MatchStateV1;if(typeof s.matchId!=='string'||!matchUuid.test(s.matchId)||!safe(s.createdAtMs)||!safe(s.assetLoadDeadlineMs)||!safe(s.stateRevision)||!safe(s.nextEventSeq)||!Array.isArray(s.players)||s.players.length!==2||s.players.some(p=>!exact(p as unknown as Record<string,unknown>,['playerId','assetLoadStatus','assetFailure','assetAttestation','score','wrongFinalAttempts','hintCredits','revealedHintIndexes','publicPattern','finalAnswerStatus','meaningCorrect','answerUntilMs','tapRateWindow'])))throw Error('invalid match state fields');return s;}
export function parseMatchInitialStateV1(value:unknown):MatchInitialStateV1 {const s=parseMatchStateV1(value);if(s.phase!=='WAITING_FOR_ASSETS'||s.stateRevision!==0||s.nextEventSeq!==1)throw Error('invalid initial state');return s as MatchInitialStateV1;}
export function parseReplayBundleV1(value:unknown):ReplayBundleV1 {if(!value||typeof value!=='object')throw Error('invalid replay bundle');const b=value as ReplayBundleV1;if(b.bundleVersion!==1)throw Error('invalid bundle version');parseMatchInitialStateV1(b.initialState);let seq=0,time=-1;for(const c of b.commands){parseMatchCommandV1(c);if(c.matchId!==b.initialState.matchId||c.commandSeq!==++seq)throw Error('invalid command sequence');const t=c.source==='TIMER'?c.dueAtMs:c.receivedAtMs;if(t<time)throw Error('effective time decreased');time=t;}return b;}
function validatePayload(source:unknown,p:Record<string,unknown>){if(typeof p.type!=='string')throw Error('payload type');const keys:Record<string,string[]>={READY:['type','contentRevisionId','contentHash','assetHashes','decodedDimensions'],REPORT_ASSET_LOAD_FAILURE:['type','assetHash','attempts'],TAP_IMAGE:['type','imageSide','x','y'],SUBMIT_FINAL_ANSWER:['type','answer'],SUBMIT_MEANING:['type','optionId'],USE_HINT:['type'],ASSET_LOAD_TIMEOUT:['type'],START_MATCH:['type'],START_WORD_HUNT:['type','missionId'],END_WORD_HUNT:['type','missionId'],UNLOCK_FINAL_CHALLENGE:['type'],START_FINAL_RUSH:['type'],CLOSE_INPUT:['type'],ANSWER_LOCK_EXPIRED:['type','playerId','wrongAttemptOrdinal'],MEANING_TIMEOUT:['type','playerId','quizOrdinal'],DISCONNECT_FORFEIT_TIMEOUT:['type','playerId','disconnectEpoch'],SUDDEN_DEATH_TIMEOUT:['type'],PLAYER_CONNECTION_CHANGED:['type','playerId','disconnectEpoch','status'],CANCEL_NO_CONTEST:['type','incidentId','reason']};const allowed=keys[p.type];if(!allowed||!exact(p,allowed))throw Error('payload branch invalid');const playerTypes=['READY','REPORT_ASSET_LOAD_FAILURE','TAP_IMAGE','SUBMIT_FINAL_ANSWER','SUBMIT_MEANING','USE_HINT'];const timerTypes=['ASSET_LOAD_TIMEOUT','START_MATCH','START_WORD_HUNT','END_WORD_HUNT','UNLOCK_FINAL_CHALLENGE','START_FINAL_RUSH','CLOSE_INPUT','ANSWER_LOCK_EXPIRED','MEANING_TIMEOUT','DISCONNECT_FORFEIT_TIMEOUT','SUDDEN_DEATH_TIMEOUT'];if(source==='PLAYER'&&!playerTypes.includes(p.type)||source==='TIMER'&&!timerTypes.includes(p.type)||source==='SYSTEM'&&p.type!=='PLAYER_CONNECTION_CHANGED'&&p.type!=='CANCEL_NO_CONTEST')throw Error('payload source mismatch');if(p.type==='TAP_IMAGE'&&(!['A','B'].includes(String(p.imageSide))||typeof p.x!=='number'||!Number.isFinite(p.x)||p.x<0||p.x>1||typeof p.y!=='number'||!Number.isFinite(p.y)||p.y<0||p.y>1))throw Error('tap invalid');for(const k of ['wrongAttemptOrdinal','quizOrdinal','disconnectEpoch'])if(k in p&&!safe(p[k]))throw Error(`${k} invalid`);}
