import{expect,it}from'vitest';import{MemoryCommandReceiptStore}from'./idempotency.js';import{MemoryRestMutationReceiptStore}from'./rest-idempotency.js';import{decideDelivery}from'./delivery-policy.js';import{resolveAuthenticatedParticipant}from'./socket.schema.js';
it('bounded-waits and reclaims expired Socket owners around durable decisions',async()=>{const s=new MemoryCommandReceiptStore(),key={matchId:'m',playerId:'p',requestId:'r'};expect((await s.claimOrReplay(key,'h','old',100,0)).kind).toBe('OWNER');expect(await s.waitForCompletion(key,1)).toBeNull();expect((await s.claimOrReplay(key,'h','new',200,101)).kind).toBe('OWNER');s.recordCommandDecision(key,'h',{protocolVersion:1,requestId:'r',accepted:false,reason:'RATE_LIMITED',stateRevision:1,lastEventSeq:0,snapshotRequired:false},null);expect((await s.claimOrReplay(key,'h','recovery',300,201)).kind).toBe('REPLAY');expect((await Promise.all(Array.from({length:20},(_,i)=>s.claimOrReplay(key,'h',`x${i}`,400,202)))).every(x=>x.kind==='REPLAY')).toBe(true)});
it('passes 20-way REST replay/conflict/two-subject isolation in all five scopes',async()=>{for(const scope of ['QUEUE_CREATE_V1','QUEUE_CANCEL_V1','FRIEND_ROOM_CREATE_V1','FRIEND_ROOM_JOIN_V1','FRIEND_ROOM_LEAVE_V1'] as const){const s=new MemoryRestMutationReceiptStore(),key={apiSubjectKey:'a',scope,idempotencyKey:'123e4567-e89b-42d3-a456-426614174000'};const c=await Promise.all(Array.from({length:20},(_,i)=>s.claimOrReplay(key,'h',`o${i}`,100)));expect(c.filter(x=>x.kind==='OWNER')).toHaveLength(1);await s.complete(key,(c.find(x=>x.kind==='OWNER')as{ownerToken:string}).ownerToken,{responseStatus:200,responseBody:{ok:true}});expect((await Promise.all(Array.from({length:20},(_,i)=>s.claimOrReplay(key,'h',`r${i}`,200)))).every(x=>x.kind==='REPLAY')).toBe(true);expect((await s.claimOrReplay(key,'x','c',200)).kind).toBe('CONFLICT');expect((await s.claimOrReplay({...key,apiSubjectKey:'b'},'x','b',200)).kind).toBe('OWNER')}});
it('maps authenticated subjects privately and rejects subject-shaped request IDs',()=>{const subject='123e4567-e89b-42d3-a456-426614174000',matchId='123e4567-e89b-12d3-a456-426614174000',members=[{authSubject:subject,matchId,participantKey:'opaque-player'}];expect(resolveAuthenticatedParticipant(subject,members,matchId,'223e4567-e89b-42d3-a456-426614174000')).toBe('opaque-player');expect(()=>resolveAuthenticatedParticipant(subject,members,matchId,subject)).toThrow('INVALID_REQUEST_ID');expect(()=>resolveAuthenticatedParticipant('other',[],matchId,'223e4567-e89b-42d3-a456-426614174000')).toThrow('FORBIDDEN')});
it('rejects legacy aggregate replay metadata that cannot prove the authoritative suffix',()=>{
 const cursor={lastEventSeq:3,stateRevision:3};
 expect(decideDelivery(cursor,{kind:'REPLAY',fromEventSeq:4,toEventSeq:6,firstRevision:4,lastRevision:6,available:true})).toBe('REPLACE_SNAPSHOT');
 expect(decideDelivery(cursor,{kind:'REPLAY',fromEventSeq:5,toEventSeq:6,firstRevision:5,lastRevision:6,available:true})).toBe('REPLACE_SNAPSHOT');
 expect(decideDelivery(cursor,{kind:'REPLAY',fromEventSeq:4,toEventSeq:6,firstRevision:2,lastRevision:6,available:true})).toBe('REPLACE_SNAPSHOT');
});
