import type { ExpectedMatchAssetV1, MatchEndReason, MatchPhase, PlayerCommandPayload } from './match.js';
import type { HintKind, PublicHintRegionV1 } from './content.js';
type PlayerInputState={enabled:boolean;reason:string|null};
export type ClientCommandEnvelope={protocolVersion:1;requestId:string;matchId:string;expectedRevision:number;clientSeq:number;payload:PlayerCommandPayload};
export type CommandRejectReason='REVISION_AHEAD'|'ALREADY_READY'|'ALREADY_CLAIMED'|'INPUT_LOCKED'|'NO_HINT_CREDIT'|'INVALID_HINT_LADDER'|'HINT_ORDINAL_CONFLICT'|'NO_HINT_REMAINING'|'RATE_LIMITED'|'MATCH_INPUT_CLOSED'|'NOT_A_PARTICIPANT'|'INVALID_PAYLOAD'|'IDEMPOTENCY_CONFLICT'|'UPDATE_REQUIRED';
export type AcceptedCommandAck={protocolVersion:1;requestId:string;accepted:true;stateRevision:number;lastEventSeq:number;snapshotRequired:boolean};
export type RejectedCommandAck={protocolVersion:1;requestId:string;accepted:false;reason:CommandRejectReason;stateRevision:number;lastEventSeq:number;snapshotRequired:boolean};
export type CommandAck=AcceptedCommandAck|RejectedCommandAck;
export type CompatibilityHelloV1={protocolVersion:1;supportedEngineVersions:readonly string[];supportedRulesetVersions:readonly string[]};
export type PinnedCompatibilityV1={protocolVersion:1;engineVersion:string;rulesetVersion:'1.0.0';rulesetHash:string;contentRevisionId:string;contentHash:string};
export type MatchmakingNotification={protocolVersion:1;type:'match_found';notificationId:string;ticketId:string;matchId:string;preloadDeadlineMs:number;preload:{contentRevisionId:string;contentHash:string;assetPolicyVersion:'1.0.0';assets:readonly[ExpectedMatchAssetV1,ExpectedMatchAssetV1]};compatibility:PinnedCompatibilityV1};
export type ServerEventPayloadMap={state_advanced:{redacted:true};asset_ready_changed:{playerId:string;readyCount:1|2;countdownEndsAtMs:number|null};match_started:{startedAtMs:number};tap_result:{requestId:string;applied:true;hit:boolean;objectiveId:string|null};difference_claimed:{objectiveId:string;ownerPlayerId:string;displayCircles:{imageA:{cx:number;cy:number;r:number};imageB:{cx:number;cy:number;r:number}}};word_hunt_started:{missionId:string;kind:'NORMAL'|'SPECIAL';publicPrompt:string;startedAtMs:number;endsAtMs:number};word_hunt_won:{missionId:string;playerId:string};word_hunt_ended:{missionId:string;reason:'TIMEOUT'};score_changed:{playerId:string;delta:number;absoluteScore:number};final_rush_started:{startedAtMs:number};final_challenge_unlocked:{unlockedAtMs:number;source:'TIME'|'DIFFERENCE'|'WORD_HUNT';publicPattern:string};hint_revealed:{playerId:string;hintIndex:number;publicPattern:string};hint_step_revealed:{requestId:string;ordinal:1|2|3|4|5;kind:HintKind;localizedText:string;publicPattern:string;publicRegion:PublicHintRegionV1|null;rankedPenaltyUnits:0|1;cumulativeRankedPenaltyUnits:number;coachChargesRemaining:number|null};hint_credit_changed:{playerId:string;delta:number;absoluteCredits:number};answer_lock_changed:{playerId:string;answerUntilMs:number|null;reason:'WRONG_ANSWER'|'FINAL_RUSH_WRONG_ANSWER'|'EXPIRED'};meaning_quiz_started:{playerId:string;quizOrdinal:number;prompt:string;options:ReadonlyArray<{id:string;label:string}>;endsAtMs:number};sudden_death_started:{objectiveId:string;endsAtMs:number;displayCircles:{imageA:{cx:number;cy:number;r:number};imageB:{cx:number;cy:number;r:number}}};input_closed:{closedAtMs:number;settlementCapAtMs:number};connection_changed:{playerId:string;status:'CONNECTED'|'DISCONNECTED';disconnectEpoch:number;forfeitAtMs:number|null};match_finished:{winnerPlayerId:string|null;endReason:MatchEndReason}};
type Base={protocolVersion:1;eventId:string;matchId:string;eventSeq:number;stateRevision:number;occurredAtMs:number;phase:MatchPhase};
export type ServerEventEnvelope={[K in keyof ServerEventPayloadMap]:Base&{type:K;payload:ServerEventPayloadMap[K]}}[keyof ServerEventPayloadMap];
type LearningHintSnapshotCurrentBase={localizedText:string;publicPattern:string|null};
type LearningHintSnapshotCurrentV1=
 |(LearningHintSnapshotCurrentBase&{ordinal:1|2|3|4;kind:'VISUAL_REGION';publicRegion:Extract<PublicHintRegionV1,{kind:'REGION'}>})
 |(LearningHintSnapshotCurrentBase&{ordinal:5;kind:'VISUAL_REGION';publicRegion:Extract<PublicHintRegionV1,{kind:'EXACT_CIRCLE'}>})
 |(LearningHintSnapshotCurrentBase&{ordinal:1|2|3|4|5;kind:Exclude<HintKind,'VISUAL_REGION'>;publicRegion:null});
export type LearningHintSnapshotV1={mode:'CASUAL'|'RANKED';nextExpectedOrdinal:1|2|3|4|5|6;revealedOrdinals:ReadonlyArray<1|2|3|4|5>;revealedCount:number;coachChargesRemaining:number|null;cumulativeRankedPenaltyUnits:number;current:LearningHintSnapshotCurrentV1|null};
export type MatchSnapshotV1={protocolVersion:1;matchId:string;viewerPlayerId:string;engineVersion:string;rulesetVersion:'1.0.0';rulesetHash:string;contentRevisionId:string;contentHash:string;serverNowMs:number;phase:MatchPhase;phaseEndsAtMs:number|null;stateRevision:number;lastEventSeq:number;preload:{assetLoadDeadlineMs:number;assetPolicyVersion:'1.0.0';assets:readonly[ExpectedMatchAssetV1,ExpectedMatchAssetV1];players:ReadonlyArray<{playerId:string;status:'PENDING'|'READY'|'FAILED'}>};viewerInput:PlayerInputState;connections:ReadonlyArray<{playerId:string;status:'CONNECTED'|'DISCONNECTED';disconnectEpoch:number;forfeitAtMs:number|null}>;scores:ReadonlyArray<{playerId:string;absoluteScore:number}>;claimed:ReadonlyArray<{objectiveId:string;ownerPlayerId:string;displayCircles:{imageA:{cx:number;cy:number;r:number};imageB:{cx:number;cy:number;r:number}}}>;mission:{id:string;kind:'NORMAL'|'SPECIAL';publicPrompt:string;startedAtMs:number;endsAtMs:number}|null;locks:ReadonlyArray<{playerId:string;answerUntilMs:number|null}>;finalChallenge:{unlocked:boolean;unlockedAtMs:number|null;viewer:{wrongAttempts:number;maxWrongAttempts:number;hintCredits:number;revealedHintCount:number;publicPattern:string|null;learningHints?:LearningHintSnapshotV1|null}};meaningQuiz:{quizOrdinal:number;prompt:string;options:ReadonlyArray<{id:string;label:string}>;remainingMs:number}|null;suddenDeath:{objectiveId:string;endsAtMs:number;displayCircles:{imageA:{cx:number;cy:number;r:number};imageB:{cx:number;cy:number;r:number}}}|null;result:{winnerPlayerId:string|null;endReason:MatchEndReason}|null};
