import { describe, expect, it } from 'vitest';
import { CONTENT_CARDINALITY_V1, privateGameSolutionSchema } from '../../packages/contracts/src/content.js';
import ruleset from '../../config/ruleset.v1.json' with { type: 'json' };
import { checkRulesetProjection } from '../../tools/write-ruleset-projections.js';

describe('ruleset content projection parity', () => {
  it('derives contract cardinalities from RulesetV1', () => {
    expect(CONTENT_CARDINALITY_V1).toEqual(ruleset.content);
    expect(privateGameSolutionSchema.properties.differences).toMatchObject({ minItems: 5, maxItems: 20 });
    expect(privateGameSolutionSchema.properties.wordHunts).toMatchObject({ minItems: 3, maxItems: 3 });
  });

  it('mechanically checks generated bytes and publishing SQL semantics', async () => {
    await expect(checkRulesetProjection()).resolves.toBeUndefined();
  });
});
