import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {describe,expect,it}from'vitest';
import {checkNormativeNumbers,checkRepositoryTraceability,discoverNormativeRequirements,validateGateScripts}from'../../tools/check-docs-lib.js';
import {spawnSync}from'node:child_process';

describe('normative traceability',()=>{
 it('discovers bullets, ordered requirements and normative prose with stable semantics',()=>{const text='# API\n## Mutations\n- Must retry. <!-- REQ: API-002 -->\n1. Tie break. <!-- REQ: API-003 -->\nServer authority is final. <!-- REQ: API-004 -->';const rows=discoverNormativeRequirements('09_API.md',text);expect(rows.map(x=>x.text)).toEqual(['Must retry.','Tie break.','Server authority is final.']);expect(rows.every(x=>x.fingerprint.match(/^[a-f0-9]{64}$/))).toBe(true);});
 it('discovers normative blockquotes and table rows',()=>{const text='# Rules\n> Ruleset is authoritative. <!-- REQ: RULE-001 -->\n| action | score |\n|---|---|\n| final | +25 | <!-- REQ: RULE-002 -->';expect(discoverNormativeRequirements('02_RULES.md',text).map(x=>x.text)).toEqual(['Ruleset is authoritative.','| final | +25 |']);});
 it('fails unmarked normative bullets and source/fingerprint drift against a copied real registry',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'trace-real-'));for(const file of ['README.md','09_API_AND_SOCKET_EVENTS.md'])fs.copyFileSync(path.resolve(file),path.join(tmp,file));fs.mkdirSync(path.join(tmp,'docs'));fs.copyFileSync(path.resolve('docs/requirements-registry.v1.json'),path.join(tmp,'docs/requirements-registry.v1.json'));expect(checkRepositoryTraceability(tmp).unmarked).toEqual([]);fs.appendFileSync(path.join(tmp,'09_API_AND_SOCKET_EVENTS.md'),'\n- The server MUST reject drift.\n');expect(checkRepositoryTraceability(tmp).unmarked.length).toBe(1);});
 it('detects broad normative numeric drift from SSOT projections',()=>{const files=Object.fromEntries(['07_REALTIME_SERVER_SPEC.md','11_TEST_AND_BALANCE_PLAN.md'].map(f=>[f,fs.readFileSync(f,'utf8')]));expect(checkNormativeNumbers(files)).toEqual([]);expect(checkNormativeNumbers({...files,'07_REALTIME_SERVER_SPEC.md':files['07_REALTIME_SERVER_SPEC.md']!.replace('250ms','251ms')})).toContain('07_REALTIME_SERVER_SPEC.md:250ms');});
 it('parses exact package gate composition rather than accepting substrings',()=>{const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));expect(validateGateScripts(pkg.scripts)).toEqual([]);expect(validateGateScripts({...pkg.scripts,check:pkg.scripts.check.replace('corepack pnpm docs:check','echo corepack pnpm docs:check')})).not.toEqual([]);});
 it('fails semantic mapping mutations and ordered/prose omissions in real artifacts',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'trace-map-'));for(const f of ['README.md',...fs.readdirSync('.').filter(x=>/^\d{2}_.+\.md$/.test(x))])fs.copyFileSync(f,path.join(tmp,f));fs.mkdirSync(path.join(tmp,'docs'));const registry=JSON.parse(fs.readFileSync('docs/requirements-registry.v1.json','utf8'));registry.requirements[0].metric='';fs.writeFileSync(path.join(tmp,'docs/requirements-registry.v1.json'),JSON.stringify(registry));expect(checkRepositoryTraceability(tmp).semantic).toContain(registry.requirements[0].id);});
 it('rejects existing but irrelevant schema/test/metric linkage and gate duplicates/additions/order',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'trace-link-'));for(const f of ['README.md',...fs.readdirSync('.').filter(x=>/^\d{2}_.+\.md$/.test(x))])fs.copyFileSync(f,path.join(tmp,f));fs.mkdirSync(path.join(tmp,'docs'));const registry=JSON.parse(fs.readFileSync('docs/requirements-registry.v1.json','utf8'));registry.requirements[0].schema=registry.requirements.at(-1).schema;registry.requirements[0].test=registry.requirements.at(-1).test;registry.requirements[0].metric='unrelated_metric';fs.writeFileSync(path.join(tmp,'docs/requirements-registry.v1.json'),JSON.stringify(registry));expect(checkRepositoryTraceability(tmp).semantic).toContain(registry.requirements[0].id);const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));expect(validateGateScripts({...pkg.scripts,check:`${pkg.scripts.check} && corepack pnpm lint`})).not.toEqual([]);expect(validateGateScripts({...pkg.scripts,check:pkg.scripts.check.replace('corepack pnpm lint && corepack pnpm typecheck','corepack pnpm typecheck && corepack pnpm lint')})).not.toEqual([]);});
 it('has executable exact-ID evidence and honest non-operational metric kinds',()=>{const registry=JSON.parse(fs.readFileSync('docs/requirements-registry.v1.json','utf8'));const coverage=JSON.parse(fs.readFileSync('config/requirement-evidence.v1.json','utf8'));expect(new Set(coverage.entries.map((x:{id:string})=>x.id))).toEqual(new Set(registry.requirements.map((x:{id:string})=>x.id)));expect(coverage.entries.every((x:{id:string;oracle:string;evidenceKind:string;metric:string|null})=>x.oracle.includes(x.id)&&x.evidenceKind&&(x.metric===null||fs.readFileSync('docs/analytics/metric-dictionary.md','utf8').includes(x.metric)))).toBe(true);});
 it('fails a stale generated release report',()=>{const file='docs/testing/reports/economy-draw-v1-seed-20260719.json',original=fs.readFileSync(file,'utf8');try{fs.writeFileSync(file,original.replace('100000','99999'));const result=spawnSync('D:\\touchcatch\\node_modules\\.bin\\tsx.CMD',['tools/write-release-reports.ts','--check'],{cwd:process.cwd(),encoding:'utf8',shell:true});expect(result.status).not.toBe(0);expect(result.stderr).toContain('stale report');}finally{fs.writeFileSync(file,original);}});
 it('recurring docs checker executes broad numeric approvals, inventory and relative-link checks',()=>{const run=()=>spawnSync(process.execPath,['tools/check-docs.mjs'],{cwd:process.cwd(),encoding:'utf8'});for(const [file,mutate,signal]of[['02_CORE_RULES_AND_BALANCE.md',(x:string)=>x.replace('정답 +25','정답 +26'),'numericApprovalDrift'],['README.md',(x:string)=>x.replace('(01_GAME_DESIGN_OVERVIEW.md)','(missing.md)'),'inventoryDrift']]as const){const original=fs.readFileSync(file,'utf8');try{fs.writeFileSync(file,mutate(original));const result=run();expect(result.status).not.toBe(0);expect(`${result.stdout}${result.stderr}`).toContain(signal);}finally{fs.writeFileSync(file,original);}}});
});
