import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {describe,expect,it}from'vitest';
import {checkNormativeNumbers,checkRepositoryTraceability,discoverNormativeRequirements,validateGateScripts}from'../../tools/check-docs-lib.js';
import {spawnSync}from'node:child_process';

describe('normative traceability',()=>{
 it('discovers bullets, ordered requirements and normative prose with stable semantics',()=>{const text='# API\n## Mutations\n- Must retry. <!-- REQ: API-002 -->\n1. Tie break. <!-- REQ: API-003 -->\nServer authority is final. <!-- REQ: API-004 -->';const rows=discoverNormativeRequirements('09_API.md',text);expect(rows.map(x=>x.text)).toEqual(['Must retry.','Tie break.','Server authority is final.']);expect(rows.every(x=>x.fingerprint.match(/^[a-f0-9]{64}$/))).toBe(true);});
 it('fails unmarked normative bullets and source/fingerprint drift against a copied real registry',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'trace-real-'));for(const file of ['README.md','09_API_AND_SOCKET_EVENTS.md'])fs.copyFileSync(path.resolve(file),path.join(tmp,file));fs.mkdirSync(path.join(tmp,'docs'));fs.copyFileSync(path.resolve('docs/requirements-registry.v1.json'),path.join(tmp,'docs/requirements-registry.v1.json'));expect(checkRepositoryTraceability(tmp).unmarked).toEqual([]);fs.appendFileSync(path.join(tmp,'09_API_AND_SOCKET_EVENTS.md'),'\n- The server MUST reject drift.\n');expect(checkRepositoryTraceability(tmp).unmarked.length).toBe(1);});
 it('detects broad normative numeric drift from SSOT projections',()=>{const files=Object.fromEntries(['07_REALTIME_SERVER_SPEC.md','11_TEST_AND_BALANCE_PLAN.md'].map(f=>[f,fs.readFileSync(f,'utf8')]));expect(checkNormativeNumbers(files)).toEqual([]);expect(checkNormativeNumbers({...files,'07_REALTIME_SERVER_SPEC.md':files['07_REALTIME_SERVER_SPEC.md']!.replace('250ms','251ms')})).toContain('07_REALTIME_SERVER_SPEC.md:250ms');});
 it('parses exact package gate composition rather than accepting substrings',()=>{const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));expect(validateGateScripts(pkg.scripts)).toEqual([]);expect(validateGateScripts({...pkg.scripts,check:pkg.scripts.check.replace('corepack pnpm docs:check','echo corepack pnpm docs:check')})).toContain('check:docs:check');});
 it('fails semantic mapping mutations and ordered/prose omissions in real artifacts',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'trace-map-'));for(const f of ['README.md',...fs.readdirSync('.').filter(x=>/^\d{2}_.+\.md$/.test(x))])fs.copyFileSync(f,path.join(tmp,f));fs.mkdirSync(path.join(tmp,'docs'));const registry=JSON.parse(fs.readFileSync('docs/requirements-registry.v1.json','utf8'));registry.requirements[0].metric='';fs.writeFileSync(path.join(tmp,'docs/requirements-registry.v1.json'),JSON.stringify(registry));expect(checkRepositoryTraceability(tmp).semantic).toContain(registry.requirements[0].id);});
 it('fails a stale generated release report',()=>{const file='docs/testing/reports/economy-draw-v1-seed-20260719.json',original=fs.readFileSync(file,'utf8');try{fs.writeFileSync(file,original.replace('100000','99999'));const result=spawnSync('D:\\touchcatch\\node_modules\\.bin\\tsx.CMD',['tools/write-release-reports.ts','--check'],{cwd:process.cwd(),encoding:'utf8',shell:true});expect(result.status).not.toBe(0);expect(result.stderr).toContain('stale report');}finally{fs.writeFileSync(file,original);}});
});
