// Generated by tools/content/generate-playable-registry.ts. Do not edit.
import { buildDemoEntry, type Bundle } from './data';

declare const require: (path: string) => number;

const bundle1 = require('../../../../content/learning/drafts/en-resilience.json') as unknown as Bundle;
const bundle2 = require('../../../../content/learning/drafts/en-dilemma.json') as unknown as Bundle;
const bundle3 = require('../../../../content/learning/drafts/en-sustainability.json') as unknown as Bundle;

// Device-demo registry: bundles and assets are packaged locally; no private solution crosses a network boundary.
export const learningDemoEntries = [
  buildDemoEntry('ENGLISH', bundle1, { imageA: require('../../../../content/learning/source/en-resilience-a.png'), imageB: require('../../../../content/learning/source/en-resilience-b.png') }, { width: 1536, height: 1024 }),
  buildDemoEntry('ENGLISH', bundle2, { imageA: require('../../../../content/learning/source/en-dilemma-a.png'), imageB: require('../../../../content/learning/source/en-dilemma-b.png') }, { width: 1536, height: 1024 }),
  buildDemoEntry('ENGLISH', bundle3, { imageA: require('../../../../content/learning/source/en-sustainability-a.png'), imageB: require('../../../../content/learning/source/en-sustainability-b.png') }, { width: 1536, height: 1024 }),
] as const;
