import type {MatchSnapshotV1} from '../../../../packages/contracts/src/socket.js';
import {matchSnapshotV1Schema} from '../../../../packages/contracts/src/socket.schema.js';
import theme from '../../../../config/ui-theme.v1.json' with {type:'json'};
import {useEffect,useMemo,useRef,useState} from 'react';
import {AccessibilityInfo,findNodeHandle,Image,Modal,Pressable,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Gesture,GestureDetector} from 'react-native-gesture-handler';
import {adaptMatchSnapshot,applyGestureDelta,assertPublicUiValue,createMeaningIntent,createTapIntent,inverseContentPoint,layoutContainedPair,shouldCancelSyntheticTap,type BattleExternalState,type Transform} from './battle-shell.js';

type Intent=NonNullable<ReturnType<typeof createTapIntent>>|NonNullable<ReturnType<typeof createMeaningIntent>>;
type Props={snapshot:MatchSnapshotV1;pendingIntentId:string|null;connection:BattleExternalState['connection'];lastRejection?:string|null;onIntent:(intent:Intent)=>void};
const playable=new Set(['PLAYING','FINAL_RUSH','SUDDEN_DEATH']);

export function BattleScreen({snapshot,pendingIntentId,connection,lastRejection=null,onIntent}:Props){
 const admitted=useMemo(()=>{assertPublicUiValue(snapshot);return matchSnapshotV1Schema.parse(snapshot)},[snapshot]);
 const vm=adaptMatchSnapshot(admitted,{pendingIntentId,connection});
 const disabled=!admitted.viewerInput.enabled||connection!=='CONNECTED'||pendingIntentId!==null||admitted.result!==null||!playable.has(admitted.phase);
 const [available,setAvailable]=useState({width:theme.viewport.baseline[0]??390,height:theme.viewport.baseline[1]??844}); const [announcement,setAnnouncement]=useState(''); const [transform,setTransform]=useState<Transform>({scale:1,tx:0,ty:0});
 const modalFocus=useRef<unknown>(null); const boardFocus=useRef<unknown>(null); const base=useRef<Transform>(transform); const motion=useRef({translationPx:0,scaleDelta:0});
 const pair=layoutContainedPair(available,{width:vm.assets[0].width,height:vm.assets[0].height},theme.space.baseGrid);
 useEffect(()=>setAnnouncement(`Score ${vm.scores.map(x=>x.absoluteScore).join(' to ')}. ${connection}. ${admitted.phase}.${lastRejection?` Rejected: ${lastRejection}.`:''}`),[vm.scores,connection,admitted.phase,lastRejection]);
 useEffect(()=>{const handle=findNodeHandle(vm.meaningQuiz?modalFocus.current:boardFocus.current);if(handle!==null)AccessibilityInfo.setAccessibilityFocus(handle)},[vm.meaningQuiz]);
 const tapFor=(side:'A'|'B')=>Gesture.Tap().enabled(!disabled).onEnd(({x,y}:{x:number;y:number})=>{if(shouldCancelSyntheticTap(motion.current,{translationPx:theme.space.baseGrid,scaleDelta:.05}))return;const point=inverseContentPoint({x,y},side==='A'?pair.a.content:pair.b.content,transform,admitted.phase==='FINAL_RUSH'?'FINAL_RUSH':undefined);const intent=createTapIntent(vm,{side,...point});if(intent)onIntent(intent)});
 const pan=Gesture.Pan().runOnJS(true).onBegin(()=>{base.current=transform;motion.current={translationPx:0,scaleDelta:0}}).onUpdate((e:{translationX:number;translationY:number})=>{motion.current.translationPx=Math.hypot(e.translationX,e.translationY);setTransform(applyGestureDelta(base.current,{scale:1,tx:e.translationX,ty:e.translationY},pair.a.content,{min:1,max:4}))});
 const pinch=Gesture.Pinch().runOnJS(true).onBegin(()=>{base.current=transform;motion.current={translationPx:0,scaleDelta:0}}).onUpdate((e:{scale:number})=>{motion.current.scaleDelta=Math.abs(e.scale-1);setTransform(applyGestureDelta(base.current,{scale:e.scale,tx:0,ty:0},pair.a.content,{min:1,max:4}))});
 const board=(side:'A'|'B',index:0|1)=><GestureDetector gesture={Gesture.Exclusive(Gesture.Simultaneous(pan,pinch),tapFor(side))}><Pressable ref={side==='A'?boardFocus:undefined} accessibilityRole="imagebutton" accessibilityLabel={`Difference image ${side}`} accessibilityHint="Double tap a visible difference" accessibilityState={{disabled,busy:pendingIntentId!==null}} disabled={disabled} style={{minWidth:theme.touchTarget.androidDp,minHeight:theme.touchTarget.androidDp,overflow:'hidden',height:pair.a.viewport.height,backgroundColor:theme.color.background}}><Image source={{uri:vm.assets[index].url}} accessibilityIgnoresInvertColors resizeMode="contain" style={{position:'absolute',left:pair.a.content.x,top:pair.a.content.y,width:pair.a.content.width,height:pair.a.content.height,transform:[{scale:transform.scale},{translateX:transform.tx},{translateY:transform.ty}]}}/>{vm.claimed.map(c=>{const circle=side==='A'?c.displayCircles.imageA:c.displayCircles.imageB;return <View key={`${side}-${c.objectiveId}`} accessible={false} pointerEvents="none" style={{position:'absolute',left:pair.a.content.x+(circle.cx-circle.r)*pair.a.content.width,top:pair.a.content.y+(circle.cy-circle.r)*pair.a.content.height,width:circle.r*2*pair.a.content.width,aspectRatio:1,borderRadius:theme.radius.pill,borderWidth:theme.depth.card.borderWidth*3,borderColor:theme.color.reward,transform:[{scale:transform.scale},{translateX:transform.tx},{translateY:transform.ty}]}}/>})}</Pressable></GestureDetector>;
 return <SafeAreaView accessibilityLabel="Battle" style={{flex:1,backgroundColor:theme.color.background}}><View onLayout={({nativeEvent})=>setAvailable({width:nativeEvent.layout.width,height:nativeEvent.layout.height})} style={{flex:1,gap:theme.space.baseGrid}}><View accessibilityRole="summary" accessibilityLiveRegion="polite"><Text allowFontScaling maxFontSizeMultiplier={2} style={{color:theme.color.ink,fontSize:theme.typography.body.lg.fontSize,lineHeight:theme.typography.body.lg.lineHeight}}>{announcement}</Text><Text allowFontScaling maxFontSizeMultiplier={2}>{pendingIntentId?'Submitting':admitted.phase}</Text></View>{board('A',0)}{board('B',1)}<Modal visible={vm.meaningQuiz!==null} accessibilityViewIsModal onRequestClose={()=>{}} transparent><View ref={modalFocus} accessible accessibilityRole="alert" accessibilityLabel="Meaning quiz" accessibilityLiveRegion="polite" style={{flex:1,justifyContent:'center',padding:theme.space.screenX,backgroundColor:theme.color.overlay}}><Text accessibilityRole="header" allowFontScaling maxFontSizeMultiplier={2} style={{fontSize:theme.typography.heading.md.fontSize,lineHeight:theme.typography.heading.md.lineHeight,color:theme.color.surface}}>{vm.meaningQuiz?.prompt}</Text>{vm.meaningQuiz?.options.map(option=><Pressable key={option.id} disabled={disabled} accessibilityRole="button" accessibilityLabel={option.label} accessibilityHint="Submit this meaning" accessibilityState={{disabled,busy:pendingIntentId!==null}} onPress={()=>{const intent=createMeaningIntent(vm,option.id);if(intent)onIntent(intent)}} style={{minWidth:theme.touchTarget.androidDp,minHeight:theme.touchTarget.androidDp,padding:theme.space.baseGrid,backgroundColor:theme.color.surface}}><Text allowFontScaling maxFontSizeMultiplier={2} style={{color:theme.color.ink}}>{option.label}</Text></Pressable>)}</View></Modal></View></SafeAreaView>;
}
