import React from 'react';import {act,create} from 'react-test-renderer';import {describe,expect,it,vi} from 'vitest';
(globalThis as typeof globalThis & {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
const gestureCallbacks:Array<{kind:string;begin?:()=>void;update?:(x:any)=>void;end?:(x:any)=>void}>=[];
// `Keyboard` is here because the development preview mounts LearningDemoScreen, which
// subscribes to keyboard events to keep its answer bar clear of the on-screen keyboard.
vi.mock('react-native',()=>({AccessibilityInfo:{setAccessibilityFocus:vi.fn()},Animated:{View:'Animated.View',Value:class{setValue(){}interpolate(){return 0;}},timing:()=>({start:(done?:()=>void)=>done?.()})},findNodeHandle:()=>1,Image:'Image',Keyboard:{addListener:()=>({remove:()=>{}})},Modal:'Modal',Platform:{OS:'ios'},Pressable:'Pressable',ScrollView:'ScrollView',Text:'Text',TextInput:'TextInput',View:'View'}));
vi.mock('react-native-safe-area-context',()=>({SafeAreaView:'SafeAreaView'}));
vi.mock('../learning-demo/registry.js',()=>({learningDemoEntries:[{key:'demo',category:'ENGLISH',preferredInputSurface:'FREE_TEXT',assistPattern:'SPELLING',title:'resilience',imageA:1,imageB:2,differences:[{id:'d',imageA:{cx:.5,cy:.5,r:.1},imageB:{cx:.5,cy:.5,r:.1}}],prompt:'Meaning?',options:[{id:'right',label:'Recovery'}],correctOptionId:'right'}]}));
vi.mock('react-native-gesture-handler',()=>{const gesture=(kind:string)=>{const callbacks:{kind:string;begin?:()=>void;update?:(x:any)=>void;end?:(x:any)=>void}={kind};if(gestureCallbacks.filter(x=>x.kind===kind).length<2)gestureCallbacks.push(callbacks);const api:any={enabled:()=>api,onEnd:(x:any)=>{callbacks.end=x;return api},runOnJS:()=>api,onBegin:(x:any)=>{callbacks.begin=x;return api},onUpdate:(x:any)=>{callbacks.update=x;return api}};return api};return{Gesture:{Tap:()=>gesture('tap'),Pan:()=>gesture('pan'),Pinch:()=>gesture('pinch'),Exclusive:(...x:unknown[])=>x,Simultaneous:(...x:unknown[])=>x},GestureDetector:'GestureDetector'}});
import fixture from '../../../../tests/fixtures/public-match-snapshot.json' with {type:'json'};import {matchSnapshotV1Schema} from '../../../../packages/contracts/src/socket.schema.js';import {BattleScreen} from './BattleScreen.js';

describe('native BattleScreen rendering',()=>{
 it('admits and renders the development preview without crashing',async()=>{const {LearningDemoHome}=await import('../learning-demo/preview-home.js');const entries=[{key:'demo',category:'ENGLISH' as const,preferredInputSurface:'FREE_TEXT' as const,assistPattern:'SPELLING' as const,title:'resilience',imageA:1,imageB:2,differences:[{id:'d',imageA:{cx:.5,cy:.5,r:.1},imageB:{cx:.5,cy:.5,r:.1}}],prompt:'Meaning?',options:[{id:'right',label:'Recovery'}],correctOptionId:'right'}];let tree:any;await act(async()=>{tree=create(<LearningDemoHome entries={entries}/>)});expect(tree.root.findAllByProps({accessibilityRole:'imagebutton'})).toHaveLength(2)});
 it('renders the admitted wire fixture with tokenized native accessibility semantics',()=>{let tree:any;act(()=>{tree=create(<BattleScreen snapshot={matchSnapshotV1Schema.parse(fixture)} pendingIntentId={null} connection="CONNECTED" onIntent={()=>{}}/>)});const root=tree.root;expect(root.findByType('SafeAreaView').props.style.backgroundColor).toBe('#F5FAFF');expect(root.findAllByProps({accessibilityRole:'imagebutton'})).toHaveLength(2);expect(root.findAllByProps({accessibilityLiveRegion:'polite'}).length).toBeGreaterThan(0);expect(root.findAllByType('Text').every((x:any)=>x.props.maxFontSizeMultiplier===2)).toBe(true)});
 it('renders disabled and modal states with trap, blocked back, 200% text and focus restoration target',()=>{const snapshot={...fixture,meaningQuiz:{quizOrdinal:1,prompt:'Choose',options:[{id:'a',label:'A'},{id:'b',label:'B'}],remainingMs:100}};let tree:any;act(()=>{tree=create(<BattleScreen snapshot={matchSnapshotV1Schema.parse(snapshot)} pendingIntentId="pending" connection="RECONNECTING" onIntent={()=>{}}/>)});const root=tree.root;expect(root.findByType('Modal').props).toMatchObject({visible:true,accessibilityViewIsModal:true});expect(root.findAllByProps({accessibilityRole:'button'}).every((x:any)=>x.props.accessibilityState.disabled)).toBe(true);expect(root.findByProps({accessibilityRole:'alert'}).props.accessibilityLiveRegion).toBe('polite')});
 it('applies one shared image-center transform container and iOS target to each board',()=>{let tree:any;act(()=>{tree=create(<BattleScreen snapshot={matchSnapshotV1Schema.parse(fixture)} pendingIntentId={null} connection="CONNECTED" onIntent={()=>{}}/>)});expect(tree.root.findAllByProps({accessibilityRole:'imagebutton'}).every((x:any)=>x.props.style.minHeight===44)).toBe(true);for(const side of ['A','B']){const content=tree.root.findByProps({testID:`board-content-${side}`});expect(content.props.style.transform).toEqual([{translateX:0},{translateY:0},{scale:1}]);expect(content.findAllByType('Image')).toHaveLength(1)}});
 it('executes independent pan, pinch and tap gesture callbacks with cancellation and accumulation',()=>{gestureCallbacks.length=0;const onIntent=vi.fn();let tree:any;act(()=>{tree=create(<BattleScreen snapshot={matchSnapshotV1Schema.parse(fixture)} pendingIntentId={null} connection="CONNECTED" onIntent={onIntent}/>)});expect(gestureCallbacks.filter(x=>x.kind==='pan')).toHaveLength(2);const pan=gestureCallbacks.find(x=>x.kind==='pan')!,pinch=gestureCallbacks.find(x=>x.kind==='pinch')!,tap=gestureCallbacks.find(x=>x.kind==='tap')!;act(()=>{pan.begin?.();pan.update?.({translationX:20,translationY:0});tap.end?.({x:100,y:100})});expect(onIntent).not.toHaveBeenCalled();act(()=>{pinch.begin?.();pinch.update?.({scale:2})});expect(tree.root.findByProps({testID:'board-content-A'}).props.style.transform[2]).toEqual({scale:2})});
 it('executes reduced-motion, high-contrast, reflow, focus order and modal trap semantics',()=>{const snapshot={...fixture,meaningQuiz:{quizOrdinal:1,prompt:'Choose a deliberately long answer at 200 percent text',options:[{id:'a',label:'Long answer A'},{id:'b',label:'Long answer B'}],remainingMs:100}};let tree:any;act(()=>{tree=create(<BattleScreen snapshot={matchSnapshotV1Schema.parse(snapshot)} pendingIntentId={null} connection="CONNECTED" preferences={{reducedMotion:true,highContrast:true}} onIntent={()=>{}}/>)});expect(tree.root.findByType('SafeAreaView').props.style.backgroundColor).toBe('#000000');expect(tree.root.findAllByType('Image').every((x:any)=>x.props.fadeDuration===0)).toBe(true);expect(tree.root.findByProps({accessibilityRole:'alert'}).props).toMatchObject({accessibilityViewIsModal:true,importantForAccessibility:'yes'});expect(tree.root.findAllByType('Text').every((x:any)=>x.props.maxFontSizeMultiplier===2&&x.props.style?.flexShrink!==0)).toBe(true)});

 const withMission=(overrides:Record<string,unknown>)=>({...fixture,serverNowMs:10000,mission:{id:'word_1',kind:'NORMAL',publicPrompt:'Sun',startedAtMs:10000,endsAtMs:15000,...overrides}});

 it('surfaces the served word hunt prompt instead of dropping it',()=>{let tree:any;act(()=>{tree=create(<BattleScreen snapshot={matchSnapshotV1Schema.parse(withMission({}))} pendingIntentId={null} connection="CONNECTED" onIntent={()=>{}}/>)});
  expect(tree.root.findByProps({testID:'word-hunt-prompt'}).props.children).toBe('Sun');
  // Inside the reveal grace the engine rejects taps, so the banner must not urge one.
  expect(tree.root.findByProps({testID:'word-hunt-stage'}).props.children).toBe('Get ready');
  expect(tree.root.findAllByType('Text').every((x:any)=>x.props.maxFontSizeMultiplier===2&&x.props.style?.flexShrink!==0)).toBe(true)});

 it('counts the remaining window down once the reveal grace has passed',()=>{const snapshot={...withMission({}),serverNowMs:12000};let tree:any;act(()=>{tree=create(<BattleScreen snapshot={matchSnapshotV1Schema.parse(snapshot)} pendingIntentId={null} connection="CONNECTED" onIntent={()=>{}}/>)});
  expect(tree.root.findByProps({testID:'word-hunt-stage'}).props.children).toBe('3s left')});

 it('hides the banner entirely when no mission is active',()=>{let tree:any;act(()=>{tree=create(<BattleScreen snapshot={matchSnapshotV1Schema.parse(fixture)} pendingIntentId={null} connection="CONNECTED" onIntent={()=>{}}/>)});
  expect(tree.root.findAllByProps({testID:'word-hunt-banner'})).toHaveLength(0)});
});
