import React from 'react';import {act,create} from 'react-test-renderer';import {describe,expect,it,vi} from 'vitest';
(globalThis as typeof globalThis & {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
const gestureCallbacks:Array<{kind:string;begin?:()=>void;update?:(x:any)=>void;end?:(x:any)=>void}>=[];
vi.mock('react-native',()=>({AccessibilityInfo:{setAccessibilityFocus:vi.fn()},findNodeHandle:()=>1,Image:'Image',Modal:'Modal',Platform:{OS:'ios'},Pressable:'Pressable',Text:'Text',View:'View'}));
vi.mock('react-native-safe-area-context',()=>({SafeAreaView:'SafeAreaView'}));
vi.mock('react-native-gesture-handler',()=>{const gesture=(kind:string)=>{const callbacks:{kind:string;begin?:()=>void;update?:(x:any)=>void;end?:(x:any)=>void}={kind};if(gestureCallbacks.filter(x=>x.kind===kind).length<2)gestureCallbacks.push(callbacks);const api:any={enabled:()=>api,onEnd:(x:any)=>{callbacks.end=x;return api},runOnJS:()=>api,onBegin:(x:any)=>{callbacks.begin=x;return api},onUpdate:(x:any)=>{callbacks.update=x;return api}};return api};return{Gesture:{Tap:()=>gesture('tap'),Pan:()=>gesture('pan'),Pinch:()=>gesture('pinch'),Exclusive:(...x:unknown[])=>x,Simultaneous:(...x:unknown[])=>x},GestureDetector:'GestureDetector'}});
import fixture from '../../../../tests/fixtures/public-match-snapshot.json' with {type:'json'};import {matchSnapshotV1Schema} from '../../../../packages/contracts/src/socket.schema.js';import {BattleScreen} from './BattleScreen.js';

describe('native BattleScreen rendering',()=>{
 it('admits and renders the development app route without crashing',async()=>{(globalThis as typeof globalThis & {__DEV__:boolean}).__DEV__=true;const {default:Home}=await import('../../app/index.js');let tree:any;await act(async()=>{tree=create(<Home/>)});expect(tree.root.findAllByProps({accessibilityRole:'imagebutton'})).toHaveLength(2)});
 it('renders the admitted wire fixture with tokenized native accessibility semantics',()=>{let tree:any;act(()=>{tree=create(<BattleScreen snapshot={matchSnapshotV1Schema.parse(fixture)} pendingIntentId={null} connection="CONNECTED" onIntent={()=>{}}/>)});const root=tree.root;expect(root.findByType('SafeAreaView').props.style.backgroundColor).toBe('#F5FAFF');expect(root.findAllByProps({accessibilityRole:'imagebutton'})).toHaveLength(2);expect(root.findAllByProps({accessibilityLiveRegion:'polite'}).length).toBeGreaterThan(0);expect(root.findAllByType('Text').every((x:any)=>x.props.maxFontSizeMultiplier===2)).toBe(true)});
 it('renders disabled and modal states with trap, blocked back, 200% text and focus restoration target',()=>{const snapshot={...fixture,meaningQuiz:{quizOrdinal:1,prompt:'Choose',options:[{id:'a',label:'A'},{id:'b',label:'B'}],remainingMs:100}};let tree:any;act(()=>{tree=create(<BattleScreen snapshot={matchSnapshotV1Schema.parse(snapshot)} pendingIntentId="pending" connection="RECONNECTING" onIntent={()=>{}}/>)});const root=tree.root;expect(root.findByType('Modal').props).toMatchObject({visible:true,accessibilityViewIsModal:true});expect(root.findAllByProps({accessibilityRole:'button'}).every((x:any)=>x.props.accessibilityState.disabled)).toBe(true);expect(root.findByProps({accessibilityRole:'alert'}).props.accessibilityLiveRegion).toBe('polite')});
 it('applies one shared image-center transform container and iOS target to each board',()=>{let tree:any;act(()=>{tree=create(<BattleScreen snapshot={matchSnapshotV1Schema.parse(fixture)} pendingIntentId={null} connection="CONNECTED" onIntent={()=>{}}/>)});expect(tree.root.findAllByProps({accessibilityRole:'imagebutton'}).every((x:any)=>x.props.style.minHeight===44)).toBe(true);for(const side of ['A','B']){const content=tree.root.findByProps({testID:`board-content-${side}`});expect(content.props.style.transform).toEqual([{translateX:0},{translateY:0},{scale:1}]);expect(content.findAllByType('Image')).toHaveLength(1)}});
 it('executes independent pan, pinch and tap gesture callbacks with cancellation and accumulation',()=>{gestureCallbacks.length=0;const onIntent=vi.fn();let tree:any;act(()=>{tree=create(<BattleScreen snapshot={matchSnapshotV1Schema.parse(fixture)} pendingIntentId={null} connection="CONNECTED" onIntent={onIntent}/>)});expect(gestureCallbacks.filter(x=>x.kind==='pan')).toHaveLength(2);const pan=gestureCallbacks.find(x=>x.kind==='pan')!,pinch=gestureCallbacks.find(x=>x.kind==='pinch')!,tap=gestureCallbacks.find(x=>x.kind==='tap')!;act(()=>{pan.begin?.();pan.update?.({translationX:20,translationY:0});tap.end?.({x:100,y:100})});expect(onIntent).not.toHaveBeenCalled();act(()=>{pinch.begin?.();pinch.update?.({scale:2})});expect(tree.root.findByProps({testID:'board-content-A'}).props.style.transform[2]).toEqual({scale:2})});
});
