import React from 'react';import {act,create} from 'react-test-renderer';import {describe,expect,it,vi} from 'vitest';
(globalThis as typeof globalThis & {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
vi.mock('react-native',()=>({AccessibilityInfo:{setAccessibilityFocus:vi.fn()},findNodeHandle:()=>1,Image:'Image',Modal:'Modal',Pressable:'Pressable',Text:'Text',View:'View'}));
vi.mock('react-native-safe-area-context',()=>({SafeAreaView:'SafeAreaView'}));
vi.mock('react-native-gesture-handler',()=>{const gesture=()=>{const api:any={enabled:()=>api,onEnd:()=>api,runOnJS:()=>api,onBegin:()=>api,onUpdate:()=>api};return api};return{Gesture:{Tap:gesture,Pan:gesture,Pinch:gesture,Exclusive:(...x:unknown[])=>x,Simultaneous:(...x:unknown[])=>x},GestureDetector:'GestureDetector'}});
import fixture from '../../../../tests/fixtures/public-match-snapshot.json' with {type:'json'};import {matchSnapshotV1Schema} from '../../../../packages/contracts/src/socket.schema.js';import {BattleScreen} from './BattleScreen.js';

describe('native BattleScreen rendering',()=>{
 it('admits and renders the development app route without crashing',async()=>{(globalThis as typeof globalThis & {__DEV__:boolean}).__DEV__=true;const {default:Home}=await import('../../app/index.js');let tree:any;await act(async()=>{tree=create(<Home/>)});expect(tree.root.findAllByProps({accessibilityRole:'imagebutton'})).toHaveLength(2)});
 it('renders the admitted wire fixture with tokenized native accessibility semantics',()=>{let tree:any;act(()=>{tree=create(<BattleScreen snapshot={matchSnapshotV1Schema.parse(fixture)} pendingIntentId={null} connection="CONNECTED" onIntent={()=>{}}/>)});const root=tree.root;expect(root.findByType('SafeAreaView').props.style.backgroundColor).toBe('#F5FAFF');expect(root.findAllByProps({accessibilityRole:'imagebutton'})).toHaveLength(2);expect(root.findAllByProps({accessibilityLiveRegion:'polite'}).length).toBeGreaterThan(0);expect(root.findAllByType('Text').every((x:any)=>x.props.maxFontSizeMultiplier===2)).toBe(true)});
 it('renders disabled and modal states with trap, blocked back, 200% text and focus restoration target',()=>{const snapshot={...fixture,meaningQuiz:{quizOrdinal:1,prompt:'Choose',options:[{id:'a',label:'A'},{id:'b',label:'B'}],remainingMs:100}};let tree:any;act(()=>{tree=create(<BattleScreen snapshot={matchSnapshotV1Schema.parse(snapshot)} pendingIntentId="pending" connection="RECONNECTING" onIntent={()=>{}}/>)});const root=tree.root;expect(root.findByType('Modal').props).toMatchObject({visible:true,accessibilityViewIsModal:true});expect(root.findAllByProps({accessibilityRole:'button'}).every((x:any)=>x.props.accessibilityState.disabled)).toBe(true);expect(root.findByProps({accessibilityRole:'alert'}).props.accessibilityLiveRegion).toBe('polite')});
});
