import fs from 'node:fs';import path from'node:path';import{createHash}from'node:crypto';
export type NormativeRequirement={id:string;source:string;sourceLine:number;section:string;text:string;fingerprint:string};
const marker=/\s*<!-- REQ: ((?:RULE|STATE|SEC|RISK|API|DATA|ECON|CONTENT|UX|QA|OBS|ENV|DOC)-\d{2,3}) -->\s*$/u;
const bullet=/^\s*[-*]\s+(.+?)\s*$/u;
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
export function discoverNormativeRequirements(source:string,text:string){let section='(document)',inFence=false;const rows:NormativeRequirement[]=[];for(const [i,line]of text.split(/\r?\n/u).entries()){if(/^\s*```/u.test(line)){inFence=!inFence;continue;}if(inFence)continue;const heading=/^#{1,6}\s+(.+)$/u.exec(line);if(heading)section=heading[1]!.trim();const b=bullet.exec(line),m=marker.exec(line);if(b&&m){const value=b[1]!.replace(marker,'').trim();rows.push({id:m[1]!,source,sourceLine:i+1,section,text:value,fingerprint:hash(`${source}\n${section}\n${value}`)});}}return rows;}
export function findUnmarkedNormativeBullets(source:string,text:string){let inFence=false;return text.split(/\r?\n/u).flatMap((line,i)=>{if(/^\s*```/u.test(line)){inFence=!inFence;return[];}return!inFence&&bullet.test(line)&&!marker.test(line)?[`${source}:${i+1}`]:[];});}
export function checkRepositoryTraceability(root:string){const files=fs.readdirSync(root).filter(x=>x==='README.md'||/^\d{2}_.+\.md$/u.test(x)).sort();const discovered=files.flatMap(file=>discoverNormativeRequirements(file,fs.readFileSync(path.join(root,file),'utf8'))),unmarked=files.flatMap(file=>findUnmarkedNormativeBullets(file,fs.readFileSync(path.join(root,file),'utf8')));const registryPath=path.join(root,'docs/requirements-registry.v1.json');const registry=fs.existsSync(registryPath)?JSON.parse(fs.readFileSync(registryPath,'utf8')) as {requirements:Array<NormativeRequirement&{schema:string;phase:string;test:string;metric:string}>}:{requirements:[]};const byId=new Map(registry.requirements.map(r=>[r.id,r]));const duplicate=[...new Set(discovered.map(r=>r.id).filter((id,i,a)=>a.indexOf(id)!==i))],missing=discovered.filter(r=>!byId.has(r.id)).map(r=>r.id),orphan=registry.requirements.filter(r=>!discovered.some(d=>d.id===r.id)).map(r=>r.id),sourceDrift=discovered.filter(r=>{const x=byId.get(r.id);return x&&(x.source!==r.source||x.sourceLine!==r.sourceLine||x.section!==r.section||x.fingerprint!==r.fingerprint)}).map(r=>r.id),broken=registry.requirements.flatMap(r=>[r.source,r.schema,r.test].filter(p=>!fs.existsSync(path.join(root,p))).map(p=>`${r.id}:${p}`));return{unmarked,duplicate,missing,orphan,sourceDrift,broken,count:discovered.length};}
export const normativeNumericTokens:Record<string,readonly string[]>={'07_REALTIME_SERVER_SPEC.md':['100 concurrent matches/200 sockets','250ms','<0.1%','10,000 unique requests','200-match/400-socket 30-minute soak'],'11_TEST_AND_BALANCE_PLAN.md':['50~70','40~65%','70%','0.5~1.5','50 matches','10,000 matches','100,000 draws','botModelVersion']};
export function checkNormativeNumbers(textByPath:Record<string,string>){return Object.entries(normativeNumericTokens).flatMap(([file,tokens])=>tokens.filter(token=>!textByPath[file]?.includes(token)).map(token=>`${file}:${token}`));}
const required=['check:runtime','admin:check','ruleset:projections:check','content:schemas:check','ui:schemas:check','ui:docs:check','ui:reference:check','ui:assets:check','ui:acceptance:check','lint','typecheck','test','openapi:lint','docs:check','content:validate','secret:scan'];
const tokenize=(script:string)=>script.split(/\s*&&\s*/u).map(command=>command.trim().split(/\s+/u));
export function validateGateScripts(scripts:Record<string,string>){const commands=tokenize(scripts.check??''),actual=commands.map(tokens=>tokens.length===3&&tokens[0]==='corepack'&&tokens[1]==='pnpm'?tokens[2]:null);const failures=required.filter(name=>!actual.includes(name)).map(name=>`check:${name}`);if(scripts.verify!=='pnpm check && pnpm check:db')failures.push('verify');return failures;}
