import fs from'node:fs';import path from'node:path';import{createHash}from'node:crypto';
export type TraceRow={id:string;source:string;sourceLine:number;section:string;text:string;fingerprint:string;schema:string;phase:string;test:string;metric:string|null;evidenceKind:string;oracle:string;linkageProof:string};
const hash=(s:string)=>createHash('sha256').update(s).digest('hex'),marker=/\s*<!-- REQ: ([A-Z]+-\d{3}) -->\s*$/u,separator=/^\s*\|?(?:\s*:?-+:?\s*\|)+\s*$/u;
const candidate=(line:string)=>line.trim()!==''&&!/^\s*(?:#{1,6}\s|<!--|---+$)/u.test(line)&&!separator.test(line);
const textOf=(line:string)=>line.replace(marker,'').replace(/^\s*(?:(?:[-*]|\d+\.)\s+|>\s*)/u,'').trim();
export function discoverNormativeRequirements(source:string,text:string){let section='(document)',inFence=false;const rows=[];for(const[i,line]of text.split(/\r?\n/u).entries()){if(/^\s*```/u.test(line)){inFence=!inFence;continue;}if(inFence)continue;const h=/^#{1,6}\s+(.+)$/u.exec(line);if(h){section=h[1]!.trim();continue;}const m=marker.exec(line);if(candidate(line)&&m){const value=textOf(line);rows.push({id:m[1]!,source,sourceLine:i+1,section,text:value,fingerprint:hash(`${source}\n${section}\n${value}`)});}}return rows;}
export function findUnmarkedNormative(source:string,text:string){let inFence=false;return text.split(/\r?\n/u).flatMap((line,i)=>{if(/^\s*```/u.test(line)){inFence=!inFence;return[];}return!inFence&&candidate(line)&&!marker.test(line)?[`${source}:${i+1}`]:[];});}
const maps={DOC:['tools/check-docs.mjs','tests/specs/traceability.test.ts'],RULE:['packages/contracts/src/rules.schema.ts','tests/specs/ruleset-parity.test.ts'],STATE:['packages/contracts/src/match.schema.ts','packages/game-engine/src/replay.test.ts'],UX:['packages/contracts/src/ui.ts','tests/contracts/ui-final-acceptance.test.ts'],ECON:['packages/contracts/src/economy.schema.ts','tests/simulation/pet-economy.test.ts'],SEC:['packages/contracts/src/quarantine.ts','packages/contracts/src/quarantine.test.ts'],OBS:['packages/contracts/src/analytics.ts','tests/contracts/analytics-event.test.ts'],DATA:['supabase/migrations/202607150001_initial_schema.sql','tests/database/concurrency.test.ts'],API:['packages/contracts/openapi.yaml','packages/contracts/src/openapi.test.ts'],CONTENT:['packages/contracts/src/content.ts','packages/contracts/src/content.test.ts'],QA:['tools/release-evidence.ts','tests/simulation/release-verification.test.ts'],ENV:['tools/check-runtime.mjs','tests/contracts/runtime-gate.test.ts']}as const;
const proof=(r:Omit<TraceRow,'linkageProof'>)=>hash([r.id,r.fingerprint,r.schema,r.test,r.evidenceKind,r.oracle].join('\n'));
export function checkRepositoryTraceability(root:string){const files=fs.readdirSync(root).filter(x=>x==='README.md'||/^\d{2}_.+\.md$/u.test(x)).sort(),discovered=files.flatMap(file=>discoverNormativeRequirements(file,fs.readFileSync(path.join(root,file),'utf8'))),unmarked=files.flatMap(file=>findUnmarkedNormative(file,fs.readFileSync(path.join(root,file),'utf8'))),registry=(JSON.parse(fs.readFileSync(path.join(root,'docs/requirements-registry.v1.json'),'utf8'))as{requirements:TraceRow[]}).requirements,evidencePath=path.join(root,'config/requirement-evidence.v1.json'),evidence=fs.existsSync(evidencePath)?(JSON.parse(fs.readFileSync(evidencePath,'utf8'))as{entries:Array<Pick<TraceRow,'id'|'evidenceKind'|'oracle'|'metric'|'linkageProof'>>}).entries:[],claims=new Map(evidence.map(x=>[x.id,x])),byId=new Map(registry.map(r=>[r.id,r])),ids=discovered.map(x=>x.id),duplicate=[...new Set(ids.filter((id,i)=>ids.indexOf(id)!==i))],missing=discovered.filter(r=>!byId.has(r.id)).map(r=>r.id),orphan=registry.filter(r=>!ids.includes(r.id)).map(r=>r.id),sourceDrift=discovered.filter(r=>{const x=byId.get(r.id);return x&&(x.source!==r.source||x.sourceLine!==r.sourceLine||x.section!==r.section||x.fingerprint!==r.fingerprint)}).map(r=>r.id),semantic=registry.filter(r=>{const family=r.id.split('-')[0]as keyof typeof maps,m=maps[family],claim=claims.get(r.id);return!m||r.schema!==m[0]||r.test!=='tests/specs/generated-requirement-coverage.test.ts'||r.metric!==null||r.evidenceKind!=='EXECUTABLE_PROJECTION'||!r.oracle.includes(r.id)||r.linkageProof!==proof(r)||!claim||claim.linkageProof!==r.linkageProof||claim.oracle!==r.oracle;}).map(r=>r.id),broken=registry.flatMap(r=>[r.source,r.schema,r.test].filter(p=>!fs.existsSync(path.join(root,p))).map(p=>`${r.id}:${p}`));return{unmarked,duplicate,missing,orphan,sourceDrift,semantic,broken,count:discovered.length};}
export const normativeNumericTokens:Record<string,readonly string[]>={'07_REALTIME_SERVER_SPEC.md':['100 concurrent matches/200 sockets','250ms','<0.1%','10,000 unique requests','200-match/400-socket 30-minute soak'],'11_TEST_AND_BALANCE_PLAN.md':['50~70','40~65%','70%','0.5~1.5','50 matches','10,000 matches','100,000 draws','botModelVersion']};export function checkNormativeNumbers(x:Record<string,string>){return Object.entries(normativeNumericTokens).flatMap(([f,t])=>t.filter(v=>!x[f]?.includes(v)).map(v=>`${f}:${v}`));}
export const requiredGateCommands=['check:runtime','admin:check','ruleset:projections:check','content:schemas:check','ui:schemas:check','ui:docs:check','ui:reference:check','ui:assets:check','ui:acceptance:check','lint','typecheck','test','openapi:lint','docs:check','release:reports:check','content:validate','secret:scan'];export function validateGateScripts(s:Record<string,string>){const actual=(s.check??'').split(/\s*&&\s*/u).map(x=>x.trim().split(/\s+/u)).map(x=>x.length===3&&x[0]==='corepack'&&x[1]==='pnpm'?x[2]:`INVALID:${x.join(' ')}`),failures=JSON.stringify(actual)===JSON.stringify(requiredGateCommands)?[]:['check:exact-order'];if(s.verify!=='pnpm check && pnpm check:db')failures.push('verify');return failures;}
