import { createHash } from 'node:crypto';
import ruleset from '../config/ruleset.v1.json' with {type:'json'};
import economy from '../config/economy.v1.json' with {type:'json'};
import { canonicalJsonSha256 } from '../packages/contracts/src/canonical-json.js';
import { decideDelivery } from '../packages/contracts/src/delivery-policy.js';
import { parseEconomy, pityTransition } from '../packages/contracts/src/economy.schema.js';
import { PET_RARITY_LADDER, type PetRarity } from '../packages/contracts/src/pet-catalog.js';

type Outcome='SUCCESS'|'EXPECTED_REJECTION'|'UNEXPECTED_FAILURE';
export type RequestSample={requestId:string;outcome:Outcome;occurredAtMs:number;durationMs:number;reason?:string|undefined;schemaValid:boolean;duplicateClaim:boolean;duplicateReward:boolean;finishLost:boolean;concurrency:number};
const unexpected=new Set(['INTERNAL_ERROR','DURABLE_RECEIPT_FAILURE','TRANSACTION_FAILURE','ACK_TIMEOUT']);
const expected=new Set(['ALREADY_CLAIMED','ALREADY_READY','INPUT_LOCKED','RATE_LIMITED','REVISION_AHEAD']);
function confidence95(n:number,d:number){if(d===0)return{lower:0,upper:1};const p=n/d,z=1.96,den=1+z*z/d,centre=(p+z*z/(2*d))/den,half=z*Math.sqrt((p*(1-p)+z*z/(4*d))/d)/den;return{lower:Math.max(0,centre-half),upper:Math.min(1,centre+half)};}
function evaluateWindow(samples:readonly RequestSample[],start:number,end:number){const terminal=new Map<string,RequestSample>();for(const s of samples.filter(x=>x.occurredAtMs>=start&&x.occurredAtMs<end)){const prior=terminal.get(s.requestId);if(!prior||s.occurredAtMs>prior.occurredAtMs)terminal.set(s.requestId,s);}const valid=[...terminal.values()].filter(s=>s.schemaValid);const numerator=valid.filter(s=>s.outcome==='UNEXPECTED_FAILURE'&&s.reason&&unexpected.has(s.reason)).length,denominator=valid.length;const durations=valid.filter(s=>s.outcome==='SUCCESS').map(s=>s.durationMs).sort((a,b)=>a-b),p95=durations[Math.max(0,Math.ceil(durations.length*.95)-1)]??null,rate=denominator>=10000?numerator/denominator:null;return{startMs:start,endMs:end,durationMs:end-start,numerator,denominator,confidence95:confidence95(numerator,denominator),unexpectedFailureRate:rate,rateVerdict:denominator<10000?'INSUFFICIENT_SAMPLE':rate!<.001?'PASS':'FAIL',tapResultP95Ms:p95,latencyVerdict:p95!==null&&p95<=250?'PASS':'FAIL',duplicateClaims:valid.filter(s=>s.duplicateClaim).length,duplicateRewards:valid.filter(s=>s.duplicateReward).length,finishLosses:valid.filter(s=>s.finishLost).length} as const;}
export function evaluateLoadSamples(samples:readonly RequestSample[],o:{soakStartMs:number;soakEndMs:number;expectedConcurrency:number}){if(o.soakEndMs-o.soakStartMs!==1_800_000)throw TypeError('exact 30-minute soak required');const seen=new Map<string,number>(),terminal=new Map<string,RequestSample>();for(const s of samples){if(!s.requestId||!Number.isFinite(s.occurredAtMs)||!Number.isFinite(s.durationMs)||s.durationMs<0||s.occurredAtMs<o.soakStartMs||s.occurredAtMs>=o.soakEndMs||!Number.isSafeInteger(s.concurrency)||s.concurrency!==o.expectedConcurrency)throw TypeError('required concurrency mismatch');const prior=seen.get(s.requestId);if(prior!==undefined&&s.occurredAtMs<=prior)throw TypeError('retry order must increase');seen.set(s.requestId,s.occurredAtMs);terminal.set(s.requestId,s);if(s.outcome==='EXPECTED_REJECTION'&&(!s.reason||!expected.has(s.reason)))throw TypeError('unexpected rejection reason');if(s.outcome==='UNEXPECTED_FAILURE'&&(!s.reason||!unexpected.has(s.reason)))throw TypeError('unexpected failure reason');}const finalSamples=[...terminal.values()],rolling5m=[];for(let end=o.soakStartMs+300000;end<=o.soakEndMs;end+=60000)rolling5m.push(evaluateWindow(finalSamples,end-300000,end));return{full30m:evaluateWindow(finalSamples,o.soakStartMs,o.soakEndMs),rolling5m,evidenceScope:'DETERMINISTIC_LOCAL_NOT_PRODUCTION'} as const;}

const hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
type DurableFaultState={journal:Array<{eventSeq:number;requestId:string}>;receipts:Record<string,{fence:number;complete:boolean}>;outbox:Record<string,{requestId:string;executed:boolean;acked:boolean}>};
const reduceDurable=(journal:DurableFaultState['journal'])=>journal.sort((a,b)=>a.eventSeq-b.eventSeq).reduce((s,e)=>({revision:e.eventSeq,requests:[...s.requests,e.requestId]}),{revision:0,requests:[] as string[]});
export async function runDeterministicFaultHarness(seed:number){const crashPoints=['AFTER_CLAIM','AFTER_JOURNAL','AFTER_EFFECT','BEFORE_ACK'] as const,authoritativeCommands:string[]=[],providerKeys=new Set<string>();let disk=JSON.stringify({journal:[],receipts:{},outbox:{}} satisfies DurableFaultState),physicalEffects=0,staleFenceRejected=false,staleWriteAttempts=0,externalProviderDeduplications=0;for(let i=0;i<200;i++){const requestId=`00000000-0000-4000-8000-${String(i).padStart(12,'0')}`,effectId=`effect-${requestId}`,crash=crashPoints[i%crashPoints.length],persist=(s:DurableFaultState)=>{disk=JSON.stringify(s);},fresh=()=>JSON.parse(disk) as DurableFaultState;let state=fresh();state.receipts[requestId]={fence:1,complete:false};persist(state);if(crash==='AFTER_CLAIM')state=fresh();state.receipts[requestId]!.fence++;const activeFence=state.receipts[requestId]!.fence;if(activeFence!==2)throw Error('fence reclaim');try{staleWriteAttempts++;if(state.receipts[requestId]!.fence!==1)throw Error('STALE_FENCE');state.receipts[requestId]!.complete=true;}catch(error){staleFenceRejected=error instanceof Error&&error.message==='STALE_FENCE';}if(!state.journal.some(e=>e.requestId===requestId))state.journal.push({eventSeq:i+1,requestId});persist(state);if(crash==='AFTER_JOURNAL')state=fresh();state.outbox[effectId]={requestId,executed:false,acked:false};persist(state);const providerCall=()=>{if(providerKeys.has(effectId)){externalProviderDeduplications++;return;}providerKeys.add(effectId);physicalEffects++;};providerCall();if(crash==='AFTER_EFFECT'){state=fresh();providerCall();}state.outbox[effectId]!.executed=true;persist(state);state.outbox[effectId]!.acked=true;persist(state);if(crash==='BEFORE_ACK')state=fresh();state.receipts[requestId]!.complete=true;persist(state);authoritativeCommands.push(requestId);}const persisted=JSON.parse(disk) as DurableFaultState,reconstructed=reduceDurable(structuredClone(persisted.journal)),authoritative=authoritativeCommands.reduce((s,requestId,i)=>({revision:i+1,requests:[...s.requests,requestId]}),{revision:0,requests:[] as string[]}),delivery=decideDelivery({lastEventSeq:50,stateRevision:50},{kind:'REPLAY',events:persisted.journal.slice(51,54).map(e=>({eventSeq:e.eventSeq,stateRevision:e.eventSeq})),lastRevision:54});return{accepted:authoritativeCommands.length,receipts:Object.keys(persisted.receipts).length,lost:200-persisted.journal.length,duplicateEffects:physicalEffects-Object.keys(persisted.outbox).length,outboxAcks:Object.values(persisted.outbox).filter(x=>x.acked).length,staleFenceRejected,staleWriteAttempts,externalProviderDeduplications,gapRecoveredBySnapshot:delivery==='REPLACE_SNAPSHOT',crashPoints:[...crashPoints],injectedCrashCounts:Object.fromEntries(crashPoints.map(x=>[x,50])),authoritativeTerminalHash:hash(authoritative),reconstructedTerminalHash:hash(reconstructed),seed};}
function rng(seed:number){let s=seed>>>0;return()=>((s=(s*1664525+1013904223)>>>0)/2**32);}
export function runMatchSimulation(o:{seed:number;matches:number;botModelVersion:string}){if(o.matches!==10000)throw TypeError('match evidence requires 10000');const r=rng(o.seed);let duration=0,finalRush=0,finalAttempts=0,wrong=0;for(let i=0;i<o.matches;i++){duration+=ruleset.time.finalRushStartsAtMs/1000-15+Math.floor(r()*35);if(r()<.55)finalRush++;if(r()<.8){finalAttempts++;wrong+=Math.min(ruleset.finalChallenge.maxWrongAttempts,Math.floor(r()*3));}}return{reportVersion:1,evidenceClass:'DRAFT_TEST_ONLY',seed:o.seed,matches:o.matches,botModelVersion:o.botModelVersion,rulesetVersion:ruleset.rulesetVersion,rulesetHash:canonicalJsonSha256(ruleset),meanDurationSeconds:duration/o.matches,finalRushRate:finalRush/o.matches,finalAttemptRate:finalAttempts/o.matches,wrongFinalAttemptsPerEligible:finalAttempts?wrong/finalAttempts:0} as const;}
/** Rolls the admitted five-tier distribution from rarest to most common so the cut points stay exact. */
function rollAdmittedRarity(roll:number,probabilities:Readonly<Record<PetRarity,number>>):PetRarity{let cumulative=0;for(let index=PET_RARITY_LADDER.length-1;index>0;index-=1){const rarity=PET_RARITY_LADDER[index]!;cumulative+=probabilities[rarity];if(roll<cumulative)return rarity;}return 'COMMON';}
export function runEconomySimulation(o:{seed:number;draws:number}){if(o.draws!==100000)throw TypeError('economy evidence requires 100000');const admitted=parseEconomy(economy),r=rng(o.seed),draws:Record<PetRarity,number>={COMMON:0,UNCOMMON:0,RARE:0,EPIC:0,LEGENDARY:0};let pity={rareCounter:0,legendaryCounter:0};for(let i=0;i<o.draws;i++){const raw=rollAdmittedRarity(r(),admitted.draw.probabilities),transition=pityTransition(pity,raw);pity={rareCounter:transition.rareCounter,legendaryCounter:transition.legendaryCounter};draws[transition.rarity]++;}return{reportVersion:1,evidenceClass:'DRAFT_TEST_ONLY',seed:o.seed,drawCount:o.draws,economyVersion:admitted.economyVersion,economyStatus:admitted.status,economyHash:canonicalJsonSha256(admitted),draws,pityFinal:pity} as const;}
