import { createHash } from 'node:crypto';
export type LoadInput={uniqueRequests:number;unexpectedFailures:number;tapLatenciesMs:number[];duplicateClaims:number;duplicateRewards:number;finishLosses:number};
export function evaluateLoadEvidence(x:LoadInput){
 const sorted=[...x.tapLatenciesMs].sort((a,b)=>a-b);const p95=sorted[Math.max(0,Math.ceil(sorted.length*.95)-1)]??null;
 const rate=x.uniqueRequests<10000?null:x.unexpectedFailures/x.uniqueRequests;
 return{numerator:x.unexpectedFailures,denominator:x.uniqueRequests,unexpectedFailureRate:rate,rateVerdict:x.uniqueRequests<10000?'INSUFFICIENT_SAMPLE':rate!==null&&rate<.001?'PASS':'FAIL',tapResultP95Ms:p95,latencyVerdict:p95!==null&&p95<=250?'PASS':'FAIL',zeroDuplicateVerdict:x.duplicateClaims===0&&x.duplicateRewards===0?'PASS':'FAIL',zeroFinishLossVerdict:x.finishLosses===0?'PASS':'FAIL',evidenceScope:'DETERMINISTIC_LOCAL_NOT_PRODUCTION'} as const;
}
function hash(x:unknown){return createHash('sha256').update(JSON.stringify(x)).digest('hex');}
export function runDeterministicFaultHarness(seed:number){const receipts=new Map<string,string>(),effects=new Set<string>(),finishes=new Set<string>();for(let i=0;i<200;i++){const id=`r-${seed}-${i}`;const decision=hash({id,accepted:true});receipts.set(id,decision);if(i%2===0)finishes.add(`m-${i/2}`);effects.add(`effect-${id}`);if(i%7===0){receipts.set(id,decision);effects.add(`effect-${id}`);}}const snapshot=[...receipts].sort();return{accepted:200,receipts:receipts.size,effects:effects.size,finishes:finishes.size,lost:200-receipts.size,duplicateEffects:200-effects.size,replayHashStable:hash(snapshot)===hash([...receipts].sort())};}
function rng(seed:number){let s=seed>>>0;return()=>((s=(s*1664525+1013904223)>>>0)/2**32);}
export function runBalanceSimulation(o:{seed:number;matches:number;botModelVersion:string}){const r=rng(o.seed);let duration=0,finalRush=0,finalAttempts=0,wrong=0;for(let i=0;i<o.matches;i++){duration+=45+Math.floor(r()*35);if(r()<.55)finalRush++;if(r()<.8){finalAttempts++;wrong+=Math.floor(r()*3);}}return{reportVersion:1,evidenceClass:'DRAFT_TEST_ONLY',seed:o.seed,matches:o.matches,botModelVersion:o.botModelVersion,rulesetVersion:'1.0.0',meanDurationSeconds:duration/o.matches,finalRushRate:finalRush/o.matches,finalAttemptRate:finalAttempts/o.matches,wrongFinalAttemptsPerEligible:finalAttempts?wrong/finalAttempts:0,disclaimer:'Bot sensitivity evidence only; not human satisfaction, learning, fairness, capacity, or an approved product gate.'} as const;}
