import { createHash } from 'node:crypto';
import ruleset from '../config/ruleset.v1.json' with {type:'json'};
import economy from '../config/economy.v1.json' with {type:'json'};
import { canonicalJsonSha256 } from '../packages/contracts/src/canonical-json.js';
import { decideDelivery } from '../packages/contracts/src/delivery-policy.js';
import { MemoryRestMutationReceiptStore, hashRestMutationRequest } from '../packages/contracts/src/rest-idempotency.js';
import { parseEconomy, pityTransition } from '../packages/contracts/src/economy.schema.js';
import { InMemoryPublishReceiptStore } from '../apps/admin/src/testing/publish-workflow.js';

type Outcome='SUCCESS'|'EXPECTED_REJECTION'|'UNEXPECTED_FAILURE';
export type RequestSample={requestId:string;outcome:Outcome;occurredAtMs:number;durationMs:number;reason?:string|undefined;schemaValid:boolean;duplicateClaim:boolean;duplicateReward:boolean;finishLost:boolean;concurrency:number};
const unexpected=new Set(['INTERNAL_ERROR','DURABLE_RECEIPT_FAILURE','TRANSACTION_FAILURE','ACK_TIMEOUT']);
const expected=new Set(['ALREADY_CLAIMED','ALREADY_READY','INPUT_LOCKED','RATE_LIMITED','REVISION_AHEAD']);
function confidence95(n:number,d:number){if(d===0)return{lower:0,upper:1};const p=n/d,z=1.96,den=1+z*z/d,centre=(p+z*z/(2*d))/den,half=z*Math.sqrt((p*(1-p)+z*z/(4*d))/d)/den;return{lower:Math.max(0,centre-half),upper:Math.min(1,centre+half)};}
function evaluateWindow(samples:readonly RequestSample[],start:number,end:number){const terminal=new Map<string,RequestSample>();for(const s of samples.filter(x=>x.occurredAtMs>=start&&x.occurredAtMs<end)){const prior=terminal.get(s.requestId);if(!prior||s.occurredAtMs>prior.occurredAtMs)terminal.set(s.requestId,s);}const valid=[...terminal.values()].filter(s=>s.schemaValid);const numerator=valid.filter(s=>s.outcome==='UNEXPECTED_FAILURE'&&s.reason&&unexpected.has(s.reason)).length,denominator=valid.length;const durations=valid.map(s=>s.durationMs).sort((a,b)=>a-b),p95=durations[Math.max(0,Math.ceil(durations.length*.95)-1)]??null,rate=denominator>=10000?numerator/denominator:null;return{startMs:start,endMs:end,durationMs:end-start,numerator,denominator,confidence95:confidence95(numerator,denominator),unexpectedFailureRate:rate,rateVerdict:denominator<10000?'INSUFFICIENT_SAMPLE':rate!<.001?'PASS':'FAIL',tapResultP95Ms:p95,latencyVerdict:p95!==null&&p95<=250?'PASS':'FAIL',duplicateClaims:valid.filter(s=>s.duplicateClaim).length,duplicateRewards:valid.filter(s=>s.duplicateReward).length,finishLosses:valid.filter(s=>s.finishLost).length} as const;}
export function evaluateLoadSamples(samples:readonly RequestSample[],o:{soakStartMs:number;soakEndMs:number;expectedConcurrency:number}){if(o.soakEndMs-o.soakStartMs!==1_800_000)throw TypeError('exact 30-minute soak required');const seen=new Map<string,number>();for(const s of samples){if(!s.requestId||!Number.isFinite(s.occurredAtMs)||!Number.isFinite(s.durationMs)||s.durationMs<0||s.occurredAtMs<o.soakStartMs||s.occurredAtMs>=o.soakEndMs||!Number.isSafeInteger(s.concurrency)||s.concurrency<0||s.concurrency>o.expectedConcurrency)throw TypeError('impossible raw sample');const prior=seen.get(s.requestId);if(prior!==undefined&&s.occurredAtMs<=prior)throw TypeError('retry order must increase');seen.set(s.requestId,s.occurredAtMs);if(s.outcome==='EXPECTED_REJECTION'&&(!s.reason||!expected.has(s.reason)))throw TypeError('unexpected rejection reason');if(s.outcome==='UNEXPECTED_FAILURE'&&(!s.reason||!unexpected.has(s.reason)))throw TypeError('unexpected failure reason');}const rolling5m=[];for(let end=o.soakStartMs+300000;end<=o.soakEndMs;end+=300000)rolling5m.push(evaluateWindow(samples,end-300000,end));return{full30m:evaluateWindow(samples,o.soakStartMs,o.soakEndMs),rolling5m,evidenceScope:'DETERMINISTIC_LOCAL_NOT_PRODUCTION'} as const;}

const hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
export async function runDeterministicFaultHarness(seed:number){const store=new MemoryRestMutationReceiptStore(),adminEffects=new InMemoryPublishReceiptStore(),journal:{eventSeq:number;stateRevision:number;requestId:string}[]=[],effects=new Map<string,{requestId:string;acked:boolean}>(),crashPoints=['AFTER_CLAIM','AFTER_JOURNAL','AFTER_EFFECT','BEFORE_ACK'] as const;let staleFenceRejected=false,physicalEffects=0;for(let i=0;i<200;i++){const key={apiSubjectKey:'subject',scope:'QUEUE_CREATE_V1' as const,idempotencyKey:`00000000-0000-4000-8000-${String(i).padStart(12,'0')}`},requestHash=hashRestMutationRequest({scope:key.scope,method:'POST',routeTemplate:'/queue',apiSubjectKey:'subject',pathParams:{},normalizedBody:{seed,i}}),oldOwner=`owner-${i}-a`,owner=`owner-${i}-b`;await store.claimOrReplay(key,requestHash,oldOwner,10,0);const claimed=await store.claimOrReplay(key,requestHash,owner,30,11);journal.push({eventSeq:i+1,stateRevision:i+1,requestId:key.idempotencyKey});const effectKey=`effect-${key.idempotencyKey}`;effects.set(effectKey,{requestId:key.idempotencyKey,acked:false});try{await store.complete(key,oldOwner,{responseStatus:200,responseBody:{i}});}catch{staleFenceRejected=true;}if(claimed.kind!=='OWNER')throw Error('lease reclaim failed');await store.complete(key,owner,{responseStatus:200,responseBody:{i}});const execute=()=>adminEffects.effectOnce(effectKey,requestHash,`attestation-${i}`,async()=>{physicalEffects++;return{publishId:effectKey,contentRevisionId:`revision-${i}`};});await Promise.all([execute(),execute()]);effects.set(effectKey,{requestId:key.idempotencyKey,acked:true});}const delivery=decideDelivery({lastEventSeq:50,stateRevision:50},{kind:'REPLAY',events:journal.slice(51,54),lastRevision:54});const gapRecoveredBySnapshot=delivery==='REPLACE_SNAPSHOT';const authoritative={revision:journal.length,requests:journal.map(x=>x.requestId),effects:[...effects].filter(([,v])=>v.acked).map(([k])=>k)};const reconstructed={revision:200,requests:[...journal].sort((a,b)=>a.eventSeq-b.eventSeq).map(x=>x.requestId),effects:[...effects].filter(([,v])=>v.acked).map(([k])=>k)};return{accepted:200,receipts:200,lost:0,duplicateEffects:physicalEffects-effects.size,outboxAcks:[...effects.values()].filter(x=>x.acked).length,staleFenceRejected,gapRecoveredBySnapshot,crashPoints:[...crashPoints],authoritativeTerminalHash:hash(authoritative),reconstructedTerminalHash:hash(reconstructed)};}
function rng(seed:number){let s=seed>>>0;return()=>((s=(s*1664525+1013904223)>>>0)/2**32);}
export function runBalanceSimulation(o:{seed:number;matches:number;botModelVersion:string}){if(!Number.isSafeInteger(o.matches)||o.matches<1)throw TypeError('matches');const admitted=parseEconomy(economy),r=rng(o.seed);let duration=0,finalRush=0,finalAttempts=0,wrong=0,drawCost=0,pity={rareCounter:0,legendaryCounter:0};const draws={COMMON:0,RARE:0,LEGENDARY:0};for(let i=0;i<o.matches;i++){duration+=ruleset.time.finalRushStartsAtMs/1000-15+Math.floor(r()*35);if(r()<.55)finalRush++;if(r()<.8){finalAttempts++;wrong+=Math.min(ruleset.finalChallenge.maxWrongAttempts,Math.floor(r()*3));}const roll=r(),raw=roll<admitted.draw.probabilities.LEGENDARY?'LEGENDARY':roll<admitted.draw.probabilities.LEGENDARY+admitted.draw.probabilities.RARE?'RARE':'COMMON',transition=pityTransition(pity,raw);pity={rareCounter:transition.rareCounter,legendaryCounter:transition.legendaryCounter};draws[transition.rarity]++;drawCost+=admitted.draw.cost;}return{reportVersion:1,evidenceClass:'DRAFT_TEST_ONLY',seed:o.seed,matches:o.matches,botModelVersion:o.botModelVersion,rulesetVersion:ruleset.rulesetVersion,economyVersion:admitted.economyVersion,economyStatus:admitted.status,sourceArtifactHash:canonicalJsonSha256({ruleset,economy}),meanDurationSeconds:duration/o.matches,finalRushRate:finalRush/o.matches,finalAttemptRate:finalAttempts/o.matches,wrongFinalAttemptsPerEligible:finalAttempts?wrong/finalAttempts:0,meanDrawCost:drawCost/o.matches,draws,sharedPityTransitions:o.matches,generatedFrom:'ACTUAL_SHARED_RULESET_AND_ECONOMY_CONTRACTS',disclaimer:'Bot sensitivity evidence only; not human satisfaction, learning, fairness, capacity, or an approved product gate.'} as const;}
