import fs from'node:fs';import path from'node:path';
import{parseRuleset}from'../packages/contracts/src/rules.schema.js';
import{parseEconomy}from'../packages/contracts/src/economy.schema.js';
import{AnalyticsCollector,emitRequirementGateStatus,parseAnalyticsEventV1,validateLifecycleTrace,type RequirementGateResult}from'../packages/contracts/src/analytics.js';
import{evaluateLoadSamples}from'./release-evidence.js';
import{validateUiReferenceBundle}from'../packages/contracts/src/ui.js';
import{createTestingReplayBundle,testingRules}from'../packages/game-engine/src/testing-fixtures.js';import{reduceMatch}from'../packages/game-engine/src/reducer.js';import{replayMatch}from'../packages/game-engine/src/replay.js';
import{clientCommandEnvelopeSchema,negotiateCompatibility,resolveAuthenticatedParticipant}from'../packages/contracts/src/socket.schema.js';import{decideDelivery,decideReconnect}from'../packages/contracts/src/delivery-policy.js';import{projectSnapshot}from'../packages/contracts/src/projection.js';import{RECOMMENDED_IMAGE_LONG_EDGE_PX}from'../packages/contracts/src/content.js';import{reconnectOverlayForElapsed}from'../packages/game-engine/src/input-projection.js';import{adaptMatchSnapshot,createTapIntent}from'../apps/mobile/src/ui/battle-shell.js';import type{MatchStateV1}from'../packages/contracts/src/match.js';
const externalKinds=new Set(['EXACT_RUNTIME','DEVICE_GOLDEN','PROVIDER_CREDENTIALS','TARGET_REGION_SOAK','LEGAL_APPROVAL','RIGHTS_APPROVAL','PRODUCT_DECISION']);
export function validateNonCurrentEvidence(root:string,claim:{lifecycle:string;closureCondition?:string;closureArtifact?:string;closureArtifactState?:'ABSENT'|'PRESENT';externalKind?:string;localSubstitute?:string}){if(!claim.closureCondition)return false;if(claim.lifecycle==='PLANNED')return!!claim.closureArtifact&&claim.closureArtifactState==='ABSENT'&&!fs.existsSync(path.join(root,claim.closureArtifact));if(claim.lifecycle==='EXTERNAL')return externalKinds.has(claim.externalKind??'')&&!!claim.localSubstitute&&!fs.existsSync(path.join(root,claim.localSubstitute));return false;}

type Row={id:string;source:string;sourceLine:number;text:string};
type Assertion={pointer:string;expected:unknown};type Claim={lifecycle:'CURRENT'|'PLANNED'|'EXTERNAL';oracle:{kind:string;expected:RequirementGateResult;input?:string;assertions?:Assertion[]};blockerReason?:string;closureCondition?:string;closureArtifact?:string;closureArtifactState?:'ABSENT'|'PRESENT';externalKind?:string;localSubstitute?:string};
const resolve=(value:unknown,pointer:string)=>pointer.split('/').slice(1).reduce<unknown>((current,key)=>current!==null&&typeof current==='object'?(current as Record<string,unknown>)[key]:undefined,value);
const assertExact=(value:unknown,assertions:Assertion[]|undefined)=>{if(!assertions?.length)throw Error('exact assertions required');for(const assertion of assertions)if(JSON.stringify(resolve(value,assertion.pointer))!==JSON.stringify(assertion.expected))throw Error(`SSOT mismatch ${assertion.pointer}`);};
export type DatabaseRequirementSource={sql:string;config:string;roles:string};
const requireSql=(source:DatabaseRequirementSource,needles:string[])=>{for(const needle of needles)if(!source.sql.toLowerCase().includes(needle.toLowerCase()))throw Error(`database predicate missing: ${needle}`);};
export function evaluateDatabaseRequirement(id:string,provided?:DatabaseRequirementSource){const root=process.cwd(),read=(p:string)=>fs.readFileSync(path.join(root,p),'utf8'),source=provided??{sql:fs.readdirSync(path.join(root,'supabase/migrations')).filter(x=>x.endsWith('.sql')).sort().map(x=>read(`supabase/migrations/${x}`)).join('\n'),config:read('supabase/config.toml'),roles:read('supabase/roles.sql')};
 if(id==='DATA-001'){if(!/^schemas\s*=\s*\["public",\s*"graphql_public"\]/mu.test(source.config)||source.config.match(/^schemas\s*=/gmu)?.length!==1)throw Error('Data API schema exposure drift');requireSql(source,['create schema if not exists private','revoke all on schema private from public, anon, authenticated, service_role','alter default privileges for role postgres in schema private revoke all on tables from public, anon, authenticated, service_role']);return true;}
 if(id==='DATA-002'){requireSql(source,['create table public.game_content_revisions','create table private.game_content_solutions','create table private.content_rights_manifests','create table private.content_publish_attestations','create view public.game_content_catalog']);return true;}
 if(id==='DATA-003'){requireSql(source,['unique(content_id, version)','public_content_hash text not null unique','schema_version text not null','asset_policy_version text not null','validator_version text not null','status text not null','approved_at timestamptz','game_content_revisions_immutable']);return true;}
 if(id==='DATA-004'){requireSql(source,['content_revision_id uuid primary key references public.game_content_revisions(content_revision_id) on delete restrict','private_solution jsonb not null','private_solution_hash text not null unique','game_content_solutions_immutable']);return true;}
 if(id==='DATA-005'){requireSql(source,['create table private.content_rights_manifests','manifest jsonb not null','manifest_hash text not null unique','content_rights_manifests_immutable']);return true;}
 if(id==='DATA-006'){requireSql(source,['create table private.content_publish_attestations','validator_version text not null','public_content_hash text not null','database_role text not null','session_role text not null','invoked_role text not null','content_publish_attestations_immutable']);return true;}
 if(id==='DATA-007'){requireSql(source,['create view public.game_content_catalog','with (security_invoker = true)',"where status = 'PUBLISHED' and approved_at is not null",'grant select on public.game_content_catalog to anon, authenticated','revoke all on public.game_content_catalog from public, service_role']);return true;}
 if(id==='DATA-008'){requireSql(source,['private.legacy_game_contents_quarantine','private.legacy_match_events_quarantine','private.legacy_matches_quarantine','to_jsonb(game_contents)','to_jsonb(match_events)','drop table public.match_events','drop table public.game_contents']);return true;}
 if(id==='DATA-009'){requireSql(source,['create role game_security_owner nologin noinherit nosuperuser nocreatedb nocreaterole noreplication','owner to game_security_owner']);return true;}
 if(id==='DATA-010'){requireSql(source,['create role deployment_role nologin noinherit nosuperuser nocreatedb nocreaterole noreplication','grant execute on function private.publish_content_revision_v1(jsonb,jsonb,jsonb,text,text,text,text) to deployment_role','revoke execute on function private.publish_content_revision_v1(jsonb,jsonb,jsonb,text,text,text,text) from public, anon, authenticated, service_role, app_server']);const grants=[...source.sql.matchAll(/grant execute on function ([^;]+) to deployment_role/giu)].flatMap(x=>x[1].split(',').map(y=>y.trim()));if(grants.some(x=>!x.startsWith('private.publish_content_revision_v1(')))throw Error('deployment_role exact execute surface drift');return true;}
 if(id==='DATA-011'){requireSql(source,['create role app_server nologin noinherit nosuperuser nocreatedb nocreaterole noreplication','grant execute on function private.join_match_participant_v1(uuid,uuid,uuid) to app_server','revoke execute on function private.join_match_participant_v1(uuid,uuid,uuid) from public, anon, authenticated, service_role, deployment_role']);const grants=[...source.sql.matchAll(/grant execute on function ([^;]+) to app_server/giu)].flatMap(x=>x[1].split(',').map(y=>y.trim()));if(grants.some(x=>!x.startsWith('private.join_match_participant_v1(')))throw Error('app_server exact execute surface drift');return true;}
 if(id==='DATA-012'){requireSql(source,['grant game_security_owner to postgres','revoke game_security_owner from postgres']);if(!source.roles.includes('grant app_server, deployment_role to postgres')||!source.roles.includes('do not deploy this file with --include-roles'))throw Error('local role bootstrap boundary drift');return true;}
 if(id==='DATA-013'){for(const signature of ['private.publish_content_revision_v1(jsonb,jsonb,jsonb,text,text,text,text)','private.join_match_participant_v1(uuid,uuid,uuid)'])requireSql(source,[`alter function ${signature} owner to game_security_owner`,`revoke execute on function ${signature} from public, anon, authenticated, service_role`,`grant execute on function ${signature}`]);if((source.sql.match(/security definer/giu)?.length??0)<2||(source.sql.match(/set search_path = pg_catalog/giu)?.length??0)<2)throw Error('definer hardening drift');return true;}
 throw Error('unsupported database requirement');}
export function evaluatePureGameRequirement(id:string){
 const bundle=createTestingReplayBundle(),state:MatchStateV1=structuredClone(bundle.initialState),m=state.matchId;
 if(id==='STATE-001'){replayMatch(bundle);if(testingRules.time.playingMs!==75000||testingRules.time.meaningSettlementCapMs!==80000)throw Error('time boundary drift');let rejected=false;try{replayMatch({...bundle,rulesetHash:'0'.repeat(64)});}catch{rejected=true;}if(!rejected)throw Error('boundary mutation accepted');return true;}
 if(id==='STATE-009'){const cancelled=reduceMatch(state,{source:'SYSTEM',commandId:`${m}:system:no-contest:oracle`,systemCommandId:`${m}:system:no-contest:oracle`,matchId:m,commandSeq:1,receivedAtMs:1,payload:{type:'CANCEL_NO_CONTEST',incidentId:'oracle',reason:'SERVER_OWNERSHIP_LOST'}},testingRules);if(cancelled.state.phase!=='CANCELLED'||cancelled.state.endReason!=='NO_CONTEST')throw Error('terminal transition');return true;}
 if(id==='OBS-012'){const requestId='00000000-0000-4000-8000-000000000991';let rejected=false;try{replayMatch({...bundle,commands:[{source:'PLAYER',commandId:`${m}:player:p1:${requestId}`,matchId:m,commandSeq:2,receivedAtMs:1,requestId,playerId:'p1',expectedRevision:0,payload:{type:'USE_HINT'}}]});}catch{rejected=true;}if(!rejected)throw Error('sequence gap accepted');return true;}
 if(id==='OBS-013'){const disconnectId=`${m}:system:connection:p1:1:DISCONNECTED`;const disconnected=reduceMatch(state,{source:'SYSTEM',commandId:disconnectId,systemCommandId:disconnectId,matchId:m,commandSeq:1,receivedAtMs:10000,payload:{type:'PLAYER_CONNECTION_CHANGED',playerId:'p1',disconnectEpoch:1,status:'DISCONNECTED'}},testingRules);const timerId=`${m}:timer:DISCONNECT_FORFEIT_TIMEOUT:p1:1`;const ended=reduceMatch(disconnected.state,{source:'TIMER',commandId:timerId,timerId,matchId:m,commandSeq:2,receivedAtMs:25000,dueAtMs:25000,payload:{type:'DISCONNECT_FORFEIT_TIMEOUT',playerId:'p1',disconnectEpoch:1}},testingRules);if(ended.state.endReason!=='FORFEIT'||ended.state.winnerPlayerId!=='p2')throw Error('deadline timer did not win');return true;}
 if(id==='OBS-011'){const commandId=`${m}:system:no-contest:oracle`;const ended=reduceMatch(state,{source:'SYSTEM',commandId,systemCommandId:commandId,matchId:m,commandSeq:1,receivedAtMs:1,payload:{type:'CANCEL_NO_CONTEST',incidentId:'oracle',reason:'BOTH_DISCONNECTED'}},testingRules);if(ended.state.phase!=='CANCELLED'||ended.state.endReason!=='NO_CONTEST'||ended.state.winnerPlayerId!==null)throw Error('both players lost');return true;}
 if(id==='OBS-001'){const member=resolveAuthenticatedParticipant('auth-subject',[{authSubject:'auth-subject',matchId:m,participantKey:'p1'}],m,'00000000-0000-4000-8000-000000000991');if(member!=='p1'||decideDelivery({lastEventSeq:1,stateRevision:1},{kind:'EVENT',eventSeq:3,stateRevision:2})!=='REQUEST_REPLAY'||decideDelivery({lastEventSeq:1,stateRevision:1},{kind:'REPLAY_UNAVAILABLE'})!=='REPLACE_SNAPSHOT'||decideReconnect(14999)!=='RESUME'||decideReconnect(15000)!=='FORFEIT')throw Error('recovery authority drift');return true;}
 if(id==='OBS-003'){for(const key of ['score','correctAnswer','winnerPlayerId','activeMission','buff','answerUntilMs']){let accepted=true;try{clientCommandEnvelopeSchema.parse({protocolVersion:1,requestId:'00000000-0000-4000-8000-000000000991',matchId:m,expectedRevision:0,clientSeq:0,payload:{type:'USE_HINT',[key]:1}});}catch{accepted=false;}if(accepted)throw Error(`client authority accepted: ${key}`);}return true;}
 if(id==='OBS-005'){state.phase='PLAYING';state.startedAtMs=0;state.gameplayClosesAtMs=testingRules.time.playingMs;state.settlementCapAtMs=testingRules.time.meaningSettlementCapMs;const tap=(x:number,seq:number)=>{const requestId=`00000000-0000-4000-8000-${String(990+seq).padStart(12,'0')}`;return reduceMatch(state,{source:'PLAYER',commandId:`${m}:player:p1:${requestId}`,matchId:m,commandSeq:seq,receivedAtMs:1000,requestId,playerId:'p1',expectedRevision:0,payload:{type:'TAP_IMAGE',imageSide:'A',x,y:.2}},testingRules)};if(!tap(.1,1).events.some(e=>e.type==='TAP_RESOLVED'&&e.payload.hit===true)||!tap(.13,2).events.some(e=>e.type==='TAP_RESOLVED'&&e.payload.hit===false))throw Error('coordinate validation drift');return true;}
 if(id==='OBS-008'){let accepted=true;try{clientCommandEnvelopeSchema.parse({protocolVersion:1,requestId:'00000000-0000-4000-8000-000000000991',matchId:m,expectedRevision:0,clientSeq:0,payload:{type:'TAP_IMAGE',imageSide:'A',x:.1,y:.2,score:999}});}catch{accepted=false;}if(accepted)throw Error('client score accepted');return true;}
 if(id==='OBS-009'){if(reconnectOverlayForElapsed(4999)!=='RECONNECTING'||reconnectOverlayForElapsed(5000)!=='OFFLINE'||decideReconnect(14999)!=='RESUME'||decideReconnect(15000)!=='FORFEIT')throw Error('reconnect boundaries drift');return true;}
 throw Error('unsupported pure game requirement');
}
const readyPayload={type:'READY' as const,contentRevisionId:'00000000-0000-4000-8000-000000000010',contentHash:'d'.repeat(64),assetHashes:['a'.repeat(64),'c'.repeat(64)]as[string,string],decodedDimensions:[{assetHash:'a'.repeat(64),width:1,height:1},{assetHash:'c'.repeat(64),width:1,height:1}]as[{assetHash:string;width:number;height:number},{assetHash:string;width:number;height:number}]};
export function evaluateSecurityRequirement(id:string){const bundle=createTestingReplayBundle(),state:MatchStateV1=structuredClone(bundle.initialState),m=state.matchId;const command=(playerId:string,seq:number)=>{const requestId=`00000000-0000-4000-8000-${String(990+seq).padStart(12,'0')}`;return{source:'PLAYER' as const,commandId:`${m}:player:${playerId}:${requestId}`,matchId:m,commandSeq:seq,receivedAtMs:1000,requestId,playerId,expectedRevision:state.stateRevision,payload:readyPayload};};
 if(id==='SEC-001'){const pinned={protocolVersion:1 as const,engineVersion:'1',rulesetVersion:'1.0.0' as const,rulesetHash:'a'.repeat(64),contentRevisionId:readyPayload.contentRevisionId,contentHash:'d'.repeat(64)};if(negotiateCompatibility({protocolVersion:1,supportedEngineVersions:['2'],supportedRulesetVersions:['1.0.0']},pinned).accepted!==false)throw Error('update admission');clientCommandEnvelopeSchema.parse({protocolVersion:1,requestId:'00000000-0000-4000-8000-000000000991',matchId:m,expectedRevision:0,clientSeq:0,payload:{type:'USE_HINT'}});if(decideDelivery({lastEventSeq:2,stateRevision:2},{kind:'EVENT',eventSeq:4,stateRevision:3})!=='REQUEST_REPLAY')throw Error('journal gap');return true;}
 if(id==='SEC-002'){const pkg=JSON.parse(fs.readFileSync(path.resolve('apps/mobile/package.json'),'utf8'));if(pkg.dependencies.expo!=='57.0.1'||pkg.dependencies['react-native']!=='0.86.0')throw Error('mobile stack drift');const snapshot=projectSnapshot(state,'p1',0),vm=adaptMatchSnapshot(snapshot,{pendingIntentId:'pending',connection:'CONNECTED'});if(createTapIntent(vm,{side:'A',x:.1,y:.2})!==null||JSON.stringify(snapshot).includes('privateSolution'))throw Error('public fail closed');return true;}
 if(id==='SEC-004'){let accepted=true;try{clientCommandEnvelopeSchema.parse({protocolVersion:1,requestId:'00000000-0000-4000-8000-000000000991',matchId:m,expectedRevision:0,clientSeq:0,payload:{type:'TAP_IMAGE',imageSide:'A',x:.1,y:.2,score:1}});}catch{accepted=false;}if(accepted)throw Error('client score authority');return true;}
 if(id==='SEC-005'){const snapshot=projectSnapshot(state,'p1',0);if(state.startedAtMs!==null||snapshot.preload.assets.length!==2||snapshot.phase!=='WAITING_FOR_ASSETS')throw Error('preload ordering');return true;}
 if(id==='SEC-006'){if(RECOMMENDED_IMAGE_LONG_EDGE_PX!==1536)throw Error('asset recommendation drift');return true;}
 if(id==='SEC-007'){const first=reduceMatch(state,command('p1',1),testingRules);if(first.state.phase!=='WAITING_FOR_ASSETS')throw Error('single ack started');const secondCommand=command('p2',2);secondCommand.expectedRevision=first.state.stateRevision;const second=reduceMatch(first.state,secondCommand,testingRules);if(second.state.phase!=='COUNTDOWN')throw Error('both ack did not start');return true;}
 throw Error('unsupported security requirement');}
export function evaluateAnalyticsRequirement(id:string){const base={eventVersion:1,eventSeq:1,stateRevision:0,occurredAt:'2026-07-19T00:00:00.000Z',matchId:'match_opaque',anonymousUserId:'anon_rotating',traceId:'trace_opaque',engineVersion:'1.0.0',rulesetVersion:'1.0.0',contentRevisionId:'content_1',experimentVariant:'CONTROL',serverVersion:'server_1',protocolVersion:1};if(id==='OBS-006'){parseAnalyticsEventV1({...base,name:'same_coordinate_burst_signal',data:{cellBucket:'03:12',countBucket:'8-15',windowDurationBucket:'1-2s'}});let rejected=false;try{parseAnalyticsEventV1({...base,name:'same_coordinate_burst_signal',data:{x:.5,y:.5,timestamp:1}});}catch{rejected=true;}if(!rejected)throw Error('raw coordinates accepted');return true;}if(id==='OBS-007'){parseAnalyticsEventV1({...base,name:'answer_reaction_time_signal',data:{durationBucket:'250-499ms'}});return true;}if(id==='OBS-014'){const stages=['queue','handshake','preload','command','finish','reward']as const,rows=stages.map((stage,i)=>({stage,eventSeq:i+1,traceId:'trace_opaque_x',matchId:'match_opaque_x',requestId:`request_opaque_${i}`,...(stage==='reward'?{effectId:'effect_opaque_x'}:{})}));validateLifecycleTrace(rows);const collector=new AnalyticsCollector();collector.recordRequest({requestId:'r',outcome:'UNEXPECTED_FAILURE',reason:'ACK_TIMEOUT',occurredAtMs:1});collector.recordRequest({requestId:'r',outcome:'SUCCESS',occurredAtMs:2});if(collector.snapshot().uniqueSchemaValidRequests!==1||collector.snapshot().unexpectedFailures!==0)throw Error('terminal retry grouping');return true;}if(id==='OBS-015'){const samples=Array.from({length:10000},(_,i)=>({requestId:`r${i}`,outcome:'SUCCESS'as const,occurredAtMs:i*100,durationMs:1,concurrency:100,schemaValid:true,duplicateClaim:false,duplicateReward:false,finishLost:false})),result=evaluateLoadSamples(samples,{soakStartMs:0,soakEndMs:1800000,expectedConcurrency:100});if(result.full30m.denominator!==10000||result.evidenceScope!=='DETERMINISTIC_LOCAL_NOT_PRODUCTION')throw Error('load evidence');return true;}throw Error('unsupported analytics requirement');}
export function executeRequirementOracle(root:string,row:Row,claim:Claim){
 let status:RequirementGateResult='FAIL';
 try{
  const line=fs.readFileSync(path.join(root,row.source),'utf8').split(/\r?\n/u)[row.sourceLine-1]??'';
  if(!line.includes(`<!-- REQ: ${row.id} -->`)||!line.includes(row.text))throw Error('source projection mismatch');
  if(claim.lifecycle&&claim.lifecycle!=='CURRENT'){
   if(!validateNonCurrentEvidence(root,claim))throw Error('invalid lifecycle closure evidence');status='BLOCKED';
  }else switch(claim.oracle.kind){
   case'STATE_SCHEMA':evaluatePureGameRequirement(row.id);status='PASS';break;
   case'PRIVACY_CONTRACT':evaluateSecurityRequirement(row.id);status='PASS';break;
   case'ANALYTICS_CONTRACT':if(['OBS-001','OBS-003','OBS-005','OBS-008','OBS-009','OBS-011','OBS-012','OBS-013'].includes(row.id))evaluatePureGameRequirement(row.id);else evaluateAnalyticsRequirement(row.id);status='PASS';break;
   case'RULESET_PARSE':{const value=JSON.parse(fs.readFileSync(path.join(root,claim.oracle.input??'config/ruleset.v1.json'),'utf8'));parseRuleset(value);assertExact(value,claim.oracle.assertions);status='PASS';break;}
   case'ECONOMY_PARSE':{const value=JSON.parse(fs.readFileSync(path.join(root,claim.oracle.input??'config/economy.v1.json'),'utf8'));parseEconomy(value);assertExact(value,claim.oracle.assertions);status='PASS';break;}
   case'UI_CONTRACT':{const value=JSON.parse(fs.readFileSync(path.join(root,claim.oracle.input??'config/ui-screen-contract.v1.json'),'utf8')),load=(file:string)=>JSON.parse(fs.readFileSync(path.join(root,file),'utf8')),bundle={theme:load('config/ui-theme.v1.json'),screens:value,references:load('docs/design/ui-reference/manifest.json'),rights:load('docs/design/ui-reference/rights-manifest.json')};if(validateUiReferenceBundle(bundle).length)throw Error('UI bundle invalid');assertExact(value,claim.oracle.assertions);status='PASS';break;}
   case'DB_PROJECTION':evaluateDatabaseRequirement(row.id);status='PASS';break;
   default:throw Error('missing current executable oracle');
  }
 }catch{status='FAIL';}
 return{status,metric:emitRequirementGateStatus(row.id,status)};
}
