import fs from'node:fs';import path from'node:path';
import{parseRuleset}from'../packages/contracts/src/rules.schema.js';
import{parseEconomy}from'../packages/contracts/src/economy.schema.js';
import{emitRequirementGateStatus,type RequirementGateResult}from'../packages/contracts/src/analytics.js';
const externalKinds=new Set(['EXACT_RUNTIME','DEVICE_GOLDEN','PROVIDER_CREDENTIALS','TARGET_REGION_SOAK','LEGAL_APPROVAL','RIGHTS_APPROVAL','PRODUCT_DECISION']);
export function validateNonCurrentEvidence(root:string,claim:{lifecycle:string;closureCondition?:string;closureArtifact?:string;closureArtifactState?:'ABSENT'|'PRESENT';externalKind?:string;localSubstitute?:string}){if(!claim.closureCondition)return false;if(claim.lifecycle==='PLANNED')return!!claim.closureArtifact&&claim.closureArtifactState==='ABSENT'&&!fs.existsSync(path.join(root,claim.closureArtifact));if(claim.lifecycle==='EXTERNAL')return externalKinds.has(claim.externalKind??'')&&!!claim.localSubstitute&&!fs.existsSync(path.join(root,claim.localSubstitute));return false;}

type Row={id:string;source:string;sourceLine:number;text:string};
type Assertion={pointer:string;expected:unknown};type Claim={lifecycle?:'CURRENT'|'PLANNED'|'EXTERNAL';oracle:{kind:string;expected:RequirementGateResult;input?:string;assertions?:Assertion[]};blockerReason?:string;closureCondition?:string;closureArtifact?:string;closureArtifactState?:'ABSENT'|'PRESENT';externalKind?:string;localSubstitute?:string};
const resolve=(value:unknown,pointer:string)=>pointer.split('/').slice(1).reduce<unknown>((current,key)=>current!==null&&typeof current==='object'?(current as Record<string,unknown>)[key]:undefined,value);
const assertExact=(value:unknown,assertions:Assertion[]|undefined)=>{if(!assertions?.length)throw Error('exact assertions required');for(const assertion of assertions)if(JSON.stringify(resolve(value,assertion.pointer))!==JSON.stringify(assertion.expected))throw Error(`SSOT mismatch ${assertion.pointer}`);};
export function executeRequirementOracle(root:string,row:Row,claim:Claim){let status:RequirementGateResult='FAIL';try{const line=fs.readFileSync(path.join(root,row.source),'utf8').split(/\r?\n/u)[row.sourceLine-1]??'';if(!line.includes(`<!-- REQ: ${row.id} -->`)||!line.includes(row.text))throw Error('source projection mismatch');if(claim.lifecycle&&claim.lifecycle!=='CURRENT'){if(!validateNonCurrentEvidence(root,claim))throw Error('invalid lifecycle closure evidence');status='BLOCKED';}else switch(claim.oracle.kind){case'RULESET_PARSE':{const value=JSON.parse(fs.readFileSync(path.join(root,claim.oracle.input??'config/ruleset.v1.json'),'utf8'));parseRuleset(value);assertExact(value,claim.oracle.assertions);status='PASS';break;}case'ECONOMY_PARSE':{const value=JSON.parse(fs.readFileSync(path.join(root,claim.oracle.input??'config/economy.v1.json'),'utf8'));parseEconomy(value);assertExact(value,claim.oracle.assertions);status='PASS';break;}case'ANALYTICS_CONTRACT':throw Error('missing exact analytics oracle');default:throw Error('missing current executable oracle');}}catch{status='FAIL';}return{status,metric:emitRequirementGateStatus(row.id,status)};}
