import fs from'node:fs';import path from'node:path';
import{parseRuleset}from'../packages/contracts/src/rules.schema.js';
import{parseEconomy}from'../packages/contracts/src/economy.schema.js';
import{emitRequirementGateStatus,type RequirementGateResult}from'../packages/contracts/src/analytics.js';
import{validateUiReferenceBundle}from'../packages/contracts/src/ui.js';
import{createTestingReplayBundle,testingRules}from'../packages/game-engine/src/testing-fixtures.js';import{reduceMatch}from'../packages/game-engine/src/reducer.js';import{replayMatch}from'../packages/game-engine/src/replay.js';
const externalKinds=new Set(['EXACT_RUNTIME','DEVICE_GOLDEN','PROVIDER_CREDENTIALS','TARGET_REGION_SOAK','LEGAL_APPROVAL','RIGHTS_APPROVAL','PRODUCT_DECISION']);
export function validateNonCurrentEvidence(root:string,claim:{lifecycle:string;closureCondition?:string;closureArtifact?:string;closureArtifactState?:'ABSENT'|'PRESENT';externalKind?:string;localSubstitute?:string}){if(!claim.closureCondition)return false;if(claim.lifecycle==='PLANNED')return!!claim.closureArtifact&&claim.closureArtifactState==='ABSENT'&&!fs.existsSync(path.join(root,claim.closureArtifact));if(claim.lifecycle==='EXTERNAL')return externalKinds.has(claim.externalKind??'')&&!!claim.localSubstitute&&!fs.existsSync(path.join(root,claim.localSubstitute));return false;}

type Row={id:string;source:string;sourceLine:number;text:string};
type Assertion={pointer:string;expected:unknown};type Claim={lifecycle:'CURRENT'|'PLANNED'|'EXTERNAL';oracle:{kind:string;expected:RequirementGateResult;input?:string;assertions?:Assertion[]};blockerReason?:string;closureCondition?:string;closureArtifact?:string;closureArtifactState?:'ABSENT'|'PRESENT';externalKind?:string;localSubstitute?:string};
const resolve=(value:unknown,pointer:string)=>pointer.split('/').slice(1).reduce<unknown>((current,key)=>current!==null&&typeof current==='object'?(current as Record<string,unknown>)[key]:undefined,value);
const assertExact=(value:unknown,assertions:Assertion[]|undefined)=>{if(!assertions?.length)throw Error('exact assertions required');for(const assertion of assertions)if(JSON.stringify(resolve(value,assertion.pointer))!==JSON.stringify(assertion.expected))throw Error(`SSOT mismatch ${assertion.pointer}`);};
export function evaluatePureGameRequirement(id:string){
 const bundle=createTestingReplayBundle(),state=structuredClone(bundle.initialState),m=state.matchId;
 if(id==='STATE-001'){replayMatch(bundle);if(testingRules.time.playingMs!==75000||testingRules.time.meaningSettlementCapMs!==80000)throw Error('time boundary drift');let rejected=false;try{replayMatch({...bundle,rulesetHash:'0'.repeat(64)});}catch{rejected=true;}if(!rejected)throw Error('boundary mutation accepted');return true;}
 if(id==='STATE-009'){const cancelled=reduceMatch(state,{source:'SYSTEM',commandId:`${m}:system:no-contest:oracle`,systemCommandId:`${m}:system:no-contest:oracle`,matchId:m,commandSeq:1,receivedAtMs:1,payload:{type:'CANCEL_NO_CONTEST',incidentId:'oracle',reason:'SERVER_OWNERSHIP_LOST'}},testingRules);if(cancelled.state.phase!=='CANCELLED'||cancelled.state.endReason!=='NO_CONTEST')throw Error('terminal transition');return true;}
 if(id==='OBS-012'){const requestId='00000000-0000-4000-8000-000000000991';let rejected=false;try{replayMatch({...bundle,commands:[{source:'PLAYER',commandId:`${m}:player:p1:${requestId}`,matchId:m,commandSeq:2,receivedAtMs:1,requestId,playerId:'p1',expectedRevision:0,payload:{type:'USE_HINT'}}]});}catch{rejected=true;}if(!rejected)throw Error('sequence gap accepted');return true;}
 if(id==='OBS-013'){const disconnectId=`${m}:system:connection:p1:1:DISCONNECTED`;const disconnected=reduceMatch(state,{source:'SYSTEM',commandId:disconnectId,systemCommandId:disconnectId,matchId:m,commandSeq:1,receivedAtMs:10000,payload:{type:'PLAYER_CONNECTION_CHANGED',playerId:'p1',disconnectEpoch:1,status:'DISCONNECTED'}},testingRules);const timerId=`${m}:timer:DISCONNECT_FORFEIT_TIMEOUT:p1:1`;const ended=reduceMatch(disconnected.state,{source:'TIMER',commandId:timerId,timerId,matchId:m,commandSeq:2,receivedAtMs:25000,dueAtMs:25000,payload:{type:'DISCONNECT_FORFEIT_TIMEOUT',playerId:'p1',disconnectEpoch:1}},testingRules);if(ended.state.endReason!=='FORFEIT'||ended.state.winnerPlayerId!=='p2')throw Error('deadline timer did not win');return true;}
 throw Error('unsupported pure game requirement');
}
export function executeRequirementOracle(root:string,row:Row,claim:Claim){let status:RequirementGateResult='FAIL';try{const line=fs.readFileSync(path.join(root,row.source),'utf8').split(/\r?\n/u)[row.sourceLine-1]??'';if(!line.includes(`<!-- REQ: ${row.id} -->`)||!line.includes(row.text))throw Error('source projection mismatch');if(claim.lifecycle&&claim.lifecycle!=='CURRENT'){if(!validateNonCurrentEvidence(root,claim))throw Error('invalid lifecycle closure evidence');status='BLOCKED';}else switch(claim.oracle.kind){case'STATE_SCHEMA':case'ANALYTICS_CONTRACT':{evaluatePureGameRequirement(row.id);status='PASS';break;}case'RULESET_PARSE':{const value=JSON.parse(fs.readFileSync(path.join(root,claim.oracle.input??'config/ruleset.v1.json'),'utf8'));parseRuleset(value);assertExact(value,claim.oracle.assertions);status='PASS';break;}case'ECONOMY_PARSE':{const value=JSON.parse(fs.readFileSync(path.join(root,claim.oracle.input??'config/economy.v1.json'),'utf8'));parseEconomy(value);assertExact(value,claim.oracle.assertions);status='PASS';break;}case'UI_CONTRACT':{const value=JSON.parse(fs.readFileSync(path.join(root,claim.oracle.input??'config/ui-screen-contract.v1.json'),'utf8')),load=(file:string)=>JSON.parse(fs.readFileSync(path.join(root,file),'utf8')),bundle={theme:load('config/ui-theme.v1.json'),screens:value,references:load('docs/design/ui-reference/manifest.json'),rights:load('docs/design/ui-reference/rights-manifest.json')};if(validateUiReferenceBundle(bundle).length)throw Error('UI bundle invalid');assertExact(value,claim.oracle.assertions);status='PASS';break;}default:throw Error('missing current executable oracle');}}catch{status='FAIL';}return{status,metric:emitRequirementGateStatus(row.id,status)};}
