import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import frozenRuleset from '../config/ruleset.v1.json' with { type: 'json' };
import { parseRuleset, rulesetHash } from '../packages/contracts/src/rules.schema.js';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const outputPath = resolve(root, 'supabase/ruleset-content.generated.sql');
const migrationPath = resolve(root, 'supabase/migrations/202607150002_content_security.sql');

export function renderRulesetProjection(): string {
  const rules = parseRuleset(frozenRuleset);
  return [
    '-- GENERATED by tools/write-ruleset-projections.ts from validated config/ruleset.v1.json.',
    '-- This projection is verification input, never an independent authority.',
    `-- rulesetVersion=${rules.rulesetVersion} rulesetHash=${rulesetHash(rules)}`,
    `-- normalDifferences=${rules.content.normalDifferences}`,
    `-- hardDifferences=${rules.content.hardDifferences}`,
    `-- wordHunts=${rules.content.wordHunts}`,
    '',
  ].join('\n');
}

export async function checkRulesetProjection(actualOverride?: string, migrationOverride?: string): Promise<void> {
  const expected = renderRulesetProjection();
  const actual = actualOverride ?? await readFile(outputPath, 'utf8');
  if (actual !== expected) throw new Error('RULESET_PROJECTION_BYTE_DRIFT');

  const rules = parseRuleset(frozenRuleset);
  const migration = migrationOverride ?? await readFile(migrationPath, 'utf8');
  const expectedSnippets = [
    `jsonb_array_length(requested_private_solution->'differences') <> ${rules.content.normalDifferences + rules.content.hardDifferences}`,
    `jsonb_array_length(requested_private_solution->'wordHunts') <> ${rules.content.wordHunts}`,
    `item->>'tier'='NORMAL') <> ${rules.content.normalDifferences}`,
    `item->>'tier'='HARD') <> ${rules.content.hardDifferences}`,
    `item->>'kind'='NORMAL') <> ${rules.content.wordHunts - 1}`,
    `item->>'kind'='SPECIAL') <> 1`,
  ];
  for (const snippet of expectedSnippets) {
    if (!migration.includes(snippet)) throw new Error(`RULESET_PROJECTION_SQL_DRIFT: ${snippet}`);
  }
}

async function main(): Promise<void> {
  if (process.argv.includes('--check')) await checkRulesetProjection();
  else await writeFile(outputPath, renderRulesetProjection(), 'utf8');
}

if (resolve(process.argv[1] ?? '') === fileURLToPath(import.meta.url)) await main();
