/**
 * Generated by `pnpm audio:music` from config/audio-rights-evidence.v1.json. Do not edit.
 *
 * Both lists come from the rights record, which is what makes the credit obligation
 * un-forgettable: a CC-BY track cannot be added to the game without its line landing here.
 */

import type { MusicTrack } from './music-model';

export const LICENSED_TRACKS: readonly MusicTrack[] = [
  { file: 'relax-pleasant-porridge.mp3', mood: 'RELAX', gain: 1 },
  { file: 'rush-brain-dance.mp3', mood: 'RUSH', gain: 0.85 },
  { file: 'lobby-sergios-magic-dustbin.mp3', mood: 'LOBBY', gain: 0.9 },
];

/** Shown on the credits screen. Empty only when nothing licensed needs attribution. */
export const AUDIO_CREDITS: readonly string[] = [
  "\"Brain Dance\" Kevin MacLeod (incompetech.com) — Licensed under Creative Commons: By Attribution 4.0 — http://creativecommons.org/licenses/by/4.0/",
  "\"Pleasant Porridge\" Kevin MacLeod (incompetech.com) — Licensed under Creative Commons: By Attribution 4.0 — http://creativecommons.org/licenses/by/4.0/",
  "\"Sergio's Magic Dustbin\" Kevin MacLeod (incompetech.com) — Licensed under Creative Commons: By Attribution 4.0 — http://creativecommons.org/licenses/by/4.0/",
];
